### ISSUE TITLE
On windows, in some cases, NetworkParams.getHostName() return localhost

### ISSUE THREAD

**Issue by jflefebvre06** [oshi/oshi#1006]
On windows, getHostName() should use Kernel32Util.getComputerName().

See https://github.com/mattsheppard/gethostname4j

**Comment by dbwiddis** [comment]
Sounds like a good improvement. Would you like to submit a PR or shall I toss this to the first timers?

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

Per the report above, the `WindowsNetworkParams` implementation should return the (unambiguous) Windows computer name rather than the result of `InetAddress.getLocalHost().getHostName()`.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- In the [`WindowsNetworkParams`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java) class, override the `getHostName()` method and return the value from `Kernel32Util.getComputerName()`.
- Optionally, override the Mac, Linux, Solaris, and BSD versions of the method to return the result from the respective platform's `LibC` class (eventually inheriting from JNA's `LibCAPI`) method `getHostName()`.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by 2kindsofcs** [comment]
I'd like to take this issue.

**Comment by dbwiddis** [comment]
It's yours! Let me know if you need any help.
