### ISSUE TITLE
getProcess(pid) is extremely slow (at least on Windows)

### ISSUE THREAD

**Issue by jgoeres** [oshi/oshi#1029]
Hi,
we are currently evaluating Oshi as a replacement for SIGAR to monitor our product. Amongst other things, we want to observe CPU and memory usage of all processes of our product. We already have a list of PIDs (obtained via Java Process API). Seems the way to get CPU and mem usage is through the OSProcess class. Alas, creating such an instance from the PID with 

    OperatingSystem.getProcess(pid)

is reaaaally slow - measured in several seconds rather than milliseconds.
I did a short dive into Oshi code and found that even when passing a single PID, a whole bunch of information about seemingly all(?) processes is loaded via WMI and then the result for the desired PID is built. 
Is there any way you could improve that API to make obtaining OSProcess instances for individual PIDs faster? Or how about not querying everything that the OS offers, at least until needed.

Regards

J

**Comment by dbwiddis** [comment]
Windows process list speed has long been a headache!

There is a boolean `slowFields` that you can set false when fetching the full process list, but we don't offer that for a single process query.  `OperatingSystem.getProcess(pid)` does grab some of the "slower" information that the full process list doesn't, but at this time is just fetching the group information which should be only about 10ms.

The WMI call for "all data" is only used pre-Windows7, and even then the WMI query is filtered to ask only about the processes you are asking about.  For Windows 7 and later, the `WTSEnumerateProcessesEx()` function is called to retrieve the info.

There is one bit of information (process command line) that requires a WMI query for all processes (again, filtered only to the one(s) you are asking about).

We did recently change from reading process stats from the registry (`HKEY_PERFORMANCE_DATA`) which was very fast, to use the performance counters as suggested by the API, because the registry-reading portion was not robust to non-English registry keys, but that change (#1001) still only changed reading the whole list's stats from a few milliseconds to about 50 milliseconds.  Note the counter-reading code DOES call WMI in the case where the performance counter initialization fails, but that should be unusual on most systems.

I just tried a quick test on my (relatively slow) system (Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz):

```
        long now = System.nanoTime();
        List<OSProcess> procs = Arrays.asList(os.getProcesses(0, null));
        long delta = System.nanoTime() - now;
        System.out.println("All process list: " + delta / 1_000_000d + "ms");
        int pid = os.getProcessId();

        now = System.nanoTime();
        procs = Arrays.asList(os.getProcesses(0, null, false));
        delta = System.nanoTime() - now;
        System.out.println("All process list (no slowfields): " + delta / 1_000_000d + "ms");

        now = System.nanoTime();
        OSProcess p = os.getProcess(pid);
        delta = System.nanoTime() - now;
        System.out.println("Get this process: " + delta / 1_000_000d + "ms");
```
Results:

> All process list: 842.1762ms
> All process list (no slowfields): 574.624601ms
> Get this process: 227.2306ms

I do see that you say you have "a list of PIDs (obtained via Java Process API)", and OSHI does allow querying an entire list of PIDs at once (filtering to that list) rather than iterating over each one.  Are you using this method?

**Comment by jgoeres** [comment]
THX for the quick response. I also noticed the "slowFields" parameter, alas the mthod for a single process is private. Any reason to not make it public?

My timing of getProcess() with System.currentTimeMillis() looks like this:

    Creation of new Oshi OSProcess for PID 17940 took 2854ms
    Creation of new Oshi OSProcess for PID 31564 took 346ms
    Creation of new Oshi OSProcess for PID 17940 took 283ms
    Creation of new Oshi OSProcess for PID 31564 took 312ms

Seems that in particular the first call is slow - is this to be expected?

Regarding the use of performance counters: so this is a kind of fallback mechanism? Cause the performance counters seem to be disabled on most of our systems. Not sure why, but maybe a group policy defined by our IT department... When we used SIGAR, we suddenly lost the ability to get process memory usage - the disabled performance counters were the reason. The SIGAR issue https://github.com/hyperic/sigar/issues/77 describes what we observed.
From what I understand, performance counters can be disabled via registry, and they can also be unavailable if the "WMI Performance Adapter" service is not started.

Regarding the method that accepts a list of PIDs: I saw that, too. Alas, I only have the PID (or handful of PIDs) for each of our microservices individually, I do not have them all at once.

**Comment by dbwiddis** [comment]
>  the method with that parameter for a single PID is private. Any reason to not make it public?

Nope!  I thought it was, and was surprised it wasn't.  Happy to change that and/or add a lot more flexibility to the various process methods to try to address your specific use case here.

> Seems that in particular the first call is slow - is this to be expected?

For WMI, yes... the first WMI call (even for a relatively quick query) has to initialize COM which sometimes takes a while... sometimes up to 20 seconds!  This is outside of OSHI, you'd see the same thing on the `wmic` commandline.  I could possibly add the single WMI requirement (when counters are enabled) to the "slowFields" filtering to help avoid that.

It seems the disabled performance counters seem to be an issue for you.  For counters, OSHI attempts to set up a "Perfmon" counter first, and if that fails, uses the equivalent data in a WMI table.  I'm not sure whether the `HKEY_PERFORMANCE_DATA` registry key would work for you in the case that counters are disabled; would be an interesting test case.  Can you test on version 4.0.0 which used the registry for counter info, and see if it's faster for you?

**Comment by dbwiddis** [comment]
Not really benchmarking, but ran 10 cycles through the process list generation.  The first one is slowest for a variety of reasons, but it's clear that the WMI query for process command line is the slowest, and should definitely be added to the `slowFields` limit (which can also be exposed to the API for a single process, particularly when called by the process's "updateAttributes" method!)  Hopefully that will work as an immediate fix.

Loop|WTS Native Call|Process the data|CommandLine Query
---|---|---|---
1|65|140|851
2|19|51|323
3|17|44|218
4|14|72|340
5|24|62|423
6|20|56|277
7|26|60|308
8|19|43|378
9|13|41|211
10|13|45|211

I do have an idea for removing the "slowFields" bit altogether and replacing the getters for those few fields onto a "queryX()" method, which would involve changing the OSProcess from an object to an interface.  It'll be a breaking API change, though, so I'm trying to collect all such similar types of issues and get them out with 5.x, probably early next year. (I wanted to do that with 4.x but didn't quite get there.)

**Comment by dbwiddis** [comment]
Oops, forgot merging the PR closed this.  Reopening until you've tested. :)

**Comment by dbwiddis** [comment]
> As a workaround, I consider a caching mechanism for OSProcess instances - I hope this is acceptable from your perspective, or do I have to get a fresh instance again whenever I need a new measurement? (CPU and mem usage, as I said being what I am interested in the most).

Sorry I missed this comment the first time around.   Originally I did cache a lot of the process info (including command line) which sped up refreshes, but was not thread safe.  There is process caching and an `updateAttributes()` method on the OSProcess object that should allow for much faster refreshes.  As you pointed out, though, the "slowFields" was not implemented on the single process method so even doing that ended up fetching all the info unnecessarily.

I've updated #1030 to expose the `slowFields` boolean to all the various `getProcess(pid)` and `getProcesses()` methods, and updated the `OSProcess.updateAttributes()` method to use the "not slowFields" variant, so that should be a pretty fast update for you.   It's in SNAPSHOT now, if you'd like to test it.   (It may still be slow if your performance counters are disabled, in which case 4.0.0 should be faster.)

**Comment by jgoeres** [comment]
Hi,

THX for reacting so quickly.

I can confirm that Oshi 4.0.0 works significantly faster, but is still rather slow:

Oshi 4.1.0

    Creation of new Oshi OSProcess for PID 17940 took 497ms
    Creation of new Oshi OSProcess for PID 31564 took 4660ms
    Creation of new Oshi OSProcess for PID 17940 took 9545ms
    Creation of new Oshi OSProcess for PID 31564 took 9705ms


Oshi 4.0.0

    Creation of new Oshi OSProcess for PID 17940 took 418ms
    Creation of new Oshi OSProcess for PID 31564 took 217ms
    Creation of new Oshi OSProcess for PID 17940 took 203ms
    Creation of new Oshi OSProcess for PID 31564 took 259ms

About the caching of OSProcess instances that I tried: Problem is that keeping an OSProcess around will of course not update its fields - so,e.g. CPU usage (which we calculated by getting the difference of kernel and user time compared to the previous measurement) now shows 0. So I need to get a new OSProcess instance to get any useful measurements.
I will definitely give the SNAPSHOT a try later, your changes (in particular making the slowFields switch accessible) sound very promising.

For our use case (regularly, i.e., roughly every second(!), monitoring a few properties, CPU & mem usage mostly), I would need an OSProcess-like interface like the one you describe: it should not be a bean into which all properties are materialized when the instance is obtained, but the getters should do the actual query for only the desired value. Of course, once you get more than a few properties that way, the "get everything in one go" approch will at some point be faster again. So depending on use case, both options should be offered.

What would be even better: something like a query-style interface, where I can specify a selection condition (for starters, an optional list of PIDs I am interested in would be fine) and a projection clause (i.e., which fields I am interested in). And the possible selection criteria could later be extended. 

SIGAR had a kind of query language that would even allow you to query for, e.g., "all processes for which the environment variable x has value z". We used that to "mark" our processes with environment variables, allowing us to later find a process and all its children, even if new child processes had been spawned in the meantime (cause at least on windows and in the components that we use, the environment is always fully inherited by child processes, Linux is a different story, though). And to my surprise this process querying was very fast. We could easily run such a query for 10-20 different process trees once a second with only minimal CPU usage. We used that to monitor if a component had crashed. Of course we also "pinged" our processes, but if you use, e.g., an HTTP GET and it fails or takes a long time, you cannot assume that the process has really crashed, but it could just be stuck in a GC or overloaded momentarily, so you would have to wait and retry the "ping" before enacting drastic measures (killing and restarting it). If, however, the process query does not find anymore processes with the particular environment variable "marker", we can be sure that it really crashed and can react much faster (e.g., restarting the component almost immediately).

**Comment by dbwiddis** [comment]
Yeah, the "fetch only what you need" interface design is definitely a rework I plan in version 5.0.   There are some stats that are grabbed together but they'll still be partitioned somewhat. #369 requested the environment variable bit, but it's a lot of overhead for that one piece of information (windows only, elevated privileges).  That's one I doubt I'll do myself but would welcome a PR for.

Keeping the process around and updating *should* work now with the `updateAttributes()` method.  Granted, under the hood it just calls the same methods you're calling in the current version (and obtains a new copy of the process and copies data over) but it's at least a friendlier API (and now has the slowfields boolean, in SNAPSHOT).

The faster query times on the registry counter grab are promising, it does seem that most of your latency is due to the disabled performance counters, and OSHI using WMI as a backup.  I'll see if I can put the registry counters back in, at least as a configurable option.

**Comment by jgoeres** [comment]
Regarding the performance counters: I debugged into Oshi code a bit.
At oshi.util.platform.windows.PerfCounterWildcardQuery#queryValuesWildcard
I definitely saw it going the 

     if source.equals(CounterDataSource.PDH)) { ...

path sometimes, while in my recent debug, it went along

        if (source.equals(CounterDataSource.WMI)) {...

It almost seems as if performance counters are sometimes available, sometimes not. I also had situations where Oshi would log a ton of error messages like this:

    PerfCounterQueryHandler - Counter \Process(putty)\IO Write Bytes/sec does not exist to query.

(and that message, but repeated for all my >100 processes on my machine)
just as if it had decided to use the performance counter branch, and then suddenly they were not available anymore. I will get in touch with our IT department about that.

I also noticed that the 

    oshi.software.os.windows.WindowsOperatingSystem#processMapToList

method always uses 

    oshi.util.platform.windows.PerfCounterWildcardQuery#queryValuesWildcard

which seems to always go over all processes. And that even though I pass a PID (or a handful of PIDs) to it - I would have expected that the PIDs would somehow be used downstream to make querying whatever API (proc counters or WMI) more efficient. Is that something that can be done?

**Comment by jgoeres** [comment]
Disclaimer: I am still trying to get my bearings in Oshi code, and it seems I am not getting far at the moment... There are quite a few things that I don't understand, maybe someone can shed a light on what is going on there:
In

    oshi.util.platform.windows.PerfCounterWildcardQuery#fillCounterListMap

this line 

    objectItems = PdhUtil.PdhEnumObjectItems(null, null, perfObjectLocalized, 100);

creates an objectItems object which holds a String list of counters (i.e., the measurements we are intersted in, right?) and another String list of "instances"... I thought that these were the PIDs of all processes, but in my observation these are just the process **names**:

![image](https://user-images.githubusercontent.com/1484812/67786879-e6159a00-fa6f-11e9-92ba-cdbac557a3d3.png)

It then does stuff with each of the perf counters for each instance. 
What I don't get: why are the instances "identified" by strings? Shouldn't the identifier be the PID? And wouldn't that be a place where we could/should filter and only use the PID of the given OSProcess? 
I find many places like that, and I am sure that there is probably a good reason to do things the way they are done, but I would like to understand why... :-)

What I tried was something like the following to build a custom WMIQuery that additionally filters for PIDs in oshi.software.os.windows.WindowsOperatingSystem#buildProcessMapFromPerfCounters

    String perfWmiClass = "Win32_Process WHERE NOT Name LIKE\"%_Total\" and (";
    Iterator<Integer> pidsIter = pids.iterator();
    while (pidsIter.hasNext()) {
        Integer pid = pidsIter.next();
        perfWmiClass+=" ProcessId = "+ pid +" "+(pidsIter.hasNext() ? " or " : ")");
    }

The query runs okay, but all the initialization that happens in PerfCounterWildcardQuery resp. PerfCounterQuery is doing things for all processes, and that ruins my optimization attempt.

**Comment by dbwiddis** [comment]
> It almost seems as if performance counters are sometimes available, sometimes not. 

Very strange.

> `PerfCounterWildcardQuery#queryValuesWildcard` ... seems to always go over all processes

Unfortunately it's very difficult to filter process performance counters during the query.  They are indexed by name, not by PID (poor design!) and when you have multiple processes the duplicates are just marked with a `#1`, `#2`, etc.  
![image](https://user-images.githubusercontent.com/9291703/67785251-2520fc80-fa2a-11e9-895e-ec476dc326a0.png)

Worse, the `#` labels are not 'sticky' What was `#3` might end up as `#2` the next time you fetch.  So from a PDH "grab instances and then filter for data" we don't have a choice but to grab the entire set of counters and iterate to find the matching PID(s).

While I've copied the above screenshot from "Perfmon" it's the same result you're seeing in native code with the `PdhUtil.PdhEnumObjectItems(null, null, perfObjectLocalized, 100)` call.

We could filter the WMI queries to be faster (and in fact we do in the "CommandLine" case).  That's not presently implemented in the current counter query class where WMI is intended only as a backup for early versions of Windows and disabled counters (or pre-Win7 compatibility), and has thus not been optimized for speed, and I'm not sure that class is the right place to add such a filter.

So, options:

1. I can (and plan to) put back in the registry counter reading (which again will read an entire binary blob of counters and iterate it, rather than filtering by pid, but it will do so quickly!).  The challenge is detecting when that fails.

2. You can try overriding the WMI queries with a custom WMIQueryHandler class, where you could override the existing query methods and insert your own WQL filter.  (This is admittedly a big hack but would work with the existing API.)

3. You could write your own WMI queries in your code (using OSHI as a template) instead of calling OSHI's code.  This would allow you to really customize things particular to your use case.

**Comment by dbwiddis** [comment]
I've just merged #1031 which restores the registry perfcounter reading.... hopefully that still works even if performance counters are disabled (and if so, makes me wonder if that's a bug or feature).  It should be in SNAPSHOT now.

Hopefully this combined with the added `slowFields` boolean in #1030 will work for you... if not... let me know what else to attack with a sledgehammer.

**Comment by dbwiddis** [comment]
Aha.  [This site explains the naming format](https://docs.microsoft.com/en-us/windows/win32/perfctrs/handling-duplicate-instance-names).  It's possible to set a registry value to report the PID appended to the name.  I suppose OSHI could read that registry key and save it, temporarily set it to the value for the PID, read and filter for just those values, and then re-set the originally saved value of the registry key.

Or just iterate them all like we currently do. :)

**Comment by dbwiddis** [comment]
Hi, @jgoeres. Have you had an opportunity to test the improvements I put in?

**Comment by jgoeres** [comment]
Hi @dbwiddis ,
I didn't have the chance to check out #1031 yet, due to project priorities. If I get you right, this will give me the performance of 4.0.0 in case performance counters are not available, correct? Alas, while much better, that version was still to slow for what we want to do. I will ask a colleague to check it out, though. 
We are currently weighing our options and consider option 3 (writing our own custom code that fits our use case, using Oshi as a template), but due to project priorities, we cannot do that right now. My current workaround is to leave memory usage measurements disabled (since most of the stuff we monitor is Java based, we can stick with JMX-based heap monitoring for now). For CPU usage, I built something using the Java process API.
In any case, once we get back to revisiting the topic, we will check out Oshi again.
THX for your help.

**Comment by dbwiddis** [comment]
The key change in #1031 is to restore the (fast) fetching of windows process information from the registry, which was removed in #1001 due to issues with internationalization.  On my machine it takes only 1-2 ms for all the processes, vs. 30-50ms for the PDH counters.

I added some checks to be sure the registry worked, and fall back to the slower PDH if available, and fall back again to even slower WMI if necessary.   This provides the best speed possible for everyone.

In addition to the process fetching, I also  wrapped the "slowFields" boolean check around the Command Line query, which uses WMI, and enabled additional command line arguments for slowFields to the single-PID and multiple-PID case.  So the performance (with that boolean set false) should be even better than what you saw when you tested 4.0.0. 

I'll go ahead and close this issue, since I think it's resolved and the speed is pretty snappy on my systems.  Feel free to re-open or post a new issue if you need more help.
