### ISSUE TITLE
Linux CPU Frequency is -1 on a VM

### ISSUE THREAD

**Issue by jfr85** [oshi/oshi#1053]
Hi,

Using the following versions:

- CentOS 7
- OpenJDK 11
- OSHI 4.2.1
- JNA 4.5.2

I get a wrong value when reading the CPU frequency: -1 Hz.
The other values seem to be correct:

jvm 1    | 20191128 16:52:19.251 CPU Vendor: GenuineIntel
jvm 1    | 20191128 16:52:19.252 CPU Model: Intel64 Family 6 Model 70 Stepping 1
jvm 1    | 20191128 16:52:19.253 CPU Sockets: 1
jvm 1    | 20191128 16:52:19.254 CPU Cores: 2
jvm 1    | 20191128 16:52:19.256 **CPU MHZ: -1 Hz**
jvm 1    | 20191128 16:52:19.260 Total System MB: 534.8 MiB / 1.8 GiB

Any ideas on how to resolve this?

**Comment by dbwiddis** [comment]
I believe -1 is the result of it fails to detect the current frequency.  Do you have somewhere on your district that the value can be obtained?  Does it require root privileges?

**Comment by jfr85** [comment]
The Java application runs with the root user and is ran inside a Parallels Linux VM.

**Comment by jfr85** [comment]
It works correctly if I run it on a "real" Linux installation (no VM).

**Comment by dbwiddis** [comment]
It may be that Parallels simply doesn’t allow access to that value. The java doc says it returns “The max frequency or -1 if unknown.” and from the VM perspective, it’s unknown.  Is there any command line you can use from your VM that gives the value you want?

**Comment by jfr85** [comment]
I switched from Hyperic SIGAR library to OSHI.
The SIGAR library worked on Linux, but not Windows (caused a JVM crash).

**Comment by dbwiddis** [comment]
SIGAR required specific drivers for each platform, which enabled more direct hardware access than OSHI has, including the CPUID opcode.  OSHI relies on reports from the Operating System, which as you see may work for bare metal Linux installation but may not work from inside a VM.  Since VM processors are somewhat virtualized anyway, I'm curious what interpretation you might get from frequency...

You haven't made clear which frequency you're seeking. Vendor Frequency should work fine as it comes from the Processor Identifier/Signature, and is a good default for the current or max frequency if the OS doesn't report it.

**Comment by jfr85** [comment]
This works fine, thank you.
