### ISSUE TITLE
java.io.NotSerializableException: oshi.software.os.OSProcess

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1058]
Hi,

I just wanted to test 4.2.1 and I got the following issue:

java.io.NotSerializableException: oshi.software.os.OSProcess

With 3.13.4 this was working fine.

Thanks and best regards,

    Jochen

**Comment by dbwiddis** [comment]
Do you need serialization?  In 4.2 we began removing `Serializable` from most classes.

**Comment by Space2Man** [comment]
Hi,

yes, we are using it to store the original OSProcess and compare it with the current one. Or is there a possibility to safely clone an OSProcess?

Thanks,

    Space

**Comment by dbwiddis** [comment]
While not imminent, it is possible that [serialization will eventually be removed](https://adtmag.com/articles/2018/05/30/java-serialization.aspx) from Java, due to [concerns with security vulnerabilities](http://cr.openjdk.java.net/~briangoetz/amber/serialization.html).

Once the `OperatingSystem` class returns an `OSProcess` it doesn't alter it or locally cache it, etc., so it is safe to hold onto that object.  Should you need to serialize it, you might consider [Jackson's ObjectMapper](https://www.baeldung.com/jackson-object-mapper-tutorial).

**Comment by Space2Man** [comment]
Yes, I can just copy it and create a new OSProcess[] for the current run and the historic values remain the same. So this can be closed.
