### ISSUE TITLE
LinuxOperatingSystem#getProcess can cause a jvm crash

### ISSUE THREAD

**Issue by lkolisko** [oshi/oshi#1081]
Invocation of `oshi.software.os.linux.LinuxOperatingSystem.getProcess` might cause crash of a jvm. 

```
private OSProcess getProcess(int pid, boolean slowFields) {
        String path = "";
        Pointer buf = new Memory(1024);
        int size = Libc.INSTANCE.readlink(String.format("/proc/%d/exe", pid), buf, 1023);
        if (size > 0) {
            String tmp = buf.getString(0);
            path = tmp.substring(0, tmp.length() < size ? tmp.length() : size);
        }
     ....
```
The buf is allocated through malloc and therefore is not guarateed to be zero-filled. The readlink does not append a null byte to the buf to mark the end of the string. Therefore `buf.getString(0)` might fail in `com.sun.jna.Native.getStringBytes`. In most cases the call will succeeed because there is at least one 0 present in the buffer and the string is trucated to the correct length.

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

When reading the path of a process in Linux, OSHI reads up to 1023 characters in a buffer of 1024.  However, the last character is not guaranteed to be null, which could attempt to access memory unowned by the program.   Clear (zero) the buffer prior to this call in order to ensure the correct operation of the null terminator.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- In the [`LinuxOperatingSystem`](https://github.com/oshi/oshi/blob/556bd9ece6c748fe5ebbe1ce55b09b1ffde1fb7e/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L240) class, change the type of `buf` on line 240 to `Memory`, and add a line immediately following that line that calls [`buf.clear();`](https://java-native-access.github.io/jna/4.2.0/com/sun/jna/Memory.html#clear--).
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by lkolisko** [comment]
Thank you for reviewing and confirming the issue. Another way to fix the issue might be adding a 0 terminator at the end of the string in the buf. The string should be then parsed correctly and no truncation should be AFAICT required.

```
if (size > 0) {
   buf.setByte(size, 0);
   path = buf.getString(0);
}
```

**Comment by dbwiddis** [comment]
I agree that `buf.setByte(size, 0);` would also work, and maybe be a few nanoseconds faster. :)

**Comment by dbwiddis** [comment]
If nobody picks this up by midday tomorrow, I'll knock it out (on both 4.X and 3.X branches)

**Comment by matthiasblaesing** [comment]
If you need a cleared memory block, don't reinvent the wheel, use `com.sun.jna.Memory.clear()`.

**Comment by dbwiddis** [comment]
Well, the final substring step does eliminate any "garbage" but on revisiting this I see that any nanoseconds of savings one gets from setting a single byte rather than clearing is lost in the extra (garbage) string manipulation with an extra String generated for no good reason.

**Comment by dbwiddis** [comment]
And revisiting my fix, I didn't do either of the above. I just read `size` bytes into a bytebuffer and turned it into a String.... and later (thanks to your mailing list suggestion) threw out the whole thing and replaced it with `Files.readSymbolicLink()`.

**Comment by matthiasblaesing** [comment]
Yeah - NIO indeed already solves that problem :-)
