### ISSUE TITLE
Missing volume label in Windows

### ISSUE THREAD

**Issue by GenghisChen** [oshi/oshi#1130]
Hello

When querying drives on a Windows machine, the volume labels are not retrieved.
Specifically, when calling WindowsFileSystem.getFileStores() labels on local volumes are correctly (though confusingly, as they are paired with the drive letter) retrieved by getLocalVolumes(); but then they are overridden by information coming from getWmiVolumes(), that omits the label.
Unsurprisingly, labels on volumes that only come from WMI are not retrieved as well.

OSHI 4.4.2
Windows 10.0.18363
Let me know if more information is needed
Thanks
Chen

**Comment by dbwiddis** [comment]
Hmm... I don't think we ever provided the volume label.  Would be trivial to add the `VolumeName` field to the existing WMI query (For some reason we're using `ProviderName`?) and attach it to an OS FileStore field.  Or it might just be we need to change `ProviderName` to `VolumeName`.

**Comment by dbwiddis** [comment]
OK, so we have to be careful with terminology here.  For a while I thought the "volume" was the label, but it's not the case...
- The existing "getVolume()" returns the volume name.  The code was ported [from here](https://docs.microsoft.com/en-us/windows/win32/fileio/displaying-volume-paths).  These names are the GUID strings (`\\?\{GUID}]`).
- The volume name is used to look up other info including the drive name, which is what you might associate with the label, is paired with the drive letter and given as the name.
- WMI has a more verbose "name" which we replace the above with for non-network drives.  We also re-populate the volume GUID (for local) or provider path (for network)

Essentially we (I) made the choice to have a more verbose name, e.g., instead of "Windows (C:)" I chose to prefer "Local Fixed Disk (C:)".

One possible way to handle this is to add a new "label" field to the `OSFileStore` and offer a `getLabel()` (or `getVolumeLabel()`) option.  For Windows, we could just use the `VolumeName` field in the `Win32_LogicalDisk` table that we are already querying; for other operating systems we could just duplicate the name field.  Do you have any other / better suggestion?

**Comment by GenghisChen** [comment]
I agree with not changing the behavior of getVolume()
getVolumeLabel() sounds about right

**Comment by dbwiddis** [comment]
Proposed update in #1132.  I've updated SNAPSHOT with these changes.  Can you test and see if it addresses your requirement?

**Comment by dbwiddis** [comment]
FYI, tests fine on my Win10 desktop.  Interestingly I have a field "logicalVolume" that is blank and I'm not sure what should go there.  I wonder if maybe that should have been the label....

```
JSON for FS:
{
  "openFileDescriptors" : 97385,
  "maxFileDescriptors" : 16711680,
  "fileStores" : [ {
    "name" : "Local Fixed Disk (C:)",
    "volume" : "\\\\?\\Volume{b3630343-4ba6-49e3-aee7-b2316967c61a}\\",
    "label" : "Windows",
    "logicalVolume" : "",
    "mount" : "C:\\",
    "description" : "Fixed drive",
    "options" : "rw,reparse,sparse,trans,journaled,quota,casess,oids,casepn,efs,streams,unicode,acls,fcomp",
    "uuid" : "b3630343-4ba6-49e3-aee7-b2316967c61a",
    "freeSpace" : 374154596352,
    "usableSpace" : 374154596352,
    "totalSpace" : 511141998592,
    "freeInodes" : 0,
    "totalInodes" : 0,
    "type" : "NTFS"
  }, {
    "name" : "Local Fixed Disk (D:)",
    "volume" : "\\\\?\\Volume{5bdbe71c-4c58-4033-9dc0-f9c8114ad5db}\\",
    "label" : "DATADRIVE1",
    "logicalVolume" : "",
    "mount" : "D:\\",
    "description" : "Fixed drive",
    "options" : "rw,reparse,sparse,trans,journaled,quota,casess,oids,casepn,efs,streams,unicode,acls,fcomp",
    "uuid" : "5bdbe71c-4c58-4033-9dc0-f9c8114ad5db",
    "freeSpace" : 1023934894080,
    "usableSpace" : 1023934894080,
    "totalSpace" : 1024073920512,
    "freeInodes" : 0,
    "totalInodes" : 0,
    "type" : "NTFS"
  }, {
    "name" : "Local Fixed Disk (E:)",
    "volume" : "\\\\?\\Volume{e433eb74-e774-419f-aa77-e703a3a7504e}\\",
    "label" : "DATADRIVE2",
  } ]
}

```

**Comment by dbwiddis** [comment]
Hmm, so the logical volume seems to be a *nix-only thing.  I wonder if instead of adding a new label field, we could just use that existing field on Windows.

**Comment by GenghisChen** [comment]
The fix is working fine on my Windows.
I'm not familiar with Logical Volumes on *nix, is there commonality between what Logical-Volume means on *nix and what Label means on Windows?
It might not be clear to users that a method named getLogicalVolume() should be called to retrieve the Label

**Comment by dbwiddis** [comment]
Yeah, probably best to leave them separate.  If you are good with this change I’ll merge it.
