### ISSUE TITLE
OSProcess windows

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1217]
hi, i'm started migrating to oshi from sigar api. currently, i'm on processes module.
sigar data:
"PTime":"Apr21",
"ShMem":"-",
"User":"NETWORK SERVICE",
"Mem":"45M",
"State":"R",
"CTime":"0:43",
"ProcName":"C:\\Windows\\system32\\svchost.exe",
"PID":"764

oshi data:
"path":"C:\\Windows\\System32\\svchost.exe",
"Mem":"5337088",
"Uptime":"1888447528",
"userTIme":"20312",
"State":"RUNNING",
"ProcName":"svchost",
"PID":"764",
"startTime":"1587480849207"

Do you have idea how to get the value of following data(PTime, CTime, and ShMem) from oshi?
I encountering Null pointer exception when getting the user from OSprocess. 
java.lang.NullPointerException
at oshi.software.os.windows.WindowsOSProcess.getUser(WindowsOSProcess.java:140)

Here's my code:
SystemInfo systemInfo = new SystemInfo();
HardwareAbstractionLayer hardwareLayer = systemInfo.getHardware();
CentralProcessor centralProcessor = hardwareLayer.getProcessor();
OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
List<OSProcess> osProcesses = operatingSystem.getProcesses();
for (OSProcess osProcess : osProcesses) {
if (osProcess == null) continue;
System.out.println("user = " + osProcess.getUser());
}

I need to get the user value of os processes.

**Comment by dbwiddis** [comment]
OK, two things.  The NPE is a bug where on line 330 I forgot to include the word `return` in the existing null check.  You'd still get "unknown" for the user info in that case, probably if you're not running with elevated permissions and trying to get info about a process you don't own.

Secondly, I'm not sure what those Sigar fields translate to, and you've only given a subset of OSHI's info so I can't try to correlate from your output.  

What are PTime and CTime?   OSHI provides user time and kernel time, which is active CPU use, as well as start time (milliseconds since 1970 epoch) and up time.  Some combination of those probably gives you the PTime and CTime although the units may be different.

What is ShMem?  OSHI's Resident Set Size output is the most commonly used measure for windows memory (matches task manager) as the "Private working set".  The raw number is returned in pages, and it's possible that in the refactoring I dropped the multiplication by page size, so I'll fix that.

**Comment by dbwiddis** [comment]
Looks like the "ShMem" might not implemented implemented on Windows, and may be a field from other OS's.  SIGAR source code reports the same virtual and resident set size as OSHI, but you haven't asked about them.
```
    procmem->size     = pinfo->size;     /* "Virtual Bytes" */
    procmem->resident = pinfo->resident; /* "Working Set" */
    procmem->share    = SIGAR_FIELD_NOTIMPL;
```

Looking at SIGAR's user and group implementation, they use `GetTokenInformation` which might be an improvement over the current way I'm doing it, both in access rights and performance.  I'll have to test that out.

**Comment by dbwiddis** [comment]
OK... PTime of "Apr21" was apparently the process start time.  OSHI reported an uptime of 1888447528 milliseconds, which converts (divide by 86,400,000) to 21.8 days ago.   Or better yet just convert the start time 1587480849207 using your favorite `java.time` methods.
```
System.out.println(Instant.ofEpochMilli(1587480849207L).atZone(ZoneId.systemDefault()).toLocalDateTime());
--> 2020-04-21T07:54:09.207
```

CTime of 0:43 is probably 43 seconds.  You showed OSHI's user time of 20,312 milliseconds but not the kernel/system time which was probably about 23,000 milliseconds, give or take.

**Comment by dbwiddis** [comment]
OK just committed a fix to the NPE.  Verified the other values should match including the memory.

Under the hood, the AdvapiUtil code OSHI uses matches Sigar for users, but the groups code only fetches the primary group not the whole group list.  This should significantly improve performance but will require me to extend the JNA class, so I'll work that up as a separate PR.

**Comment by dbwiddis** [comment]
Nice. PrimaryGroup takes 0.3 seconds per process compared to 47 seconds for all groups, at least on this machine... :)

**Comment by Space2Man** [comment]
Just some performance numbers  from one of our machines ...

getProcesses(0, null) took ~450ms previously (on 5.0.1) and now we are at ~150ms on average.

So good job!
