### ISSUE TITLE
Get the cpu usage by the name of the process

### ISSUE THREAD

**Issue by ymikorcmy** [oshi/oshi#1328]
Hi @dbwiddis, hope you are doing great.
I recently want to switch from Sigar to Oshi, but I have a question, hope it's quick. 

So in Sigar I can do for example, 
ProcCpu cpu = sigar.getProcCpu("Exe.Name.ct=SampleApp")
Is it possible to do that in Oshi? (I know we can get process by pid though)
Thank you very much for help.

**Comment by dbwiddis** [comment]
The `OperatingSystem` class has a `getProcesses()` method which returns a List of `OSProcess` objects.  The [`OSProcess`](https://oshi.github.io/oshi/apidocs/oshi/software/os/OSProcess.html) class has several getters including:
 - `getName()` which you can use to try to correlate with a running program, if you don't have the PID
 - `getUpTime()`, `getUserTime()`, and `getKernelTime()` which you can use to calculate cumulative CPU usage in User or Kernel mode separately, or `getProcessCpuLoadCumulative()` which does the calculation for you.

In addition, there is a `getProcessCpuLoadBetweenTicks()` method that takes an `OSProcess` argument.  You can pass it the OSProcess object you fetched from a previous `getProcesses()` call and it will calculate the CPU load based on the delta of up time and usage times (defaulting to the cumulative calculation otherwise).

I'm not sure exactly what Sigar returned for that calculation, but OSHI should provide at least as much detail here.

**Comment by dbwiddis** [comment]
The [`ProcessPanel`](https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java) class in the `oshi-demo` project is a pretty good example of showing how to do the CPU calculations.

**Comment by ymikorcmy** [comment]
Thank you very much for your fast response. I wanna monitor the cpu usage for a process but I don't have its PID. So I guess I will need to correlate with a program that can return PID with name given.

**Comment by dbwiddis** [comment]
You can just iterate the list of processes and filter for a match. It's a one-liner in a stream. 

`Optional<OSProcess> proc = os.getProcesses().stream().filter(p -> p.getName().equals("ExampleProcess:).findFirst();`

**Comment by ymikorcmy** [comment]
That's super helpful. Thanks a lot! :)
