### ISSUE TITLE
Resulting List<NetworkIF> does not include loopback and virtual interfaces

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1345]
Is there a reason to ignore the loopback and virtual interfaces when calling `getNetworkIFs()`?

Based on https://github.com/oshi/oshi/blame/master/oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java#L137 - this seems to be intentionally done. Why is that? Is there a way to configure oshi to include these?

**Comment by dbwiddis** [comment]
As you can see ignoring them is hardcoded there is not "currently" a way to include them, but I'd welcome a PR to make that filtering configurable.   Probably could do the same thing for the types of filesystems which are ignored as well.

As for the "why"?  Probably trying to suppress noise, and because nobody has asked for it until now.
