### ISSUE TITLE
Return list of TCP and UDP connections

### ISSUE THREAD

**Issue by kmagsuciitrs** [oshi/oshi#1422]
Hi,

I see that OSHI supports retrieval of tcp and udp stats. Is it also possible to retrieve the list of tcp and udp connections and their details, ex:
- local address and port
- remote address and port
- socket type (tcp or udp)
- state
- send queue, receive queue

If not, are there plans to add this functionality and provide an interface to get a list of tcp/udp connections?

I am currently looking for a solution/library to get these information in both Windows and Linux platforms. In Linux, tcp and udp connection details can be read from /proc/net/tcp and /proc/net/udp files. However, in Windows, I do not know if there are any helper APIs/libraries that can be used to get the connection details. I am trying to look for solutions that interface with native APIs or files, and not use an external command like netstat as much as possible, as I may be working with systems where the netstat command is not available.

Any input on this would be appreciated. Thanks.

**Comment by dbwiddis** [comment]
This sounds like a good feature.  I haven't added it primarily because I was unsure of its usefulness, plus my initial explorations into collecting the data showed it was very slow.   Plus, I am not really a networking expert, so I don't know why some data is important (why are TCP and UDP so much more requested than, say IPSec).  So this is really one of those things I need the community to drive if they want it.

I would absolutely love if you (or anyone) could put together a PR for this, even if it's just one or two OS's.  

As you mention, `netstat` provides most of the information and is a reasonable default (abstract class method that can be overridden with better native choices).

Sounds like you've got a handle on Linux.

Windows API has [GetTcpTable()](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-gettcptable) which returns a collection of [`MIB_TCPROW`](https://docs.microsoft.com/en-us/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_lh) structures containing the local/remote addresses and port and state.  Similarly [GetUdbTable()](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getudptable) returns a collection of [MIB_UDPROW](https://docs.microsoft.com/en-us/windows/win32/api/udpmib/ns-udpmib-mib_udprow) structures with the local address and port.    I haven't yet tracked down send and receive queue info (and am not sure where to even look!).

**Comment by kmagsuciitrs** [comment]
Thanks for feedback, and for inputs on where to look in Windows for these information. It seems the send and receive queue info may not be readily available in Windows, as even netstat does not provide them in Windows.

Kudos on the great work creating and updating OSHI!

**Comment by dbwiddis** [comment]
Hey, I'm just carrying on a great project started by someone else.  Would love more people pitching in!  Let me know if you (or anyone who sees this later and wants to help) needs any assistance putting together a PR.

**Comment by dbwiddis** [comment]
FYI, I got started with a default implementation using `netstat`, on my branch here: https://github.com/dbwiddis/oshi/tree/netstat 

But it's likely not that easy. A big problem with a `netstat` approach is that IPv6 addresses are truncated in the output, so it's definitely better to use native code wherever possible.  
 - Windows API sources are noted above, but it's impossible to get the queue info.
 -  Linux is the easiest, parsing `/proc/net`, which also includes the command/process with the connection open, probably useful to add
 - macOS (and FreeBSD also?) looks like it may have a `sysctl` call based on [this source code](https://opensource.apple.com/source/network_cmds/network_cmds-77/netstat.tproj/inet.c.auto.html).  Parsing `lsof -i 4tcp` (and 6- and -udp) gives the full address but is slow.  `lsof` source code may give ideas on how to do it better (possibly standard across Unix).

Not expecting to do much more on this in the near future, though.

**Comment by dbwiddis** [comment]
Well, shortly after saying I'd put it off, I figured out how to get the info in macOS and that port's done.  I'll probably work on the Windows and Linux ones this week.

**Comment by dbwiddis** [comment]
Windows now done, along with macOS as reported earlier.  Looking at Linux, `/proc/net` seems deprecated and the official replacement is much more complicated.   @kmagsuciitrs have you done a Linux implementation elsewhere?

**Comment by dbwiddis** [comment]
The linux code should probably port [this](https://github.com/kristrev/inet-diag-example/blob/master/inet_monitor.c), documented [here](http://kristrev.github.io/2013/07/26/passive-monitoring-of-sockets-on-linux).
