### ISSUE TITLE
Prevent github actions from running on forks

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1429]
The current github actions setup runs on user forks (e.g., for me, `git pull upstream master` and `git push origin master` results in an execution on the `dbwiddis/oshi` fork.

We should restrict github actions to only execute on `oshi/oshi`.

**Comment by hazendaz** [comment]
For CI?  Generally that always runs on forks including when on travis.  That is sort of expected.  Its blocked on things like sonar.  See the yaml file on there for how that is blocked.  CI though should be for all as that should be natural testing unless the fork blocks it but that is counted if I'm not mistaken against their fork not against the main one.  Each person can configure how they might want that.

**Comment by dbwiddis** [comment]
Travis only runs on PRs, so it was a surprise to me to push to my fork's master branch and see a CI report.   I guess as long as it doesn't run on branches on forks, it's tolerable.   It just seems not quite right to run quota-limited actions on a user's account without asking them, even if they are able to override it later.

**Comment by dbwiddis** [comment]
I think this may be what I'm looking for:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#allowing-specific-actions-to-run
> **Allow specified actions:** You can restrict workflows to use actions in specific organizations and repositories.
>
> You can use the * wildcard character to match patterns. For example, to allow all actions in organizations that start with space-org, you can specify space-org*/*.

**Comment by dbwiddis** [comment]
Looking at the configuration, it seems it might be appropriate to run:
 - on push to `master` branch
 - on pull requests

But not on pushes to other branches.   In general, forks/PRs should be from a non-`master` branch anyway.

**Comment by hazendaz** [comment]
So travis will run on everything if you sign up for it per project.  I have on nearly all my forks.  I as a normal course of action generally will determine things work before I even raise a pull request so repos are not polluted with false starts.

Since this is integrated, I think it becomes different in your case (and others) as you didn't do the same with travis builds.  Not an issue though at this repo level.  If you go to your fork, look there, you can setup your actions to do nothing on dbwiddis/oshi.

What happens directly on a fork though is not part of oshi/oshi in any counts.  Those would be specific to the owning account which isn't oshi in that case.  I wouldn't bother trying to figure out how to control forks.  Maybe just a note that if they want this turned off on CI builds how to expressly do that?  That is super easy to achieve what you are noting.

**Comment by hazendaz** [comment]
As a note, we have had this turned on for mybatis/mybatis-3 on CI builds for some time now and no one has mentioned anything there.  That repo has such a larger user base that it might pop up of note there but hasn't.  Someone donated the intial setup a few months back and it has been silently running since.

**Comment by dbwiddis** [comment]
Sounds good. I'll go ahead and close this issue.  But I would like the "push to master branch" and "pull request" selections for the "on:" field.  I can try to configure that if you don't.
