### ISSUE TITLE
Thread names are returned as `""` for linux

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1458]
For a docker image based on CentOS 7, linux thread names are all returned as `""`.

Oshi code also does not seem to have an implementation for linux thread names - is this expected? (i.e. are there issues in implementing this for linux?)

**Comment by dbwiddis** [comment]
Linux "thread names" are simply the name of the owning process followed by a 0-indexed number. However, that number changes as threads are started and stops, so it does not represent a unique thread name.  If you wish for your app to re-create the "temporary" thread name that you would see in `/proc` you can construct it yourself based on the process name and iteration order.

However, I cannot, given only an `OSThread`, know where in the process's list of threads it will be, so the "name" is not a property/attribute of the thread itself.  

@tausiflife I think you worked on this feature, do you have any more insight here?

**Comment by dbwiddis** [comment]
OK, looking more into this.  Threads inherit their parents' name by default, but it's possible programmatically to change the name of a thread.  For example, `rsyslogd` has multiple threads:
```
$ cat /proc/732/task/732/comm
rsyslogd
$ cat /proc/732/task/772/comm
in:imuxsock
$ cat /proc/732/task/773/comm
in:imklog
$ cat /proc/732/task/774/comm
```
So we should populate the name field from the contents of `comm`.  

Easy fix if someone else wants to do it today or tomorrow, otherwise I'll do it Sunday before cutting the next release.
