### ISSUE TITLE
"Operating system not supported: 5" on OpenBSD

### ISSUE THREAD

**Issue by mprins** [oshi/oshi#1465]
This "5" isn't a very helpful indication for "UNKNOWN"; I think that could be changed to just "Operating system not supported"

#6 and #7 talk about adding OpenBSD but that never happend I guess.

Having 2 BSD variants already I think it shouldn't be too hard to add OpenBSD (at least the most common hardware platforms (i386 and amd64) (I only have amd64 atm)

**Comment by dbwiddis** [comment]
> This "5" isn't a very helpful indication for "UNKNOWN"; I think that could be changed to just "Operating system not supported"

Actually, it is helpful as an error code. It corresponds to [the OPENBSD constant in JNA's `Platform` class](http://java-native-access.github.io/jna/5.6.0/javadoc/constant-values.html#com.sun.jna.Platform.OPENBSD).  If anything I'd implement all the constants in the existing enum to provide the remaining unsupported OS's, to give a string representation in the error message, rather than the integer.

> #6 and #7 talk about adding OpenBSD but that never happend I guess.

Indeed, and at the time there was a bare minimum of information in the API.   [An earlier version of the FAQ included this comment](https://github.com/oshi/oshi/blob/d71de9adef4a2a40e12edc1e8951c999eddd58dd/FAQ.md#will-you-do-a-port-for-the-other-bsds--how-about-android):
> **Will you do a port for the other BSDs? How about Android?**
>
> Unlikely without bribes such as a lifetime supply of coffee. But happy to advise someone else who wants to do so!

I removed that eventually as it wasn't really "frequently" asked. In fact, you're the first person to ask about it since 2014.  

That said, the general attitude is still about the same. I'm happy to work together with someone to add it, but the odds of me doing it solo (for free) are rather slim, at least in the near future.  It looks like OpenBSD currently has about 0.0015% usage share of webservers, so I'm not sure that the effort to implement and maintain the port is worth it if nobody is even using it!  

Let me know if you want to collaborate on this.  Community involvement in developing and maintaining the port can convince me of its value.

> Having 2 BSD variants already I think it shouldn't be too hard to add OpenBSD (at least the most common hardware platforms (i386 and amd64) (I only have amd64 atm)

I would hope that there's more overlap with FreeBSD than macOS had.

**Comment by mprins** [comment]
I've started a PR to implement the basics, I'm primarily interested in getting GeoServer working on OpenBSD (with the systeminfo page), so far I've not gotten the JNA working, not sure that's needed for the basics

see also https://osgeo-org.atlassian.net/browse/GEOS-9851

**Comment by dbwiddis** [comment]
Can you define what you mean by "the basics"?  I can add OpenBSD as a "supported" OS and implement a skeleton "fail gracefully with no info" return values reasonably quickly.  If I copy over all the FreeBSD code, some of it might even work. :)

**Comment by dbwiddis** [comment]
Steps for an OpenBSD port:
1. "Clone" (simple copy/paste into new directory) the `freebsd` packages into `openbsd` packages.
2. Global search/replace "FreeBsd" with "OpenBsd" in all the files copied in step 2.  (Try to preserve case.)
3. In the `oshi` package, add `OPENBSD` to the enum and as an option in the switch/case statements in the `SystemInfo` class, pointing to the new `OpenBsdHardwareAbstractionLayer` and `OpenBsdOperatingSystem` classes created in the first two steps.
4. Run SystemInfoTest and see what breaks.  Override selected methods and create a TODO list.
