### ISSUE TITLE
Support perf data on Linux

### ISSUE THREAD

**Issue by everflux** [oshi/oshi#1469]
It would be useful to be able to get linux perf data via api. (Perf tools examples: https://perf.wiki.kernel.org/index.php/Tutorial#Counting_with_perf_stat )
My use case: I would like to measure some operations in junit tests to guard against regressions with regard to i/o and especially CPU instructions used. oshi currently provides only timing data that is dependent on the actual cpu and clock rate.

**Comment by dbwiddis** [comment]
Thanks for the suggestion. This does look like an interesting tool.  I'm still very on the fence (leaning no) toward including this into OSHI, for a few reasons:
 - It's Linux-only.  Our primary purpose is as a cross-platform API, so we tend to avoid things that are only relevant to a single platform, which can usually be done better with a separate application. Perhaps [this one](https://github.com/jvm-profiling-tools/perf-map-agent)?
 - It relies on a package that is not installed by default, and which the overwhelming majority of users won't install.  
   - The trade-off here is adding a bunch of classes/enums/methods to handle everything in the API and adding to the JAR size with a feature that won't be used by the vast majority of people.  JAR size is a concern -- we don't want to be Guava.  
   - Perhaps if/when in the future OSHI is modularized and users can choose whether or not to include the "Linux perf module" this concern may be mitigated, but in its current single-JAR format, I see this as mostly bloat.
 - It looks like it's primarily command-line based.  We try to avoid command-lines when there's a native version.  
   - There does appear to be a `perf_events()` function that could be implemented, but it's not very well (or at all, officially) documented, and my brief research into the history of `perf` indicates multiple times backwards compatibility was broken, meaning it'd be very difficult to catch all different versions that users may be running. You could probably implement this yourself using JNA without trying to use OSHI as a middleman.
   - OSHI does include a utility class (`ExecutingCommand`) that allows you to run command lines and parse their results, and this may be sufficient for your needs, especially given the large number of options available.  
 - OSHI does provide IO counters and the JVM provides `System.nanoTime()` which should handle most general use cases.  For more detailed microbenchmarking, I just don't see OSHI as being the right tool for the job.

I'm open to being convinced otherwise, and am interested in the feedback of other users/maintainers.

**Comment by everflux** [comment]
Thanks a lot for looking into this! I can accept if it is not a good fit for oshi.

* I believe that oshi already provides platform dependent perf data, if I did not misunderstood the purpose of this class: http://oshi.github.io/oshi/oshi-core/jacoco/oshi.util.platform.windows/PerfCounterQuery.java.html#up-a
* afaik perf data is provided by the linux kernel, and the perf tool is just the user facing application and not required. Otherwise this is certainly a possible blocker. I was not aware that the kernel API might be that unstable as you pointed out, perhaps it is worthwhile to monitor the current state of affairs before implementing it.
* The JAR size is a valid point, too. Not much to argue as you pointed out a separate module as a possible solution in the future.

Thanks for pointing out alternative approaches! Though I think they target different use cases. What I would like to achieve is a couple of tests that are independent of the current machine / load (as much as possible, since intel/amd/arm might as well make a difference). I would like to measure the actual number of instructions used on the cpu for code execution so I am more interested in the _relative speed_. The perf agent and async profiler do not allow me to run them from inside the java code, so I can't use them in (junit) tests.
So currently I really just need the perf counter for the current process, not the kitchen sink. Perhaps this is really similar to the windows specific code I cited above. Perhaps it is a really bad fit for oshi. I any case: Thanks for the really fast feedback and taking care!

**Comment by dbwiddis** [comment]
With regard to the Windows Performance Counters (a.k.a. perfmon) -- those are on a different level entirely than the kernel-based info the `perf` command exposes.  These are higher level statistics already available in Linux via the `/proc` or `/sys` interfaces, e.g.,
 - Disk perf counter (reads/writes) has `udev` equivalent for Linux `sysfs`.
 - Memory/swap perf counters have `/proc/meminfo` and `/proc.vmstat` equivalents
 - Process and Thread perf counters echo `/proc/<pid>/stat` and the thread equivalent
 - Processor cpu counters echo `/proc/stat`

It may be these existing (`/proc`) counters plus `System.nanoTime()` is sufficient for your needs.

**Comment by dbwiddis** [comment]
Rereading your whole post, I see you want to measure "instructions."  it is possible that you can use the `perf` system command lines via OSHI's `ExecutingCommand` class (or just roll your own forked process) and parsing the output yourself for the statistics you need.  Use OSHI to grab the current process PID, for example, construct a command line for `perf stat -p <pid>` and whatever options you want, and process the returned list of Strings.

**Comment by everflux** [comment]
I see, thanks for clarification.
In fact I used `process.getUserTime()` and tried to calculate it back to _jiffies_ in order to get a relative value. While this is quite resilient to thread.sleep calls (this is what I want) it is not invariant to the current cpu performance.
I will check out the `ExecutingCommand` to wrap `perf`, it might indeed serve my immediate needs. Thanks!

**Comment by dbwiddis** [comment]
If you want raw jiffies, you can skip OSHI's intermediate processing into milliseconds and grab the original proc value for the process. `oshi.driver.linux.proc.ProcessStat` has a `getPidStats()` method encapsulating `/proc/pid/stat` output. It's convenient, with a bit of extra ovehead.  Or you can fetch the stat line yourself and do `ParseUtil.parseStringToLongArray()` with the appropriate index. which trades readability for performance.

**Comment by dbwiddis** [comment]
I'd be interested in seeing your command line version when it's done. If it's sufficiently generalizable it *might* be worth putting in a standalone Linux driver class.  Or at least serve as a template for a future implementation.

**Comment by dbwiddis** [comment]
Another idea is another artifact outside of `oshi-core`. Perhaps `oshi-perf` which implements high-performance counter info from different platforms and can thus be highly specialized without adding to main artifact bloat...

**Comment by dbwiddis** [comment]
After thinking about this for a while, I think I'm going to close this as out of scope, with the primary "excuse" being lack of good and consistent documentation to implement it natively (plus it requires users to install something to even make it work).  This particular system seems to have a good command-line API with lots of options that it'd be silly to wrap java around for a "general" case.  I hope the comments above are helpful in implementing your own system.
