### ISSUE TITLE
skipped rpool volumes

### ISSUE THREAD

**Issue by majster-kat** [oshi/oshi#1478]
Hi,

class SolarisFileSystem skips filestores whose name starts with "rpool" (see line 116).
Would it be possible to:
1. either change it to skip only filestores called rpool (i.e. replace startsWith with equals)?
2. or add add some configuration parameter that enable/disable skipping of rpool filestores?

Thanks
matej

**Comment by dbwiddis** [comment]
Yes, it certainly is possible to make display of volumes starting with `rpool` on Solaris and FreeBSD configurable.  macOS has similar for volumes starting with `map ` or equaling `devfs`. Linux could be configured to not exclude paths ending in `/shm` or equaling `/dev`.  The hardcoded `TMP_FS_PATHS` could also be configured.   We probably could do some sort of wildcard based inclusion/exclusion per OS.

**Comment by GeorgeJoLo** [comment]
Hello, @dbwiddis  you mentioned label:"PR welcome"
I'm very new in open source and don't have much  programming experience.
Is this something I could do? What may I can change in the code?

**Comment by dbwiddis** [comment]
Hi, @GeorgeJoLo so glad to see you post this! I was getting ready to draft a "first-timers-only" pitch for this!  Here's my thoughts:
 - Take a look at the existing implementation of network and pseudo filesystem types in config for context:   
   - The `oshi.properties` file in `src/main/resources` and the `oshi.network.filesystem.types` and `oshi.pseudo.filesystem.types` therein.
   - The `AbstractFileSystem` class in `oshi.software.common` which loads those configs into Lists.
   - Each of the OS-specific `<OS>FileSystem` classes which filter out using these collections using code something like this for Solaris (this issue), but similar for other Unix-based OS's (not Windows):
```
          if ((localOnly && NETWORK_FS_TYPES.contains(type)) || PSEUDO_FS_TYPES.contains(type) || path.equals("/dev")
                    || ParseUtil.filePathStartsWith(TMP_FS_PATHS, path)
                    || volume.startsWith("rpool") && !path.equals("/")) {
                continue;
            }
```
 - Create a similar set of config parameters loaded into the abstract class for exclusion and inclusion of paths and volume names by OS.  Exactly how you do this is up to you!  If you have a better idea, please suggest it.  Otherwise, here's what I was thinking:
   - Make 4 config parameters:
     - FS_PATH_INCLUDES
     - FS_PATH_EXCLUDES
     - FS_VOLUME_INCLUDES
     - FS_VOLUME_EXCLUDES
   - Each will be a comma-delimited list of OS:text pairs
     - Use the PlatformEnum constants for the OS.
     - Allow the * wildcard at the beginning (for `endsWith()`) or end (for `startsWith()`) for the text match. 
     - Replace the logic similar to the above with a single call to a method like `includeThisFileSystem(type, path, volume)` in the abstract class, in which you implement the logic once
     - Also remove the TMP_FS_PATHS in each file and incorporate into these
     - Code up logic similar to the above code snippet in the Abstract class.
     - Test and debug. Ideally write a unit test, although we can wait on that. :) 

So for example, the above logic would include in the config:
```
oshi.filesystem.path.excludes=*:/dev,*/tmp,SOLARIS:/system,SOLARIS:/dev/fd
SOLARIS:rpool
# includes override excludes
oshi.filesystem.path.includes=*:/
```
and the code might look like:
```
    protected boolean includeThisFileSystem(String type, String path, String volume) {
        if ((localOnly && NETWORK_FS_TYPES.contains(type)) || PSEUDO_FS_TYPES.contains(type) 
            || !isFileSystemIncluded(path, volume) && isFileSystemExcluded(path, volume)) {
            return false;
        }
        return true;
    }

    private boolean isFileSystemIncluded(String path, String volume) {
       // some logic to iterate the includes with wildcard prefixes/suffixes
    }

    private boolean isFileSystemExcluded(String path, String volume) {
       // some logic to iterate the excludes with wildcard prefixes/suffixes
    }
```
Again, this is just my idea, if you have a better one, feel free to try to implement.

Feel free to ask questions here, or submit a draft PR for review!

**Comment by majster-kat** [comment]
Hi @dbwiddis, thanks for your thoughts. Here are few notes

1. what about using property for each OS type instead of parsing pairs OS:text. So there would be properties:
`
oshi.os.windows.filesystem.path.excludes=
oshi.os.windows.filesystem.path.includes=
oshi.os.windows.filesystem.volume.excludes=
oshi.os.windows.filesystem.volume.includes=
# following are for any unix OS
oshi.os.unix.filesystem.path.excludes=
oshi.os.unix.filesystem.path.includes=
oshi.os.unix.filesystem.volume.excludes=
oshi.os.unix.filesystem.volume.includes=
# following are only for Solaris
oshi.os.solaris.filesystem.path.excludes=
oshi.os.solaris.filesystem.path.includes=
oshi.os.solaris.filesystem.volume.excludes=
oshi.os.solaris.filesystem.volume.includes=
# and other properties for other OS types.
`

2. for path matching could be used glob ( https://en.wikipedia.org/wiki/Glob_(programming) )

**Comment by dbwiddis** [comment]
1. It would work -- the problem with that is there are 6 supported OS's, so that's 24 different config lines.  Add 4 more for the "include always" such as for the `/` path, unless we want to duplicate that line 6 times.  Internally, it all gets separated into those 24 lists anyway, though, so it's more a question of config file readability.   

2. I'd not like to use an external commandline for parsing something we can do inside Java that can be compiled to bytecode.  You could, for example, do a one-liner regex match (and indicate the config file lists are regular expressions).  Checking the first or last character seems a lot more performant, though.

**Comment by dbwiddis** [comment]
Thinking more on 1... I still think fewer lines in the config are preferred, but if you want to implement as you have it I can always tweak it later.   But I also had a thought, following up on my comment of "24 lists anyway".  We actually would only have 4 or 8 lists on any given OS (the "all" and "OS-specific" list).  But we really only *need* 4 lists.  When the `FileSystem` class loads this config, we should read the config once into a single list for each of the 4 categories. It's ok to be a little less efficient with this read as it's one-time.  But each call that checks `isFileSystemIncluded()` should only have to look at a single list.

**Comment by dbwiddis** [comment]
One other note ... the path and volume stuff is only for the Unix-based (including macOS and Linux) OS's. Windows does not do any volume or path filtering.

**Comment by majster-kat** [comment]
1. to me having separate config property for each OS type is more easy to read/write (but it's a matter of preference). Here are examples for both types of configuration:

```
# one property per OS, unused properties are not present (for me easier to read)
oshi.os.aix.filesystem.path.excludes=/run,/sys,/proc
oshi.os.freebsd.filesystem.path.excludes=/system,/tmp,/dev/fd
oshi.os.linux.filesystem.path.excludes=/run,/sys,/proc
oshi.os.macosx.filesystem.volume.excludes=map *
oshi.os.solaris.filesystem.path.excludes=/system,/tmp,/dev/fd,/dev
oshi.os.solaris.filesystem.volume.excludes=rpool

# common property for each OS types (for me a bit more difficult to read)
oshi.filesystem.path.excludes=AIX:/run,AIX:/sys,AIX:/proc,FREEBSD:/system,FREEBSD:/tmp,FREEBSD:/dev/fd,LINUX:/run,LINUX:/sys,LINUX:/proc,SOLARIS:/system,SOLARIS:/tmp,SOLARIS:/dev/fd,SOLARIS:/dev
oshi.filesystem.volume.excludes=MACOSX:map *,SOLARIS:rpool
```

2. I meant to implement glob parsing in java. There are two options:
 a. use Java implementation: https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob
 b. or implement globToRegexp method that will created regexp pattern out of glob pattern. 
Or another option is to just use prefix/suffix matching as you suggested :)

**Comment by dbwiddis** [comment]
At first I thought "I like the one liner" until I went to edit it to fix some of yours and then I thought "several individual lines is so much more readable and maintainable when changes are needed".  :-)

So go for it with the individual lines.   A few notes:
 - I think `/dev` should probably be on every system. Probably `/tmp` as well.
 - I think the FreeBSD list is a relic of "copy and paste Solaris" and probably should be validated. Fine for now though, later chang eis an easy config file edit.
 - You missed the linux `*/shm`

**Comment by dbwiddis** [comment]
Regarding the second question about glob...  I'd forgotten that was part of Java!  In fact, I think using [`PathMatcher`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher%28java.lang.String%29) is a great idea as we would only need a single list/config that could handle both paths *and* volumes.  And it's actually built for precisely the purpose we intend to use it for.  And it probably matches the under-the-hood include and exclude stuff in most Maven plugins.

So yes, please implement glob (probably with `PathMatcher`) and see if you can combine to a single exclude list per OS.  You may want to instantiate the patterns outside a loop before applying them, but otherwise I don't see a big performance hit.

**Comment by mprins** [comment]
a 3rd option for the property files is to have a "primary" props bundle (oshi.properties) that has all the keys and OS specific ones (eg. oshi.macos.properties) that only have overrides for that platform, as an example (which uses a ".local" as an override:
https://github.com/B3Partners/brmo/blob/832a00afe6ecbaf4a85be7f6b51103e716ded333/brmo-loader/src/test/java/nl/b3p/AbstractDatabaseIntegrationTest.java#L70-L83

**Comment by dbwiddis** [comment]
I like the idea of defaults and overrides.  But I'm a bit iffy on having multiple config files, particularly for behavior we expect the user to change (vs. "static" things like OS name mappings).  Also, while we could do it going forward, moving some of the existing configs to platform-only files would probably break compatibility.   I think an entire re-write of how we do configs is probably a good idea for the next major version change.

**Comment by majster-kat** [comment]
I have created p

**Comment by majster-kat** [comment]
I have created pull request https://github.com/oshi/oshi/pull/1482
