### ISSUE TITLE
Bytes written on disc and bytes read from disc is always 0 in solaris.

### ISSUE THREAD

**Issue by SatyamMishra245** [oshi/oshi#1480]
getBytesWritten() and getBytesRead() in SolarisOSProcess.java in Oshi-core-5.3.7 
do not have implementations.
These two methods return 0 always.

**Comment by dbwiddis** [comment]
These statistics "do not have implementations" on Solaris because they are not available in the user-accessible `ps` command like they are on other Unix-like operating systems.  [The `psinfo_t` structure](https://docs.oracle.com/cd/E19253-01/817-6223/chp-proc-psinfo/index.html), where `ps` gets its info (and exposed with root permissions in the `/proc/pid/psinfo` path) does not have these values.

Do you have another source for this information?

**Comment by dbwiddis** [comment]
(Retracing my research steps from a few years ago) The best guess for this information is the `prusage` structure exposed (for root) in `/proc/pid/usage`. There are fields `pr_ioch` (bytes read *and* written), `pr_inblk` and `pr_outblk` (supposed to be 8KB blocks).  However, these do not appear to work.  [See this paper](http://www.brendangregg.com/Solaris/paper_diskubyp1.pdf).  The author runs actual tests that show these counters display all process I/O but not necessarily to the disk (e.g., counters increase for sending data to `/dev/null`).   The 45-page pdf concludes disk IO is best measured using `iosnoop` or `iotop` which use `dtrace` under the hood, but are resource intensive monitoring apps and do not present cumulative statistics like in other OS's.

So I'm convinced this information is not really accessible, unless you know otherwise.
