### ISSUE TITLE
Java modularity support / jlink support

### ISSUE THREAD

**Issue by all-creator** [oshi/oshi#1500]
Could you add the module-info file to the oshi-core directory or is this not possible in this context? Java modularity is required for jlink builds. If this is not possible could you write a raw module-info file and provide it here.

**Comment by dbwiddis** [comment]
> Could you  ...

I have very little experience with JPMS, have spent far too many hours trying and failing to do simple changes, and would prefer an experienced member of the community do this.  A PR that doesn't break the build/test/release process is welcome. 

Some notes:
 - OSHI depends on JNA, which does not yet have this capability either. It is an experimental feature which will be enabled in version 5.7.0.  See https://github.com/java-native-access/jna/pull/1237   Of note, they publish separate jars with `-jpms` appended to them, and I think I'd prefer doing that with OSHI (e.g., `oshi-core-jpms`) as well.
 - When I've experimented with this in the past, I've experienced problems trying to keep JDK8 compatibility (which we will target for a very long time) but also allow building on JDK9+ without breaking things, usually due to Maven plugins not yet understanding whether we're modular or not.  The current version of the javadoc plugin, for example, breaks just with the automatic module name when trying to publish a shaded JAR for use with OSGi modules.   OSGi and JPMS modules don't play nice with each other, as they essentially seek to do opposite things.  This is another argument for a separate `-jpms` artifact.

As for writing the raw module-info, I recommend you take a look at the [ModiTect](https://github.com/moditect/moditect) Maven plugin.  You can use it to generate the module-info file yourself and/or add that file to OSHI during the build process.

**Comment by all-creator** [comment]
Yes, you are right, a separate artifact would not be a bad decision. I've seen this plugin, but unfortunately I'm also not good at JPMS. And also I do not quite understand the architecture of the project and all my attempts to write modul-info ended in failure. Contacting you was my last attempt. If anyone provides a working ModiTect POM-Code starting with the <plugin> ... </plugin> tag for your project, I would be very grateful

**Comment by dbwiddis** [comment]
It looks like [this commit at Jackson](https://github.com/FasterXML/jackson-core/pull/527/files) is a decent example of how to do it with JDK8 compatibility, copying from a file.  I have not tried this. use at your own risk.

One can generate a full module-info.java file in an IDE that lists every package.  Removing anything under "Jna", "common" and "platform" packages should suffice to trim down most of the internal stuff.  If you don't need anything in the drivers or custom utils those can go too, so a minimal one would be:
```
module com.github.oshi {
    exports oshi;
    exports oshi.hardware;
    exports oshi.software.os;
    exports oshi.util;

    requires com.sun.jna;
    requires com.sun.jna.platform;
    requires java.desktop;
    requires org.slf4j;
}
```
Disclaimer:  this probably doesn't work, but should be at least minimally helpful.  Use at your own risk.  Probably requires building another module-info for JNA or copying relevant code from the above-linked PR.

Once JNA 5.7.0 has been released I may consider putting more effort into this, but until then, you (or anyone wanting to use jlink) will need to figure out moditect or other workarounds.

See also [this thread on the jna-users mailing list](https://groups.google.com/g/jna-users/c/c7__3PprLm8/m/e4mQsoyfAAAJ).

**Comment by dbwiddis** [comment]
See also [this Stack Overflow answer](https://stackoverflow.com/questions/47727869/creating-module-info-for-automatic-modules-with-jdeps-in-java-9/47728002#47728002) which indicates `jdeps` can generate the appropriate module-info for you to use with `jlink` manually, while you wait on OSHI (and JNA) to do what Jackson did in the link above.

**Comment by dbwiddis** [comment]
I just released a new Maven artifact `oshi-core-java11` that I *hope* will work in a modular build.  I may, in the future, make other improvements leveraging java11 code (e.g., `ProcessHandle` class).
```
<dependency>
  <groupId>com.github.oshi</groupId>
  <artifactId>oshi-core-java11</artifactId>
  <version>5.5.0-beta-1</version>
</dependency>
```
The beta is in the version for a reason.  Please do not use this in production yet.    Please do test this and let me know if changes are needed.
