### ISSUE TITLE
DiskStore#getTransferTime returns incorrect Values in Windows

### ISSUE THREAD

**Issue by TheGoesen** [oshi/oshi#1504]
Hello,

Using the Code below 

```
import oshi.SystemInfo;

   public class Demo {
    public static void main(String[] args) throws InterruptedException {
        long time;
        do {
            time = getTime();
            Thread.sleep(5000);
        } while (time <= getTime());
    }

    private static long getTime() {
        final var next = new SystemInfo().getHardware().getDiskStores().iterator().next();
        System.out.println("next = " + next.getName());
        final var transferTime = next.getTransferTime();
        System.out.println("transferTime = " + transferTime);
        return transferTime;
    }
}
```

gives me this result

```
next = \\.\PHYSICALDRIVE0
transferTime = 1611303212783
next = \\.\PHYSICALDRIVE0
transferTime = 1611303212739

-> exit
```

given that the docs state 

> The time spent reading or writing, in milliseconds.

this would mean my disk already spent >51 years of reading and writing and it is also going back in time, so i am not sure about that...

**Comment by dbwiddis** [comment]
> my disk already spent >51 years of reading and writing and it is also going back in time

You may have accidentally installed a Stargate drive rather than a Seagate one.

![image](https://user-images.githubusercontent.com/9291703/105524203-2b853f00-5c94-11eb-806c-fa220eefa071.png)

But seriously, that timestamp points to the Unix epoch, so I suspect I may be misinterpreting the meaning of the counter, and the going back in time could be attributable to roundoff that I can probably avoid.

**Comment by dbwiddis** [comment]
Well, I at least know why it's giving the results it's getting.
 - The PhysicalDisk performance counter OSHI uses is "% idle time" which will be close to the current time in 100-nanosecond ticks since the epoch
 - The timestamp stored is from Java's `currentTimeMillis()` since the epoch which isn't synchronized with the performance counter clock, leading to the backwards time travel based on differing processing times in the loop
 - OSHI calculates the value of the counter as the timestamp minus idle time value; if that idle time is 0 (or very small) we get the very large values indicated.  I think we're seeing these small values which conflict with the WMI documentation, but I've seen them before in other counters and we should error-check for them.  Or see if another counter other than "idle" time is better to use here.

**Comment by TheGoesen** [comment]
I did a bit of research and it seems that if one uses % idleTime, u should also use  uint64 PercentIdleTime_Base. (?)
https://stackoverflow.com/questions/58712142/what-are-base-properties-in-powershell-and-how-do-i-use-them 
that seems like smart people saying stuff, i dont know...

**Comment by dbwiddis** [comment]
The _Base counters are all the same and are elapsed 100-nanosecond ticks since the Windows epoch (1600-01-01), see also the `FILETIME` class.  One definite fix we should put in is to use those counters as timestamps.

I'm not sure why I used %Idle rather than %Disk, but I think it has to do with Windows 7 compatibility. On Windows 10, the %Disk raw counter elapsed time (100-ns) exactly matches the "Transfer time per sec" raw counter, so that's clearly the value we want.   Spinning up my Win7 VM to see if there's a reason I didn't use those there.

**Comment by dbwiddis** [comment]
OK, I got in my time machine (see original report) and looked back at issue #1061 and PR #1063 where we (Hi @Space2Man!) decided on 1-Idle% in preference to % disk time (to fix a longstanding bug... this statistic has been problematic for a long time!) The linked website is broken but here it is [on the wayback machine](http://web.archive.org/web/20200421151718/http://support.demandtech.com/index.php?pg=kb.page&id=47).  TLDR: the %DiskTime value includes queue time, and thus slightly overestimates the transfer time.  

The WMI classes permit an accurate calculation: 
 - AvgDiskSecPerTransfer is the counter we want based on description.  The calculation divides the delta of that counter by the delta of the _Base equivalent, which is the total number of transfers, indicating that the elapsed time of that counter measures what we want.
   - However, there's no obvious "time base" for this counter. On my Win7 machine it was negative!  So as a standalone number it's useless.
 - PercentDiskTime isn't as obviously the same counter based on the description, but the elapsed time of that counter exactly matches the AvgDiskSecPerTransfer elapsed difference.  So for our purposes it's equally valid (subject to above caveat re: the queue).
   - The value is exactly the sum of PercentDiskReadTime and PercentDiskWriteTime.
   - The value is referenced to Timestamp_Perftime, which appears to be time since latest reboot.  Subtracting The PercentIdleTime from Timestamp_Perftime gives a slightly smaller value that, according to the above link, is more accurate.  So this is really the value we want (converting from 100-ns to ms by dividing by 10000.)
   - The various Percent<foo>Time_Base counters exactly match the Timestamp_Sys100NS value as I mentioned above.  So Timestamp_Perftime is a relative reference to reboot, while those bases are a relative reference to a fixed point in time.

The problem we have is that WMI is slow and we'd prefer to fetch that value from the performance counters. And the performance counters do not have Timestamp_Perftime.   We saved the system time (referenced to 1970) but it's completely incorrect to subtract an "idle time since reboot" from a "total time since 1970" value.

So, the subtraction of idle from "total" is correct, but our calculation of total is the cause of both bugs referenced above:
1. The use of 1970-epoch as a timestamp base is wrong, it should be "milliseconds since startup". 
2. The use of a system timestamp independent from the data source itself leads to timing issues which can result in the counter spinning backwards.

So, how do we fix this?
1. An "easy" fix is just to switch back to % Disk Time.  It slightly overestimates transfer time, but it does not require any reference to any actual clock time.  
   - It's also an upper bound and order-of-magnitude estimate of the true value.
2. The "correct" fix is to use a more accurate timestamp for the counter. This is harder because:
   - We've abstracted the counter queries to draw from 3 possible sources (WMI, HKEY_PERFORMANCE_DATA hive in the registry, and PDH Counters).  WMI gives the Timestamp_Perftime (relative to boot) that we want, but the performance counters do not.  
   - I can get a more accurate millisecond-since-epoch timestamp (available but currently discarded) that would fix the backwards-in-time issue but not the reference point.  (So you could ignore the number, but deltas would never decrease.)  This is probably a good idea anyway and may benefit other counters.
   - I'll have to look into whether just calculating a constant boot time and subtracting is accurate enough (probably) or if there's another source for the basis of the WMI Timestamp_Perftime.

There went my weekend. :D

**Comment by dbwiddis** [comment]
Thought I had something with the "System\System Up Time" performance counter:
```
C:\> wmic path Win32_PerfRawData_PerfOS_System  get systemuptime,timestamp_perftime,timestamp_sys100NS
SystemUpTime        Timestamp_PerfTime  Timestamp_Sys100NS
132556335645000000  1944625507189       132557992268100000
<time elapses>
SystemUpTime        Timestamp_PerfTime  Timestamp_Sys100NS
132556335645000000  1954572367717       132558002215010000
```
That uptime value is a constant corresponding to a 1601-epoch date-time, but:
 - subtracting the uptime constant from the second 100NS timestamp gives 166657 seconds, or 1.93 days, but my boot time was 2.25 days ago.
 - the Timestamp_perftime is 195457 seconds, 2.2622 days.

So it seems using "boot time" is still a better choice than that counter.

**Comment by TheGoesen** [comment]
Just to state our original use case: 
We were are trying to monitor disk active time and give the user a heads up when the disk stays very busy for a prolonged period of time. So we don't really need the most accurate counters. (what's the difference between 65% and 73% disk usage anyway..)
Also we don't need the absolute values to be correct, it would suffice if the relative values are not broken.

**Comment by dbwiddis** [comment]
Thanks for reiterating the original use case.  

For your reference, the existing values are "correct on average" if you measure the interval between two measurements, with a longer interval mitigating any inaccuracy.   

I see a clear path to fix that inaccuracy (and prevent the clock moving backward), and have a decent estimate of what the overall total should be.  As I said, it'll be a fun weekend.

**Comment by TheGoesen** [comment]
Soooooooooooo why and how are we going "correct on average" back in time?  ;) 5 seconds to short? 
Anyway have fun,

**Comment by dbwiddis** [comment]
What I mean is, in the example you gave you were probably under by about 50 ms. Your next query was likely to be over by 50ms. On average you'll be at 0! :)

I've already got the more accurate timestamps (preventing time travel) coded, about to work on the boot time reference.

**Comment by dbwiddis** [comment]
Not so fast with the timestamps, I guess.  I rounded to milliseconds in my implementation, but also rounding the transfer ticks from 100ns to ms results in occasional "backwards by 1ms" events in my testing.  So I guess i need to track the original 100ns timestamps.

**Comment by dbwiddis** [comment]
Bleh. Even with tracking the original 100ns timestamps, there's a slight problem.  Here are 1-second polls of the percent disk time counter (includes queue) and the "more accurate" xfer time counter (1 - idle using highest resolution timestamp we have) with times in milliseconds:
```
Disk 0: disktime=53261.7, xfertime=52325.0
Disk 0: disktime=53261.7, xfertime=52325.4
Disk 0: disktime=53261.7, xfertime=52325.0
Disk 0: disktime=53261.8, xfertime=52325.0
Disk 0: disktime=53266.1, xfertime=52328.0
Disk 0: disktime=53267.6, xfertime=52329.9
Disk 0: disktime=53269.5, xfertime=52331.2
Disk 0: disktime=53270.9, xfertime=52333.0
Disk 0: disktime=53272.6, xfertime=52334.1
Disk 0: disktime=53275.3, xfertime=52337.5
```
The % Disk Time counter is monotonically increasing (good, what we want).  The Xfer time has one hiccup where it rolls backwards by 0.4 milliseconds between the 2nd and 3rd instance above.  

The difference is small (2.4%) implying that perhaps disk time is "close enough", and I'm leaning toward that simpler measure.   Any input on this, @Space2Man?

**Comment by dbwiddis** [comment]
(Or there's the alternative of providing either one based on a config file setting, which actually seems like a great option.)

**Comment by dbwiddis** [comment]
Or, actually, no.  If it were just a millisecond I think it'd be acceptable, but I'm pretty sure the root cause of the inaccuracy here is that the "more accurate" calculation relies on a timestamp that is incremented in clock ticks of 1/64 of a second and thus provides the opportunity for errors up to 16 ms.  I don't think this is really acceptable here.
```
Disk 0: disktime=54058.9, xfertime=52825.9
Disk 0: disktime=54058.9, xfertime=52814.1
Disk 0: disktime=54058.9, xfertime=52827.1
Disk 0: disktime=54058.9, xfertime=52826.6
Disk 0: disktime=54058.9, xfertime=52820.1
```
I'm just going to use % Disk Time.  But at least we have this issue as a record of why that choice was made.
