### ISSUE TITLE
Exposing additional network interface properties

### ISSUE THREAD

**Issue by dornand** [oshi/oshi#1540]
Hello,

i'd like to propose extending the `NetworkIF` with some additional properties:
"ifOperStatus" and "ifAlias" from RFC 2863.

I think, i could contribute a Windows and Linux implementation.
Not sure about the other platforms.

**Comment by dbwiddis** [comment]
Sounds like a great addition.  Do what you can and I'll try to help with the other platforms.

**Comment by dornand** [comment]
For the `ifOperStatus`, should we return an int or make it an enum type?

**Comment by dbwiddis** [comment]
I'm leaning toward an enum (with a getter for the int value) since the values (at least 1, 2, and 3) are well defined by the standard.  It appears Cisco has extended definitions that [Microsoft agrees on](https://docs.microsoft.com/en-us/windows/win32/api/ifdef/ne-ifdef-if_oper_status) ... except in Microsoft are the values 0-indexed compared to the standard's 1-index?  (In which case, even a bigger argument for enum.)
```
    SYNTAX INTEGER {
        up(1),
        down(2),
        testing(3),
        unknown(4),
        dormant(5),
        notPresent(6),
        lowerLayerDown(7)
        }
```
