### ISSUE TITLE
MacOS interrupt values are sometimes decreasing over multiple samples

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1583]
For MacOS, is the value of [getInterrupts](http://oshi.github.io/oshi/oshi-core/apidocs/oshi/hardware/CentralProcessor.html#getInterrupts()) the number of interrupts since the machine started?

If yes, I seem to be getting into a weird situation where the current number of interrupts is LESS than the previous number of interrupts. For example, in my case I'm computing the rate of interrupts over a period, and I'm getting this over multiple samples:

```
PrevInterrupts:1579727, CurrInterrupts:1581443, deltaInterrupts:1716, Duration:1021000000
PrevInterrupts:1581443, CurrInterrupts:1579618, deltaInterrupts:-1825, Duration:1037000000
PrevInterrupts:1579618, CurrInterrupts:1579653, deltaInterrupts:35, Duration:1017000000
PrevInterrupts:1579653, CurrInterrupts:1579628, deltaInterrupts:-25, Duration:1015000000
```

CurrInterrupts is the return value of `getInterrupts`. PrevInterrupts is the stored value of the previous `getInterrupts` call.

OS details is as follows:
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
```

If this is the number of interrupts since the machine started, I should not get a negative difference right? i.e. it should just be continuously increasing. Is this behavior expected for MacOS?

**Comment by dbwiddis** [comment]
This is a feature of macOS:
![image](https://user-images.githubusercontent.com/9291703/112654545-bd343880-8e0c-11eb-9cda-8dff951c28cf.png)

But seriously.... OSHI is using the `host_statisctics()` function with the `HOST_VM_INFO` key ([see here](http://web.mit.edu/darwin/src/modules/xnu/osfmk/man/host_statistics.html)) to return a `vmmeter` structure, and returning the `v_intr` element.  Some old source [here](https://git.privacyone.io/useful/macos-sdk/-/blob/11bc9ba500a038d623714d88bcf93bf003685f9c/MacOSX10.3.9.sdk/usr/include/sys/vmmeter.h) shows the structure:
```
/*
 * System wide statistics counters.
 */
struct vmmeter {
	/*
	 * General system activity.
	 */
	u_int v_swtch;		/* context switches */
	u_int v_trap;		/* calls to trap */
	u_int v_syscall;	/* calls to syscall() */
	u_int v_intr;		/* device interrupts */
	u_int v_soft;		/* software interrupts */
	u_int v_faults;		/* total faults taken */
<snip>
```
There's no other math or logic that would otherwise explain a decreasing number.

Although the vmmeter structure we use is different than the `vm_statistics` structure shown on that doc page (for which we'd return the fourth integer value), so now I'm confused.  I'll look into this more and see if there's a reason we are using that structure.

**Comment by dbwiddis** [comment]
Discussed vaguely in #470 but I can't remember what issues I encountered then.  Looks like I chose the `host_statistics()` approach based on [this psutil code](https://github.com/giampaolo/psutil/blob/master/psutil/arch/osx/cpu.c#L86).  I'll dig into this again and see if I can find more/better documentation.

**Comment by dbwiddis** [comment]
After spending several hours searching, I'm convinced that system level interrupts and context switches are not available on macOS.  Only the process information appears to have those stats.

**Comment by dbwiddis** [comment]
Closing the loop on this:
 - the value that was being reported for interrupts was actually "wired pages" of memory
 - the system level interrupt value appears to be impossible to retrieve on macOS
 - this has been "fixed" to return 0.  Not that helpful, I guess, but I know of no other data source for this.  There is a `latency` command line tool (requires `sudo`) that accumulates a number while it's running, but that's not usable by OSHI.
