### ISSUE TITLE
MacOS process command line is not null-character-delimited if started via shell script

### ISSUE THREAD

**Issue by Dansoftowner** [oshi/oshi#1646]
Hi all!

I have a problem related to [this](https://github.com/Dansoftowner/Restart4j/issues/3) issue in my project.

I use OSHI in [Restart4j](https://github.com/Dansoftowner/Restart4j), a library that allows you to restart a java application programmatically. It basically retrieves the `command line` that started the application -> executes it with the system -> then shuts down the currently running process. For retrieving the command line, I use `oshi.software.os.OSProcess#getCommandLine`.

The documentation says:
>...
On Linux and macOS systems, the string is **null-character-delimited**, to permit the end user to parse the executable and arguments if desired. Further, the macOS variant may include environment variables which the end user may wish to exclude from display.
...

If the application is started via shell script on MacOS, somehow the `command line` is not null-character-delimited, only space-delimited. Splitting the command into a command-array based on spaces might lead to an incorrect result (e. g. if a folder has spaces in its name). The interesting thing is that it only occurs if the app is started from shell script, otherwise the `command line` is correctly delimited by null-chars.

Thanks for your help!

Best regards,
Daniel

**Comment by dbwiddis** [comment]
Techincally if you look up a little bit higher in that same documentation, it says:
> The format of this string is platform-dependent and may require the end user to parse the result.

Which was my official way of deciding that trying to provide parsing into a consistent format for all possible use cases was impossible, and I chose to directly return the command line as retrieved via sysctl (CTL_KERN, KERN_PROCARGS2).

However, this sysctl call no longer appears to work on macOS Big Sur, so I added a `ps` command backup in #1440.  This is where it's probably inserting spaces rather than nulls.

But then it comes back to the question of "whose responsibility is it to parse the result".   I can update OSHI's documentation to indicate that macOS _might_ be space-delimited on newer versions of macOS.  [Parsing space delimiters offers a lot of difficulties. Number one being, your parsing space delimiters](https://youtu.be/7CnBrz_j-a0).

Thoughts?

**Comment by dbwiddis** [comment]
Bah.

So I had a look at the JDK `ProcessHandle` implementation figuring they knew what they were doing.  And they use the sysctl.  Which means that an "unreliable" sysctl points to something I should have looked into when I first discovered that incompatibility.  The "size" argument of the native sysctl command is of type `size_t`.

Way back when I first contributed that code to JNA I assumed it was 4-bytes and code just worked.  However, with macOS Big Sur, size_t is now 8 bytes.

So this is in fact a bug (upstream in JNA) that I should be able to fix and restore the original null-delimited behavior.
