### ISSUE TITLE
Checking memory/pagefile takes a very long time

### ISSUE THREAD

**Issue by Fourmisain** [oshi/oshi#1661]
This issue originated from Minecraft issue [MC-228430](https://bugs.mojang.com/projects/MC/issues/MC-228430), I'll reiterate it here.

It appears that oshi's memory check is very slow (on my system at least), as running the `SystemInfoTest` indicates:
> 2021-06-10 21:16:39.827 [INFO] SystemInfoTest - Initializing System...
2021-06-10 21:16:40.095 [INFO] SystemInfoTest - Checking computer system...
2021-06-10 21:16:40.153 [INFO] SystemInfoTest - Checking Processor...
2021-06-10 21:16:40.207 [INFO] SystemInfoTest - Checking Memory...
2021-06-10 21:17:55.063 [INFO] SystemInfoTest - Checking CPU...

It takes over a minute to check the memory.

The very same happens when booting Minecraft version 1.17, which uses oshi 5.7.4.
There, the log gives further details:
> [16:15:46] [main/WARN] [PerfDataUtil]: Failed to add PDH Counter: \Auslagerungsdatei(_Total)% Usage, Error code: 0xC0000BB8
[16:15:46] [main/WARN] [PerfCounterQueryHandler]: Failed to add counter for PDH object: Auslagerungsdatei
[16:15:46] [main/WARN] [PerfCounterQuery]: Disabling further attempts to query Paging File.
[16:17:03] [Render thread/INFO] [YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

So it seems it's actually the pagefile which takes time to check.
The warnings say that since it can't use the performance counter it retorts to [querying WMI](https://github.com/oshi/oshi/blob/4f56e5ba786121a00779e83af0cbf73ecf57b592/oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java#L105-L112).
I suspect this query is (for some unknown reason) taking a ton of time.

I saw that there is a [timeout](https://github.com/oshi/oshi/blob/4f56e5ba786121a00779e83af0cbf73ecf57b592/oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java#L156) value, defaulting to -1 (no timeout), which can be changed via the `oshi.util.wmi.timeout` setting inside the `oshi.properties` file, and also through the `GlobalConfig` class.

Maybe setting this timeout to a low value would at least help the long Minecraft loading time (though it'd still be the question why it happens in the first place). The issue is that I don't control the code and the `oshi.properties` file is part of the `oshi-core-5.7.4.jar` file, which I also cannot modify without it being redownloaded.

Is there maybe another way of externally changing oshi's config?

**Comment by dbwiddis** [comment]
Thanks for this report.   I'm going to answer in two comments, the first one addressing possible fixes and workarounds and the second one a possible bug that I will look into.

WMI / COM can be slow, particularly if the application is the first one starting up COM after a long delay, although typically this delay should be no more than about 20 seconds.  This is not particular to OSHI, you could see the same delay using the `wmic` command line.    I suspect the 75-second delay in the `SystemInfoTest` output above is due to *multiple* WMI Queries in the Memory class.

Bottom line, we really try to avoid WMI and is only using it in this case due to a failure to lookup localized performance counter names.  If you only have the localized names and not English names in location 009, this can happen. This is a known potential problem that could possibly be fixed by rebuilding performance counters on your machine.

As a potential fix, I suggest you rebuild your performance counters and ensure you have a set of English counters.  To see if this is a potential problem, open your registry editor and look at `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib\009`.  See [instructions here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/rebuild-performance-counter-library-values) or elsewhere using your favorite search engine and the term "rebuild performance counters".

If your English counters are there, see the next comment about a possible bug.

Until performance counters are fixed, here are some other workarounds:

If you still have issues, try to "Wake up" COM before starting Minecraft with a simple command line `wmic` query.  Something like `wmic os` should be sufficient.  If it takes 20 seconds, wait until that's done and then see if everything else is faster.

To directly answer your questions about timeouts -- this is possible to do, but other than the initial startup issues you're seeing, shouldn't really be necessary.

There is an ability to `setWmiTimeout()` on the WMI Query Handler which by default uses the config file's `oshi.util.wmi.timeout` value (default -1 = Infinite).  A new handler object is created for each set of queries, so it's rare you'll use this directly, but there are two ways to work around this.

You can change the timeout value (in milliseconds) in OSHI's config files using this command:
```
GlobalConfig.set("oshi.util.wmi.timeout", 30000);
```
Note this should be done *before* instantiating any OSHI objects (e.g., the first WMI query will keep whatever config value was there.)

Alternately, the [PERFORMANCE](https://github.com/oshi/oshi/blob/master/PERFORMANCE.md#windows-wmi-query-com-initialization) document notes that the WMI Query Handler is extensible.  The example in `oshi-demo` is for not initializing COM if it's been initialized elsewhere, but you could use that example as a template, and add a constructor for your subclass that calls `setWmiTimeout()`.  Then you can `setInstanceClass()` on the handler at any time (not just at startup) to substitute your customized query handler.

**Comment by dbwiddis** [comment]
The whole bit about internationalization of counters shouldn't be an issue for Windows Vista or higher -- meaning, unless you're running on Windows XP, the log entries I see shouldn't be happening.

The log warning displays the value of `path` in this code:
```
int ret = IS_VISTA_OR_GREATER ? PDH.PdhAddEnglishCounter(query.getValue(), path, PZERO, p) 
    : PDH.PdhAddCounter(query.getValue(), path, PZERO, p);<!--EndFragment-->
```
This means it's trying to add an English counter with an already localized name, which is done here:
```


public static <T extends Enum<T>> Map<T, Long> queryValuesFromPDH(Class<T> propertyEnum, String perfObject) {
	T[] props = propertyEnum.getEnumConstants();

    ////////////////////////////////
	// Here we localize the counter
	String perfObjectLocalized = localize(perfObject);

	EnumMap<T, PerfCounter> counterMap = new EnumMap<>(propertyEnum);
	EnumMap<T, Long> valueMap = new EnumMap<>(propertyEnum);
	try (PerfCounterQueryHandler pdhQueryHandler = new PerfCounterQueryHandler()) {
		// Set up the query and counter handles
		for (T prop : props) {

            ////////////////////////////////
			// Here we use the localized value
			PerfCounter counter = PerfDataUtil.createCounter(perfObjectLocalized,
					((PdhCounterProperty) prop).getInstance(), ((PdhCounterProperty) prop).getCounter());
			counterMap.put(prop, counter);

            ////////////////////////////////
			// This is the call that's failing because it's localized
			if (!pdhQueryHandler.addCounterToQuery(counter)) {
				return valueMap;
			}
		}
		// And then query. Zero timestamp means update failed
		if (0 < pdhQueryHandler.updateQuery()) {
			for (T prop : props) {
				valueMap.put(prop, pdhQueryHandler.queryCounter(counterMap.get(prop)));
			}
		}
	}
	return valueMap;
}
```
So I think this is a longstanding localization bug that needs to be fixed. I hope you'll test the fix...

**Comment by Fourmisain** [comment]
> If you only have the localized names and not English names in location 009, this can happen.
> (...)
> To see if this is a potential problem, open your registry editor and look at HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib\009.

I took a look at that path and the counters are all in English, e.g. I see "Paging File" (number 700) in there.

I also found there's two other registry paths:
`HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib\007`,
which I assume doesn't matter and
`HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib\CurrentLanguage`.
Both contain German names, number 700 is "Auslagerungsdatei", so I assume this is where it got the name from?
(Possibly meaning that if they could be made English, there's no issue anymore?)

> try to "Wake up" COM before starting Minecraft with a simple command line wmic query. Something like wmic os should be sufficient. If it takes 20 seconds, wait until that's done and then see if everything else is faster.

Gave that a try, however, `wmic os` was blazing fast (<1s), I could spam it and it ultimately did not improve the other timings.

> You can change the timeout value (in milliseconds) in OSHI's config files using this command: (...)

I can't change Minecraft (at that point in execution time), but I did try this in `SystemInfoTest`.
At first I only got "lucky" queries that took 50ms (probably because I just booted MC before).
After a while, I retried and got a slow query and it was indeed only 30s slow this time.
So this might be a possible workaround that Mojang could add to cut down the boot time.

> Alternately, the PERFORMANCE document notes that the WMI Query Handler is extensible. (...)

Sorry, but I'm positive I understood nothing of that whole paragraph. 😅
Maybe one Mojang employee reading.

------

> The whole bit about internationalization of counters shouldn't be an issue for Windows Vista or higher -- meaning, unless you're running on Windows XP, the log entries I see shouldn't be happening.

I am running Windows 7!

> So I think this is a longstanding localization bug that needs to be fixed. I hope you'll test the fix...

I'd love to!
It'd be ideal if I could just tell Mojang "update oshi to fix the issue".

**Comment by dbwiddis** [comment]
> It'd be ideal if I could just tell Mojang "update oshi to fix the issue".

Yes, I hope to fix it within a few hours and probably cut a release over the weekend.

**Comment by dbwiddis** [comment]
OK, this is fixed in #1662.  It's probably been broken for a very long time (since 3.13.x) but since there was a WMI fallback, the code still worked.   I should have investigated #1265 in more detail which would have clued me in on the problem.

The fix is in SNAPSHOT if you are able to test it.

This should really improve performance for localized users.

**Comment by Fourmisain** [comment]
I **may** have some bad news.

I did some testing and ran twice into the following:

> 2021-06-11 02:39:29.866 [INFO] SystemInfoTest - Initializing System...
2021-06-11 02:39:30.145 [INFO] SystemInfoTest - Checking computer system...
2021-06-11 02:39:30.219 [INFO] SystemInfoTest - Checking Processor...
2021-06-11 02:39:30.275 [INFO] SystemInfoTest - Checking Memory...
2021-06-11 02:39:30.487 [INFO] SystemInfoTest - Checking CPU...
2021-06-11 02:40:47.566 [INFO] SystemInfoTest - Checking Processes...

While I couldn't seem to reproduce the hang when checking memory, it now seems to hangs when checking the CPU.

I say "may" and "seems" because I currently don't trust anything (as you can see, it's *very* late).

I wanted to verify the issue is gone by trying to reproduce the warnings on the old version (going back 1 commit) and checking if they disappear on the new version - because they should, right? The "Disabling further attempts to query" one in `PerfCounterQuery` especially.
But I can't seem to get any log output except for the `SystemInfoTest` logger at all, not even plain `System.out` when running
`mvnw test-compile -pl oshi-core exec:java -Dexec.mainClass="oshi.SystemInfoTest" -Dexec.classpathScope="test"`
Is there a way to see all log output?

I'll retest this tomorrow and hopefully I can help debug this, if there's even an actual bug left.

**Comment by dbwiddis** [comment]
> But I can't seem to get any log output

The tests are actually executed via a plugin and you won't see any output until they all complete.  

It would be good if you could turn on DEBUG level logging to see which specific WMI queries cause the delays.

It doesn't surprise me that the delay has changed to a different location. While I was able to eliminate WMI from anything with a performance counter, there are still several one-time calls.  For the CPU it's fetching the Processor ID, for example.  It's possible the sample `wmic os` query earlier didn't require startup of the same services (RPC is the culprit I think).  Does `wmic path Win32_Processor get ProcessorID` return quickly?

Even with a delay, 20 seconds is the most I've typically seen.  Lots of older issues on this.  #613 is a good one to read.  #474 summaries several others.

**Comment by dbwiddis** [comment]
> One thing that I couldn't overlook is that `PerfCounterWildcardQuery.queryInstancesAndValues()` is not thread-safe due to the use of double checked locking

Doesn't double checked locking make it thread safe?

**Comment by dbwiddis** [comment]
> Disabling further attempts to query Processor Information.

This is expected on Win7.  Those counters exist on Win 10, and Win7 has a WMI table for those.  I suspect Minecraft does not need CPU frequency, so a delay fetching it due to WMI isn't a big deal.

Can you turn on DEBUG level logging to see exactly which WMI queries are causing the delays (and try them in `wmic`)?  Basically WQL `SELECT Foo,Bar FROM Baz` should be `wmic path Baz get Foo,Bar`.  This will isolate any WMI delays to outside OSHI.

**Comment by Fourmisain** [comment]
Got a new log:

> 2021-06-11 18:35:34.873 [INFO] SystemInfoTest - processor.getSystemCpuLoadTicks()
2021-06-11 18:35:34.885 [WARN] PerfCounterWildcardQuery - Disabling further attempts to query Processor Information.
2021-06-11 18:35:34.885 [INFO] PerfCounterWildcardQuery - WMI query: SELECT NAME,PERCENTDPCTIME,PERCENTINTERRUPTTIME,PERCENTPRIVILEGEDTIME,PERCENTPROCESSORTIME,PERCENTUSERTIME FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE NOT Name LIKE "%_Total"
2021-06-11 18:36:49.168 [INFO] SystemInfoTest - processor.getProcessorCpuLoadTicks()

So the command would be
`wmic path Win32_PerfRawData_Counters_ProcessorInformation get NAME,PERCENTDPCTIME,PERCENTINTERRUPTTIME,PERCENTPRIVILEGEDTIME,PERCENTPROCESSORTIME,PERCENTUSERTIME`
(It's missing the `WHERE NOT`, but that really shouldn't matter)

And after a restart, it was slow as expected.

Minecraft does not use `getSystemCpuLoadTicks()`, but is does use `getProcessorCpuLoadTicks()` when starting the profiler (F3+L) and I verified that this does the *same* WMI query and it actually halts Minecraft when pressing the key combination.

So the pause is basically moved from boot to profiling.
I could imagine Mojang adding an asynchronous `getProcessorCpuLoadTicks()` call at boot (and throw away the answer), to "prewarm" WMI as a possible workaround.

**Comment by dbwiddis** [comment]
> I could imagine Mojang adding an asynchronous getProcessorCpuLoadTicks() call at boot (and throw away the answer), to "prewarm" WMI as a possible workaround.

Part of me thinks that's not a bad idea for OSHI to do.

So at this point I don't think we have a bug any more (other than thread safety mentioned above), but we have some config issues on your machine that are creating issues.
 - Your "Processor Information" performance counter doesn't seem to work from OSHI (It works fine in my Win7 VM.)
 - Your WMI is insanely slow for some reason.

I'll switch to a `ConcurrentHashMap` for the queries. Not sure why I didn't do that the first time.

**Comment by Fourmisain** [comment]
> Your "Processor Information" performance counter doesn't seem to work from OSHI (It works fine in my Win7 VM.)

Just had a look at that, `PdhUtil.PdhEnumObjectItems()` fails with the all familiar error code 0xC0000BB8 (the exception is swallowed, so I had to add a log call). That code stands for "The specified object is not found on the system.".

But if I look at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009`, it's right there, number 1848 (it's also in CurrentLanguage, but not in 007 if that matters).

I think I'll try rebuilding the performance counters afterall.

**Comment by Fourmisain** [comment]
Huh.

I did try rebuilding the counters and apparently the instructions you linked, namely the part about readding extended counters, don't quite work for Win7 (and I couldn't find more specific instructions).
The `findstr drivername *.ini` and `lodctr <inifile>` can't work, since there's no ini files directly in System32 (and if searching over the whole Windows folder, there are 342 candidates over 40 drivers).
I'm not sure if that ends up mattering or not, "Processor Information" might be a base counter.

Rebuilding the (base) counters did not fix the issue though, just like before, `PdhUtil.PdhEnumObjectItems()` couldn't find it.

The "huh" about this is that I can't seem to get any super slow WMI queries anymore, the slowest took 7s!

This might actually be a curse in diguise because now the issue isn't obvious anymore.
E.g. I wanted to check if the System Monitor had similar issues, but I can't notice any delay when adding performance counters
![systemmonitor](https://user-images.githubusercontent.com/8464472/121750889-83222b00-cb0d-11eb-9664-ca81d7ef3fc0.png)
(Those should be the same as PERCENTDPCTIME, PERCENTDPCTIME, PERCENTINTERRUPTTIME, PERCENTPRIVILEGEDTIME, PERCENTPROCESSORTIME and PERCENTUSERTIME.)

I was also wondering if there's no alternative, as [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) does just fine polling a metric ton of performance metrics without any lag.

But since it works on your machine™ and is basically fixed on mine, I wonder if we can even call this an issue anymore?

**Comment by dbwiddis** [comment]
I think we can close this issue. I'll fix the thread safety and cut a release tomorrow.
