### ISSUE TITLE
Do we have some samples showing what values are returned for the following on different Linux distros and versions?

### ISSUE THREAD

**Issue by shahzaibj** [oshi/oshi#1676]
I want to be able to detect Linux OS distro and version and I am doing so as follows:

```java
final SystemInfo systemInfo = new SystemInfo();
final String distro = systemInfo .getOperatingSystem().getFamily();
final String version = systemInfo .getOperatingSystem().getVersionInfo().getVersion();
```
First of all, is that the right approach or should I be doing something different? I am asking because there are a few different properties on `OSVersionInfo` object and I found the above logic to give me the right distro and version for Ubuntu 20.04.2 LTS, however, I want to be sure that this approach would work for all distros and versions.

Secondly do we have some samples showing what each of the above methods as well as the other methods on the `OSVersionInfo` object return for different Linux distros and versions? It seems these were meant to live [here](https://github.com/oshi/oshi/wiki/OS-Support), however, I only find `Linux Mint` on that page.

**Comment by dbwiddis** [comment]
> First of all, is that the right approach or should I be doing something different?

It's definitely a reasonable approach.  You may prefer `getVersionInfo().toString()` which combines the version, codename (e.g., "Focal Fossa"), and build number into a single String.  So yes, that approach will return reasonable/sane results as best as we can figure them out on all distributions.

> Secondly do we have some samples showing what each of the above methods as well as the other methods on the OSVersionInfo object return for different Linux distros and versions?

Unfortunately as a crowdsourced page that didn't get any publicity the linked page you showed isn't really current.  And there are so many different distributions it's nearly impossible to count them all!  However, I can outline the general algorithm used which should hopefully answer your question.
 - OSHI attempts to get the family, version, and codename from release files in the following order, stopping when successful
  - Attempt to read `/etc/system-release` which works on CentOS and Fedora and is preferred to the next step
  - Newer distributions put data in `/etc/os-release`, see https://www.freedesktop.org/software/systemd/man/os-release.html
  - If that doesn't work, we try the `lsb_release -a` command or read `/etc/lsb-release`
  - If that doesn't work, we look for `/etc/<some name here>-release/` for which the filename is checked against the list in [`oshi.linux.filename.properties`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.linux.filename.properties) to map to a better family name, otherwise the filename itself is used
 - All of the above files have standard keys for the name, version, and code name or "pretty name" that are used
 - OSHI attempts to read the build number from the version info in `/proc/version`

**Comment by shahzaibj** [comment]
@dbwiddis Thanks a lot - that's helpful!

One more question, I believe the build number inside `/proc/version` is the Linux Kernel Version. Do you know if this is this always true? Or can the version retrieved from here represent something else at times?

**Comment by dbwiddis** [comment]
That is correct `/proc/version` is the kernel version.  This is always used for the "build number" field.  (Otherwise if it fails that field is null.)

**Comment by shahzaibj** [comment]
Cool. That helps - thanks!
