### ISSUE TITLE
COM exception: Invalid Query

### ISSUE THREAD

**Issue by HeZhanfeng** [oshi/oshi#1710]
The following exception occurred on a small number of machines, but the systems are all win10
---
o.u.p.windows.PerfCounterWildcardQuery   : Disabling further attempts to query Process.
2021-09-05 14:27:41.180  WARN 8572 --- [   scheduling-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"

**Comment by HeZhanfeng** [comment]
jdk1.8
maven3.5.4
oshi5.8.1
windows10

**Comment by dbwiddis** [comment]
There is no PageFaultsPerSec in Win32_Process which is clearly a bug.  This is a backup for when performance counters fail.

I believe the correct table should be `Win32_PerfRawData_PerfProc_Process` but some of the other field names will have to be changed.

**Comment by HeZhanfeng** [comment]
Excuse me, after this bug is fixed, when will it be submitted to Maven Central? thanks

**Comment by dbwiddis** [comment]
About 4 hours ago. 😊

 

https://search.maven.org/artifact/com.github.oshi/oshi-core/5.8.2/jar

]

 

Excuse me, after this bug is fixed, when will it be submitted to Maven Central? thanks

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dbwiddis** [comment]
Also of note, if you see this message in the logs:
> o.u.p.windows.PerfCounterWildcardQuery : Disabling further attempts to query xxxx

This is indicative of a problem with the performance counters.  Windows does use WMI as a backup, which is why you only saw the errors on a few machines.  However, WMI is slower than performance counters and those machines still may be candidates for rebuilding performance counters to improve their performance.

**Comment by HeZhanfeng** [comment]
I just tried 5.8.2 and there is still a problem，
my code:
---
SystemInfo systemInfo = new SystemInfo();
OperatingSystem os = systemInfo.getOperatingSystem();
List<OSProcess> processes = os.getProcesses();
// processes size 0

Please tell me how to write it correctly，thanks

**Comment by dbwiddis** [comment]
That code is correct.

There may be a problem with the performance counters on that machine.  See https://docs.microsoft.com/en-US/troubleshoot/windows-server/performance/manually-rebuild-performance-counters
