### ISSUE TITLE
Remove deprecated code and change return types for 6.X

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1723]
**It's time for Hacktoberfest!**

I'm marking this issue for [hacktoberfest](https://hacktoberfest.digitalocean.com/) and [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept PRs for these changes from new contributors to open source as envisioned by the Hacktoberfest project; this can be your first commit, or perhaps a slightly more complex commit than your first if you're just getting started.  Experienced contributors, please leave this issue for those just getting started!

Don't worry if you don't know what to do. Ask for help and I'll hold your hand through this if you need me to. :-) 

As the OSHI 5.x major version has reached a rather stable point, I'm wanting to update API-breaking return types and remove deprecated code as part of a major version bump to 6.x.  You can submit a PR to help out!  

For each of these, please both submit the code to make the change and add appropriate documentation in the UPGRADING.md document.  If you do more than one of the below options, please do a separate PR for each one.

Plese reply to this issue if you're starting working on one of these to avoid anyone duplicating your effort.

- [x] Change the return type of the `NetworkInterface` method [`getMTU()`](https://github.com/oshi/oshi/blob/1aa0c1b9ed13bb5b38a274b440b70abb534c4412/oshi-core/src/main/java/oshi/hardware/NetworkIF.java#L114) from `int` to `long`.  This will require a "signed" `int` to (Java's unsigned) `long` conversion in each of the different OS implementations. `ParseUtil` has an [`unsignedIntToLong()`](https://github.com/oshi/oshi/blob/84a9afc849f52c88042ff1cbcc7d7d212e1b7af0/oshi-core/src/main/java/oshi/util/ParseUtil.java#L426) method you can use for this.

- [x] Change the `OperatingSystem` class method [`getServices()`](https://github.com/oshi/oshi/blob/c5c1b136a50fc82d1c215a9be7da277681dbdba8/oshi-core/src/main/java/oshi/software/os/OperatingSystem.java#L446) to return a `List<OSService>` rather than an array.  This will require chaning the return type for each of the different OS implementations.

- [x] Change the value returned from `MacOSProcess` and `LinuxOSProcess` method `getCommandLine()` from a null-delimited `String` to a space-delimited String.  Update the `OSProcess` javadoc for this method to remove the portion discussing null-terminated String on these two operating systems.  When you update UPGRADING.md add a note to use `getArguments()` as the preferred alternative.

- [x] Remove the deprecated `MACOSX` value from the `PlatformEnum`.  Also remove the special treatment of the deprecated value in the `SystemInfo` class.

- [x] Remove deprecated process sorting methods from the [`OperatingSystem`](https://github.com/oshi/oshi/blob/c5c1b136a50fc82d1c215a9be7da277681dbdba8/oshi-core/src/main/java/oshi/software/os/OperatingSystem.java) class.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make one of the changes indicated above.
- Also update the UPGRADING.md document for "upgrading from 5.X to 6.X"
- Also asdd a CHANGELOG.md entry
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by Simba-97** [comment]
I would love to contribute and get started with this issue.

**Comment by varnaa** [comment]
Hey, I'd like to contribute to this issue. Thanks for the warm welcome for first timers ☺️

**Comment by dbwiddis** [comment]
@Simba-97 and @varnaa Welcome. Please say which one of the 5 options you'll start working on! :)

**Comment by Simba-97** [comment]
@dbwiddis I'll be working on the first issue. Can you help me out with the folder structure? I can't find the file I need to make changes to.

**Comment by dbwiddis** [comment]
@Simba-97 the interface is in `oshi/oshi-core/src/main/java/oshi/hardware/NetworkIF.java`

You'll also need to update code in the operating system implementations in `oshi/oshi-core/src/main/java/oshi/hardware/platform/foo/FooNetworkIF.java` (replace "foo" with the various OS folders)

**Comment by varnaa** [comment]
@dbwiddis i want to work on removing the deprecated process sorting methods from the **OperatingSystem** class.

**Comment by arsen1c** [comment]
@dbwiddis Can I work on option 2?

**Comment by dbwiddis** [comment]
Current "assignments"
 - @Simba-97 is working on NetworkIF getMTU
 - @arsen1c is working on getServices
 - @varnaa is working on deprecated process sorting methods

**Comment by Novaenn** [comment]
Can I work on option 4?

**Comment by ripalx9173** [comment]
Hi ,
I would like to work on this .Specially on issue 1. can you please guide me for the same.

**Comment by evansusu** [comment]
evansoo@Evans-MBP first-contributions % git push origin Evensusu-branchremote: Permission to Evensusu/first-contributions.git denied to Evensusu.
fatal: unable to access 'https://github.com/Evensusu/first-contributions/': The requested URL returned error: 403

I can't git push origin to contribute to this project and receive the above error :(

**Comment by tejaskulkarni28** [comment]
Hii,
I am new to open source contribution. I have one doubt, for one issue there can't be more contributors! as said in(Plese reply to this issue if you're starting working on one of these to avoid anyone duplicating your effort.) Thanks 😊

**Comment by dbwiddis** [comment]
@ripalx9173 someone is already working on the first one for now.  The third one (`getCommandLine()`) is the only one currently unclaimed.  It looks like @tejaskulkarni28 is also interested, so that's available for whichever one of you claims it first.

**Comment by dbwiddis** [comment]
@evansusu not sure which one you're trying to work on. If you forked the project to your own branch you should be able to use your own GitHub credentials when committing.  You might need to set up a personal access token?  I'm not sure exactly what the issue is there but it's credential related.

**Comment by prathamgandhi** [comment]
Hey @dbwiddis I'm interested in the third one. Since this will be my first PR, I might need some help, I've figured out the directories by now though

**Comment by dbwiddis** [comment]
@prathamgandhi Third one is all yours.   So currently all these are claimed.  I'll get another issue up shortly with plenty of room for everyone to submit something.

**Comment by prathamgandhi** [comment]
Just for testing it out before I went any further (never done unit testing ever) I ran mvn test in the source directory and for some reason oshi-core fails after execution of all the tests?? However, it did output all my system details, like running processes, IP address, MAC address and everything. So am I doing something wrong? I just cloned the repo and ran mvn test in the command line.

**Comment by dbwiddis** [comment]
It should tell you which test fails (it's above the output you referenced).   Can you tell me which one it was?

There is a test on code format which could fail on things like whitespace, etc. even if the code works.

There are some tests that occasionally fail (counting number of child processes, for example) which generally work if you try it a second time.

**Comment by dbwiddis** [comment]
Also you should run mvn test from the project root (oshi-parent), not from oshi-core.

**Comment by dbwiddis** [comment]
Losts of new tasks in #1727

**Comment by prathamgandhi** [comment]
@dbwiddis Yeah running it from the root of the project. It doesn't seem like the occasional fail, because I've done it about 5-6 times and it fails entirely. Since I'm not entirely sure about what might be relevant, I'll just post the major snippets of the output here.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Operating System and Hardware Information                          [pom]
[INFO] oshi-core                                                          [jar]
[INFO] oshi-core-shaded                                                   [jar]
[INFO] oshi-demo                                                          [jar]
[INFO] oshi-dist                                                          [pom]
[INFO] 
[INFO] --------------------< com.github.oshi:oshi-parent >---------------------
[INFO] Building Operating System and Hardware Information 5.8.3-SNAPSHOT  [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
.
.
.
[INFO] Launching JUnit Platform 1.8.1...
[INFO] Output Log: 12,188 bytes, Error Log: 19,114 bytes
[ERROR] 
[ERROR] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
[ERROR] 
[ERROR] .
[ERROR] +-- JUnit Jupiter [OK]
[ERROR] | +-- UsbDeviceTest [OK]
[ERROR] | | '-- testUsbDevices() [OK]
[ERROR] | +-- FileUtilTest [OK]
[ERROR] | | +-- testReadProcIo() [OK]
[ERROR] | | +-- testReadProperties() [OK]
[ERROR] | | +-- testReadFile() [OK]
[ERROR] | | '-- testGetFromFile() [OK]
[ERROR] | +-- UtilTest [OK]
[ERROR] | | +-- testWildcardMatch() [OK]
[ERROR] | | +-- testSleep() [OK]
[ERROR] | | +-- testIsBlankOrUnknown() [OK]
[ERROR] | | '-- testIsBlank() [OK]
[ERROR] | +-- ExecutingCommandTest [OK]
[ERROR] | | '-- testRunNative() [OK]
[ERROR] | +-- OperatingSystemTest [OK]
[ERROR] | | +-- testGetEnvironment() [OK]
[ERROR] | | +-- testGetDesktopWindows() [OK]
[ERROR] | | +-- testThreads() [OK]
[ERROR] | | +-- testGetServices() [OK]
[ERROR] | | +-- testGetSessions() [OK]
[ERROR] | | +-- testGetChildAndDependentProcesses() [OK]
[ERROR] | | +-- testOperatingSystem() [OK]
[ERROR] | | +-- testProcessStats() [OK]
[ERROR] | | +-- testGetArguments() [OK]
[ERROR] | | +-- testProcessQueryByList() [OK]
[ERROR] | | +-- testGetCommandLine() [OK]
[ERROR] | | '-- testProcessStrings() [OK]
[ERROR] | +-- FileSystemTest [OK]
[ERROR] | | '-- testFileSystem() [OK]
[ERROR] | +-- SourceCodeTest [OK]
[ERROR] | | '-- testCheckstyle() 10542 ms [X] There are Checkstyle errors found
[ERROR] | |       Expected: Has no Checkstyle issues
[ERROR] | |            but: 
[ERROR] | |       warning  containsTab                              /home/pratham/git/oshi/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java:121    Line contains a tab character.
[ERROR] | +-- VirtualMemoryTest [OK]
[ERROR] | | '-- testGlobalMemory() [OK]
[ERROR] | +-- CentralProcessorTest [OK]
[ERROR] | | +-- testTicks() [OK]
[ERROR] | | +-- testProcessorIdentifier() [OK]
[ERROR] | | +-- testFrequencies() [OK]
.
. (Many more error ok pairs like this below follow)
.
[ERROR] Failures (1):
[ERROR]   JUnit Jupiter:SourceCodeTest:testCheckstyle()
[ERROR]     MethodSource [className = 'oshi.SourceCodeTest', methodName = 'testCheckstyle', methodParameterTypes = '']
[ERROR]     => java.lang.AssertionError: There are Checkstyle errors found
[ERROR] Expected: Has no Checkstyle issues
[ERROR]      but: 
[ERROR] warning  containsTab                              /home/pratham/git/oshi/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java:121    Line contains a tab character.
.
.
.
[ERROR] Test run finished after 30536 ms
[ERROR] [        33 containers found      ]
[ERROR] [         0 containers skipped    ]
[ERROR] [        33 containers started    ]
[ERROR] [         0 containers aborted    ]
[ERROR] [        33 containers successful ]
[ERROR] [         0 containers failed     ]
[ERROR] [       130 tests found           ]
[ERROR] [         0 tests skipped         ]
[ERROR] [       130 tests started         ]
[ERROR] [         0 tests aborted         ]
[ERROR] [       129 tests successful      ]
[ERROR] [         1 tests failed          ]
[ERROR] 
[ERROR] 2021-10-02 09:16:55.890 [ERROR] FileUtil - Error reading file /proc/2755/environ. /proc/2755/environ
[ERROR] 2021-10-02 09:17:21.092 [INFO] SystemInfoTest - Initializing System...
[ERROR] 2021-10-02 09:17:21.099 [INFO] SystemInfoTest - Checking computer system...
[ERROR] 2021-10-02 09:17:21.337 [INFO] SystemInfoTest - Checking Processor...
[ERROR] 2021-10-02 09:17:21.345 [INFO] SystemInfoTest - Checking Memory...
[ERROR] 2021-10-02 09:17:21.347 [INFO] SystemInfoTest - Checking CPU...
[ERROR] 2021-10-02 09:17:22.479 [INFO] SystemInfoTest - Checking Processes...
[ERROR] 2021-10-02 09:17:22.571 [INFO] SystemInfoTest - Checking Services...
.
.
.
[ERROR] 2021-10-02 09:17:25.138 [INFO] SystemInfoTest - Printing Operating System and Hardware Info:
[ERROR] GNU/Linux Pop!_OS 20.04 LTS (unknown) build 5.8.0-7630-generic
[ERROR] Booted: 2021-10-02T03:45:01Z
[ERROR] Uptime: 0 days, 00:02:19
[ERROR] Running without elevated permissions.
[ERROR] Sessions:
.
.
.
[ERROR] My PID: 4146 with affinity 1111
[ERROR] Processes: 260, Threads: 701
[ERROR]    PID  %CPU %MEM       VSZ       RSS Name
[ERROR]   4146 206.5  5.8   5.3 GiB 454.4 MiB java
[ERROR]   4074  81.0  5.3   5.5 GiB 418.3 MiB java
[ERROR]   2755   4.8  2.9   4.1 GiB 230.8 MiB gnome-shell
[ERROR]   4041   2.8  0.9 778.3 MiB  69.0 MiB nautilus
[ERROR]    796   2.1  0.3 610.6 MiB  20.3 MiB NetworkManager
[ERROR] Current process arguments: 
.
.
.
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Operating System and Hardware Information 5.8.3-SNAPSHOT:
[INFO] 
[INFO] Operating System and Hardware Information .......... SUCCESS [  7.123 s]
[INFO] oshi-core .......................................... FAILURE [ 42.205 s]
[INFO] oshi-core-shaded ................................... SKIPPED
[INFO] oshi-demo .......................................... SKIPPED
[INFO] oshi-dist .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.112 s
[INFO] Finished at: 2021-10-02T09:17:25+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.1.5:launch (injected-launch) on project oshi-core: RED ALERT! -> [Help 1]
.
.
.

**Comment by evansusu** [comment]
@dbwiddis Yes I created personal access token but still it happens same error

**Comment by prathamgandhi** [comment]
Yeah, @dbwiddis also I wanted to confirm something about my task. I need to replace the null-delimited string to space delimited string, but in java the delimition is used only while splitting a string into a list, but the return type is not a list? So I suspect I must not do that. Is it like C-style null-termination of strings? Or something like a string of form "Some\0random\0text" to "Some random text"?

**Comment by dbwiddis** [comment]
@prathamgandhi from the error trace, here is the problem:
```
[ERROR] | | Expected: Has no Checkstyle issues
[ERROR] | | but:
[ERROR] | | warning containsTab /home/pratham/git/oshi/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java:121 Line contains a tab character.
```
As for the task, the native string returned is null delimited so you need to use `split()` to split on the null, and then join back together with space delimiter.  From memory I think this might work: `Arrays.stream(nullDelimString.split('\0')).collect(Collectors.joining(" "));`

**Comment by dbwiddis** [comment]
@evansusu are you using an IDE or command line? What operating system? Have you searched Stack Overlow with your error text to see if it makes suggestions?

**Comment by prathamgandhi** [comment]
@dbwiddis I've done a pull request on the third issue. Do check and let me know. I guess a message isn't required here, but just to make sure
