### ISSUE TITLE
Revamping README and site pages

### ISSUE THREAD

**Issue by TurboFiero** [oshi/oshi#1819]
Forgive my ignorance but it seems there isnt even a guide on how to use this?

Claims to be compatible with everything, alright then, show us? 

launching with java does literally nothing?

**Comment by dbwiddis** [comment]
As a library, OSHI is not intended to be run as a stand-alone application. It provides a pure Java interface that you can incorporate into your own application.

There are specific instructions in the README document (also the project's github homepage) showing:
1. Usage: https://github.com/oshi/oshi/blob/master/README.md#usage
2. Getting output from your own machine: https://github.com/oshi/oshi/blob/master/README.md#output

In addition, several common implementation examples are implemented as proof-of-concept in the `oshi-demo` artifact here: https://github.com/oshi/oshi/tree/master/oshi-demo/src/main/java/oshi/demo

If these links do not provide enough information for you to use the library, please be more specific in what you're trying to do and we can give a more specific answer.

**Comment by dblock** [comment]
Maybe mention https://github.com/rememberber/MooInfo as a demo very early in the README, or another example @TurboFiero please contribute to the README if it's unclear. 

I suggest closing this because if the README isn't  "a guide on how to use this", I don't know what is.

**Comment by dbwiddis** [comment]
> I suggest closing this because if the README isn't "a guide on how to use this", I don't know what is.

I think I'll move the SystemInfoTest snippet from "Output" to the "Usage" (how to use) section of the README. The whole output section could probably be trimmed to just show the screencaps.

I'll leave this open for now as a reminder to myself.

**Comment by adrian-kong** [comment]
> I think I'll move the SystemInfoTest snippet from "Output" to the "Usage" (how to use) section of the README. The whole output section could probably be trimmed to just show the screencaps.

oh yea maybe a mkdocs/docsify or something documentation site generator would be really cool maybe on like readthedocs.io
or just github pages ? and we can move some of the readme to there to keep everything nice and clean

that would be something i could contribute to but looks like someone else already took the name oshi https://oshi.readthedocs.io/en/latest/

**Comment by dbwiddis** [comment]
For most github projects, the README with markdown is sufficient. Certainly it could be trimmed up with some organization.

That other project looks abandoned and most companies have procedures to claim abandoned names. (Our github oshi org was pre-owned.)

We do have github pages but it just mirrors the README: https://oshi.github.io/oshi/README.html (but could be customized).

**Comment by adrian-kong** [comment]
> We do have github pages but it just mirrors the README: https://oshi.github.io/oshi/README.html (but could be customized).

ooh didnt realize that could i organize/seperate the readme to maybe different sections/pages?
would it be under https://github.com/oshi/oshi/tree/master/src/site

**Comment by dbwiddis** [comment]
Yes, the github site is built from the copy of the README at src/site/markdown:
https://github.com/oshi/oshi/blob/master/src/site/markdown/README.md

It's built using maven-site-plugin.  

I welcome any PR that improves the documentation.

**Comment by mprins** [comment]
> We do have github pages but it just mirrors the README: https://oshi.github.io/oshi/README.html (but could be customized).

@dbwiddis You could/should add that link (https://oshi.github.io/oshi/) to the "About" on the front page (top right cog wheel on https://oshi.github.io/oshi/)

**Comment by dbwiddis** [comment]
> @dbwiddis You could/should add that link (https://oshi.github.io/oshi/) to the "About" on the front page (top right cog wheel on https://oshi.github.io/oshi/)

It is already.  I don't see where that changes anything though.

![image](https://user-images.githubusercontent.com/9291703/148109356-83281f1a-67c7-43da-8b2a-c0487491279e.png)

**Comment by adrian-kong** [comment]
> It is already. I don't see where that changes anything though.

i think he meant put a link in the description as well so it shows up on the right hand side easier to find like maybe something like

```
Native Operating System and Hardware Information

https://oshi.github.io/oshi/
```

for description because i didnt know that link existed until u mentioned it 

maybe we can move majority of the README on the front page out to github pages for better reading experience less scrolling involved? not really a big deal more like minor developer experience but i think as you mentioned something about traffic so not really sure

**Comment by dbwiddis** [comment]
> for description because i didnt know that link existed until u mentioned it

And the reason is that it entirely duplicated the main project website, so there was no reason to link to something redundant.

And until we update the main README there's still no reason to link to something redundant.

And there are many themes we could put on the site to make it prettier.

And there are many other creative things we can do.

I'm happy to entertain ideas and provide input, and if someone out there is creative and wants to prettify the site, I'm all for it!  

I would like it to be as low maintenance as possible for me when I do README updates, though, meaning I'd like to not duplicate things unless it's a complete duplication.

**Comment by mprins** [comment]
> i think he meant put a link in the description as well so it shows up on the right hand side easier to find like maybe something like

Nope; the website url is supposed to appear below the description, like so:
![image](https://user-images.githubusercontent.com/1165786/148231548-5e2d84fc-cd9a-4ece-a9a1-fdb9725162d0.png)

No idea why it doesn't show up...

If there is interest I can create a PR with a workflow that builds the Maven site and pushes to gh-pages like I did here: https://github.com/B3Partners/tailormap-api/blob/b47128573c8440b7137ed3f4d12f613626c3b524/.github/workflows/ubuntu-maven.yml#L47-L82

**Comment by dbwiddis** [comment]
I think we already have such a workflow. We just push to the “site” branch.  

I may be wrong though.  :)

**Comment by mprins** [comment]
ahh yes, I see https://github.com/oshi/oshi/blob/master/.github/workflows/site.yaml pushes to gh-pages on a release message

**Comment by dbwiddis** [comment]
Yep, and we can manually trigger that workflow if desired.

**Comment by dbwiddis** [comment]
Quick update:
 * Regarding @mprins suggestion for the "About" link -- turns out the suggested link in my screencap was just a pre-filled suggestion and not actually filled in.  I've fixed that link, for what it's worth.
 * I just spent a bit of time reorganizing the README content, thanks to @TurboFiero suggestions and @adrian-kong original PR trimming some of the content.  See #1903 or just go to this branch to preview the new(er) README: https://github.com/dbwiddis/oshi/tree/readme
   * Reduced badge-spam by moving all the CI badges way down to their own section
   * Switched downloads from confusing tabular layout to simple bullets
   * Moved sample output and projects using OSHI to their own new pages.  
     * Linked to those and other relevant pages under "Documentation".  
     * Also created a new "Documentation" directory and moved most things there
     * (left CHANGELOG where it was 'cause it's pretty important and also linked in every single release)
   * Moved a lot of usage-related stuff to the Usage section:
     * The original "usage" context with less distraction
     * The link to SystemInfoTest
     * The link to oshi-demo

Let me know if you have any suggestions before (or after) I merge.

**Comment by dbwiddis** [comment]
> oh yea maybe a mkdocs/docsify or something documentation site generator would be really cool maybe on like readthedocs.io or just github pages ? and we can move some of the readme to there to keep everything nice and clean
> 
> that would be something i could contribute to but looks like someone else already took the name oshi https://oshi.readthedocs.io/en/latest/

@adrian-kong I am the proud new owner of that oshi readthedocs link.  Let me know what you think we should do with it. :)
