### ISSUE TITLE
Wrong CPU load Data ?

### ISSUE THREAD

**Issue by vickllny** [oshi/oshi#1870]
Hello, I used the following code to query the CPU usage, but the value is always lower than the CPU usage in the task manager.

processor.getSystemCpuLoadBetweenTicks(prevTicks)  * 100;

The source code is in the file SystemInfoTest.java, I have not made any changes

**Comment by adrian-kong** [comment]
I think this might be in the FAQ

https://github.com/oshi/oshi/blob/master/FAQ.md#why-does-oshis-process-cpu-usage-differ-from-the-windows-task-manager

**Comment by dbwiddis** [comment]
Which OS? How long between ticks?

**Comment by dbwiddis** [comment]
Short answer: "Yes, the Task manager gives 'Wrong CPU load Data'."   😁 

Longer answer(s):
 - The method you cite calculates the overall percent load of the entire system, dividing the amount that is "user" and "system" usage by the "total" usage which includes the "idle" process.  This is an accurate 0% to 100% measure of overall CPU utilization.
 - Windows has an option to scale to 100% for the system, but often is configured to scale to 100% per processor, so on a 4-core system, if all 4 cores were fully loaded, you'd get 400%.  This is actually the metric used on all other OS's.
 - But rarely are you using all 4 processors fully, a single threaded process might be using one fully.  Is that 25% usage (what OSHI would say) or 100% usage (what *nix and sometimes Windows might say)?   
 - Windows rounds ticks to the nearest 1/64 of a second, per processor.  So if you're measuring a 1-second time period like SystemInfoTest, each processor could be off by 1/64 of a second for each of the 3 tick counter sources (Idle, Kernel, User).  On an 8-logical-processor machine that's up to 24/64 of a second of potential round-off error.

Here's [an interesting article summarizing Task Manager shortcomings](https://aaron-margosis.medium.com/task-managers-cpu-numbers-are-all-but-meaningless-2d165b421e43).

There is a potential for user error depending on if you're saving the ticks correctly... if they are invalid ticks they are treated as 0 and you're getting the "average CPU usage since the system started".   So I'd have to see your full code to make sure you're properly saving the previous ticks.

If you can give specific examples of differences over a longer time period I'd be happy to give you a more specific analysis of the differences you're seeing.  I'd suggest a 5- or 10-second period between collecting ticks and compare that to the average task manager over the same time period.

**Comment by dbwiddis** [comment]
I took the counters referenced in the article above and did a quick check on my system, under normal load (one processor fully loaded on a single thread at 100% but the others idle) and opening many browser tabs with lots of computation.

Green line is what task manager reports. Red line is what OSHI reports.  OSHI over-counts when load is low (because system scales back idle processor frequency).  Task manager over-counts when capped at 100% and actually does >100% load (how's that?).

![image](https://user-images.githubusercontent.com/9291703/151058322-4b3996f4-779a-480b-a94c-1bd53a937e5f.png)

**Comment by vickllny** [comment]
How did you get the CPU usage data from task manager?  I want to get the CPU usage data of the task manager on my computer and compare it.

**Comment by dbwiddis** [comment]
Processor Time (what OSHI uses) is a percentage of time the CPU is working.  It can never exceed 100%.

Processsor Utility (what Task Manager uses) is a relative measure of "processing work completed" compared to a fully loaded processor at nominal performance settings.  It can exceed 100% if the processor is boosting its performance.

I'll quote the exact descriptions, highlighting the difference.
> % Processor Time is the percentage of elapsed time that the processor spends to execute a non-Idle thread. It is calculated by measuring the percentage of time that the processor spends executing the idle thread and then subtracting that value from 100%. (Each processor has an idle thread to which time is accumulated when no other threads are ready to run). **This counter is the primary indicator of processor activity, and displays the average percentage of busy time observed during the sample interval.** It should be noted that the accounting calculation of whether the processor is idle is performed at an internal sampling interval of the system clock tick. On todays fast processors, % Processor Time can therefore underestimate the processor utilization as the processor may be spending a lot of time servicing threads between the system clock sampling interval. 

> Processor Utility is the **amount of work a processor is completing**, as a percentage of the amount of work the processor could complete if it were running at its nominal performance and never idle. On some processors, Processor Utility may exceed 100%.

**Comment by vickllny** [comment]
Thank you for answering me so enthusiastically. What you said is beyond my knowledge limit. I have to spend a lot of time to learn the above 👍 


I tested it again on my work computer.
This is my code  https://github.com/vickllny/cpu-usage.git

I compared the log I output with the polyline of the CPU usage of the task manager. The CPU usage of the task manager remains at more than 60%, but the CPU usage obtained by using OSHI remains at more than 50%. What is going on?If this is a problem, how can I fix it?
<img width="1052" alt="cpu-usage" src="https://user-images.githubusercontent.com/31479141/151275182-d560f558-6f28-4fd0-9327-ff0b54d427cf.png">

**Comment by dbwiddis** [comment]
> What is going on? If this is a problem, how can I fix it? 

What is going on is that Task Manager is measuring something different than OSHI.  At the higher load, your processors are boosting their frequency to get more work done, but OSHI is reporting just "active vs. idle" time, not work.

I can look into adding a config parameter to allow users to switch to the "Work completed" metric that Task Manager uses.  Would that be useful?

**Comment by vickllny** [comment]
> I can look into adding a config parameter to allow users to switch to the "Work completed" metric that Task Manager uses. Would that be useful?

That's great. But this feature is only for windows? Should linux and other operating systems not need this feature?

**Comment by dbwiddis** [comment]
No, all the Unix-based operating systems use "time-based" cpu load.  Only windows does different things on Task Manager.

**Comment by vickllny** [comment]
All Right!!!

**Comment by dbwiddis** [comment]
I've done an initial test which looks "sane" but I'm not yet confident in it.  Can you test the latest SNAPSHOT build?

**Comment by vickllny** [comment]
Very happy to test, what is the latest snapshot version number?

**Comment by dbwiddis** [comment]
A link on the README should grab the latest one.   Here it is:  https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi/oshi-core/6.1.1-SNAPSHOT/oshi-core-6.1.1-20220127.071845-15.jar

**Comment by dbwiddis** [comment]
Well I was able to test it myself on a different machine ... good news is it "mostly" works. Bad news is it's off by exactly a factor of 2.   I had assumed when I wrote the existing code that the "multiply by 8" on the base counter was number of processors, but my work machine has a multiple of 16.

The base counters are associated with the elapsed time and the "nominal work of the processor" so it's not obvious where I could get that data.  I *can* get the data from WMI's counter tables, but those are far less efficient than querying the counters directly.   So I'll have to do some digging around to see if there's another way to recover that multiplicative constant in the base.

**Comment by vickllny** [comment]
> So I'll have to do some digging around to see if there's another way to recover that multiplicative constant in the base.

Sounds like this solution works!

**Comment by dbwiddis** [comment]
> Sounds like this solution works!

It works if I use the number 16.

But I don't know *why* 16. :)

**Comment by vickllny** [comment]
> It works if I use the number 16.
> 
> But I don't know _why_ 16. :)

You mean it has something to do with CPU logic cores? em..... My CPU is 8 cores and 8 threads, and the result of my test is also that the usage rate of the task manager is 2 times that of the program

**Comment by dbwiddis** [comment]
I have two 4 core/8 thread machines, same results.  16 may be a constant.  Or it may not.   It might be 2x processors.  Or some other formula.  Until I know why I’m not sure I should hardcode it.

**Comment by vickllny** [comment]
What is the correct calculation method? Confusing

**Comment by dbwiddis** [comment]
The “correct” calculation method uses the difference in the `PercentProcessorCapacity_Base` value to divide the difference in `PercentProcessorCapacity`.  This can be done with WMI.   However, WMI queries are a bigger performance hit. It is preferred to use the “% Processor Capacity” counter via PDH.  

But there is no “base” counter.  

We have the same issue with the existing counters but the base is just elapsed time and since we have idle ticks we can back into the calculation. 

The base in this case appears to be elapsed time / 1600.  The 100 makes sense as it is a percent unit.  The 16… ?

**Comment by dbwiddis** [comment]
Did some benchmarking... WMI takes about 90 ms on average; PDH is about 15 ms.

One hacky workaround is to start off with WMI long enough to derive/confirm the conversion and then switch to PDH later.  I'd prefer something less hacky.

**Comment by vickllny** [comment]
The performance of PDH seems to be much better than WMI.
> One hacky workaround is to start off with WMI long enough to derive/confirm the conversion and then switch to PDH later.

What does this sentence mean, I don't quite understand?

**Comment by dbwiddis** [comment]
The first two times a user asks for cpu ticks it would query WMI which makes the base available.  Once it had two queries with time stamps it would have enough info to calculate that “16” factor and it could use the faster PDH queries later.

**Comment by dbwiddis** [comment]
Aha.  Figured it out.  Counters actually return two values, but we've only been using the first one.  The base value is returned with the original counter as "SecondValue", we just haven't been reading it.

**Comment by dbwiddis** [comment]
OK, [another snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi/oshi-core/6.1.1-SNAPSHOT/oshi-core-6.1.1-20220129.221237-21.jar) ready for you to test.

**Comment by vickllny** [comment]
Ok, thank you, the company has a holiday, I will test it on my machine immediately after I come back from the holiday

**Comment by dbwiddis** [comment]
I was able to do some pretty thorough testing and it aligned perfectly (other than capping at 100% when my computer was at 225% load).  

This is implemented in #1886 which is now available in the latest snapshot linked from the README.  

You'll need to either edit your `oshi.properties` config or use `GlobalConfig.set(ProcessorInformation.USE_CPU_CAPACITY, true);` shortly after startup (at least before the first instantiation of the Central Processor class).   See [the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#why-does-oshis-system-and-processor-cpu-usage-differ-from-the-windows-task-manager).

**Comment by Jiangyongqiang** [comment]
mark，i have the same problem，tanks。

**Comment by dbwiddis** [comment]
Have you tested the latest snapshot?

**Comment by vickllny** [comment]
I have tested the latest snapshot, and the CPU usage obtained is basically the same as the usage of the task manager. But the static variable ProcessorInformation.USE_CPU_CAPACITY does not exist? I am using ProcessorInformation.OSHI_OS_WINDOWS_CPU_UTILITY and the oshi-core version number is 6.1.1-SNAPSHOT

**Comment by dbwiddis** [comment]
Hmm. Apparently it's a public variable but the class is package private.  I should probably move all these config-based variables into `GlobalConfig`.   You can just put the same string as in the config file in its place.

**Comment by vickllny** [comment]
OK

**Comment by dbwiddis** [comment]
OK, so I realize the CPU_CAPACITY was a typo.  You had the correct constant but it (and others) are now on GlobalConfig in the latest snapshot.

Thanks for testing.
