### ISSUE TITLE
Issues follow #Wrong CPU load Data ? #1870

### ISSUE THREAD

**Issue by Jiangyongqiang** [oshi/oshi#1936]
@dbwiddis   Hello, Daniel, I use the latest version of 6.1.1 to test the CPU utilization. The utilization rate will be greater than the actual utilization rate within about five minutes after startup, and exceed 100%. It will return to normal after five minutes. Why?
![企业微信截图_20220218095903](https://user-images.githubusercontent.com/13825585/154603233-db9c5c5a-2a36-4915-b7ee-73ff4c37507e.png)

**Comment by dbwiddis** [comment]
What does the task manager show over the same time period?

**Comment by Jiangyongqiang** [comment]
@dbwiddis 
I've used the snapshot version before. This version is accurate
https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi/oshi-core/6.1.1-SNAPSHOT/oshi-core-6.1.1-20220129.232529-24.jar

![333](https://user-images.githubusercontent.com/13825585/154613304-6bc51269-7cc7-49a3-af88-f1b5a366cbc8.png)

**Comment by dbwiddis** [comment]
Can you print out the ticks each second so I can see what’s happening with them?

**Comment by Jiangyongqiang** [comment]
> Can you print out the ticks each second so I can see what’s happening with them?
![444](https://user-images.githubusercontent.com/13825585/154624165-57a6e85a-3afe-4707-a29d-f23871c2779a.png)

**Comment by dbwiddis** [comment]
OK, I'm unable to reproduce this on my machine.  There's clearly a problem in the data, however, as the system ticks are decreasing which should not be possible.

Can you please fork the project and execute from the fork, and gather some data on the internal calculations?  The ones that are important here are:
- The baseticks, privticks, and procticks arrays populated in the WindowsCentralProcessor constructor (lines 114-116, so print out the value after that loop completes)
- Those same values when queried from the counters at lines 350-352 (those are lists that you may need to create arrays from to print)
- The intermediate idlepercent and syspercent (per processor) on lines 402-403

**Comment by dbwiddis** [comment]
Some other thoughts. The way the code works is:
- it immediately catches a snapshot of the capacity counter ticks and the base (timer snapshot) when the CentralProcessor is instantiated, and saves them.
- for all future ticks it calculates the difference in counters (both process/system and the "base") which produces a "percentage" over that time period.
- The percentage can then be multiplied by elapsed time to determine the overall tick calculation
- There is a potential for roundoff problems but the values are 64-bit so that shouldn't be too big of an impact

The output you've posted shows that:
 - early on the numbers are very large suggesting the denominator may be very small; this also correlates to situations where the CPU load is small
 - after enough time (or cumulative CPU load) it acts as designed 

This suggests that there may be some rounding issues before enough time or cumulative CPU load has accumulated.  Specifically given the declining numbers for system (kernel) CPU ticks, this may be the case when there is near-zero "privileged" CPU load.

These calculations could be mitigated by defaulting to the "old" calculation based on some measure of inaccuracy (perhaps seeing negative system ticks?) which still wouldn't match Task Manager but would be a lot closer than the given values.

Still, to confirm this thought, I'd need some more run data from you.

**Comment by dbwiddis** [comment]
I refactored the calculations in #1937 ... while I don't think that changes anything it does simplify the logic and if there was an error it would have fixed it.  Please test out the latest snapshot.

**Comment by Jiangyongqiang** [comment]
OK, let me try

**Comment by Jiangyongqiang** [comment]
I used the latest snapshot version 6.1.3-snapshot to test it. It seems that the CPU utilization at startup is accurate and stable over time. @dbwiddis 。
![new_cpu_2](https://user-images.githubusercontent.com/13825585/154877715-b8650505-c7ee-4360-bba3-5adb00dc7b28.png)

![new_cpu_1](https://user-images.githubusercontent.com/13825585/154877558-6c83b47d-0b48-4dfd-9089-012fd064e2f9.png)

**Comment by dbwiddis** [comment]
OK, great.  And I think I now know what may have caused the problem; there was a different CPU ordering in the initial ticks vs. the real-time ticks. This resulted in some (impossible normally) negative values in the time difference calculations, which subsequently were amplified by the way the calculation was done.  And while this version gives you consistent ticks for the system, the per-processor index now probably doesn't match the actual index (which has been a long-standing bug that nobody has noticed).
