### ISSUE TITLE
CPU utilization

### ISSUE THREAD

**Issue by Jiangyongqiang** [oshi/oshi#1948]
Hello, Daniel. Thank you for your help。 I asked a question about CPU utilization: https://github.com/oshi/oshi/issues/1936 At first, it seemed to be accurate, but I started a scheduled task to get the CPU utilization regularly. After a long time (about a day), the usage became negative. According to the ticks, it was idle and the ticks was negative. What's going on?
![0226](https://user-images.githubusercontent.com/13825585/155823484-283365de-6468-4387-b5cf-1c97bbcf65a1.png)
@dbwiddis

**Comment by dbwiddis** [comment]
The way I calculated it is by taking a baseline immediately on startup and then using the "percent utility" since that time.  I suspect there's a limit to the precision of that calculation after a very long period of time.

I'll have to re-work it to periodically update the base

**Comment by dbwiddis** [comment]
OK, please test the latest snapshot. I think I've fixed this once and for all.

**Comment by dbwiddis** [comment]
Complication.  Refreshing the ticks doesn't work seamlessly as there are lots of accumulated offsets accounted for over time.  I'd need to update not only the base ticks but the saved offsets as reported to users.  That introduces another complication in that it relies on saving not only the base but the last reported (to user) offset (which could, in theory, become the new base).    This is fine if we can rely on users refreshing regularly, but fails in the edge case where a user initializes the CentralProcessor object, and then doesn't bother to query ticks for >19 hours.

Quick fix: moved storing the initial ticks into a memoized object in WindowsCentralProcessor.  This means that the user can control the refreshing: specifically, they would have to use a new SystemInfo object at least once every 19 hours in order to refresh that initial calculation; but they would be able to time it at their convenience.  In the case where a user is querying ticks every second (or any time period less than 19 hours), this seems like an easy solution.  

Alternate fix with a sanity check is still a theoretically possibility, counting the number of base counter wraps.  It introduces more complex code; we either sanity check every loop which, or store a "numberOfWraps" monotonically increasing variable and make sure it's thread-safe.  I think I can do this, but testing it will be a challenge as I'd have to keep an instance of OSHI running over 19 hours to confirm it works.  

Another option is to ignore the counter base and calculate a fixed ratio from elapsed time. This was my initial approach when I started these experiments.  It suffers from the same edge case situation as storing the last counter query; doesn't handle the case where no ticks are collected for 19 hours.

I'm leaning toward the quick fix.  Given this capability (matching Task Manager) is already an optional configurable property that requires users to take a few extra actions to enable it, this seems reasonable to require.  This is a clear shortcoming of the Windows counters involved, and if there needs to be a workaround for this, documenting the limitation and the solution seems better than trying to handle strange edge cases without really being able to effectively test them.

**Comment by dbwiddis** [comment]
Oops, miscalculated by a factor of 10.  It increments 625000 per second.  So the counter rolls over every 115 minutes.

Good news, a fix is more easily tested....

**Comment by dbwiddis** [comment]
It's impossible to handle all edge cases, particularly "remain idle for >2 hours and then collect ticks".  But after #1950 I think this is about as good as it's going to get.  SNAPSHOT available for testing.
