### ISSUE TITLE
In the docker container, oshi gets cpu information will be blocked

### ISSUE THREAD

**Issue by conghuhu** [oshi/oshi#2019]
![image](https://user-images.githubusercontent.com/56248584/164884012-c453680d-d62e-4b09-93b3-2db8ed58de88.png)
My springboot application is deployed in a docker container. Calling the cpu api as shown in the figure below cannot obtain information, and it will be blocked all the time, as shown in the above figure.
![image](https://user-images.githubusercontent.com/56248584/164884055-47fc42d0-9b83-47a6-881a-548b947f9849.png)

After testing, it is possible to obtain memory information and obtain jvm information, and hope to get a reply.

**Comment by dbwiddis** [comment]
Which operating system is the container running on?

Does the container have access to procfs or have an alternate in-container location for the equivalent of the `/proc` directory?

**Comment by conghuhu** [comment]
Docker is deployed on centos, and the base image of the container is openjdk:8-jre-alpine.
The project is a springboot, so should I change the base image in the dockerfile to centos or ubuntu?
Thank you again.


| |
丛国庆
|
|
***@***.***
|
On 4/23/2022 15:09，Daniel ***@***.***> wrote：

Which operating system is the container running on?

Does the container have access to procfs or have an alternate in-container location for the equivalent of the /proc directory?

**Comment by dbwiddis** [comment]
Can you see the contents of `/proc/stat` from inside the container?

**Comment by dbwiddis** [comment]
There is not enough information in your post for me to diagnose the problem.
 - The top image appears to show a synchronization thread triggering every 5 seconds, and two log messages from an attempt to get CPU information, with only the first of the two log messages shown
 - This implies the CPU information thread is terminating somewhere in the code snippet shown
 - The only possibility inside the thread would be a hang/delay/error executing `getSystemCpuLoadTicks()` 
   - The code for this on Linux simply reads the contents of `/proc/stat` and parses it
 - The other possibility is that the thread is being terminated from outside by the application, possibly due to the internal 1000 ms delay in your code

Suggestion: don't use code with an internal delay.  Just return the raw tick values to your springboot application and do the usage calculations there.

**Comment by dbwiddis** [comment]
Heh @conghuhu, haven't heard back from you so I'm going to assume this is resolved and close this issue.

I researched enough to know that springboot does include default timeouts and it's not waiting for you do delay as long as you do before responding to the query.  As mentioned in the previous comment, you should immediately return the raw tick values, and your base application should compare them to an older returned set to do the calculation.

Feel free to reopen this issue if you need more help.

**Comment by conghuhu** [comment]
OK, thank you very much for your answer


| |
丛国庆
|
|
***@***.***
|
---- Replied Message ----
| From | Daniel ***@***.***> |
| Date | 5/15/2022 00:10 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [oshi/oshi] In the docker container, oshi gets cpu information will be blocked (Issue #2019) |

Closed #2019.
