### ISSUE TITLE
Why change the name of device mounted to root into "/"?

### ISSUE THREAD

**Issue by banjiaojuhao** [oshi/oshi#2030]
https://github.com/oshi/oshi/blob/a820f5501d47fdbb8d4dcb2768b549e2e362587f/oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java#L147-L149

Why change the name of device mounted to root into "/"? It makes the format of root device's name different from other device.
It's easy for user to change the name to "/" but difficult to change back to "/dev/xxx".

```java
List<NodeState.DiskUsage> diskUsageList = new LinkedList<>();
for (OSFileStore fs : fileSystem.getFileStores()) {
    diskUsageList.add(DiskUsage.newBuilder()
            .setDevice(fs.getName())
            .setAvailableSpace(fs.getFreeSpace())
            .setTotalSpace(fs.getTotalSpace())
            .setMountPoint(fs.getMount())
            .build());
}
```

**Comment by dbwiddis** [comment]
Well the "why" is for historical reasons. It was there when the file stores were first implemented and only had the name, description, and usable/total space.  Without path or mount point components that was probably appropriate then.

I think it makes sense to leave it alone since we now include the path and users could make this same change in their own code.

Since changing this behavior could "break" some user implementations, I'd at least like to keep this issue open for a bit for feedback before changing this.

**Comment by dbwiddis** [comment]
FYI: I plan to do a minor version bump (6.2.0) with the next JNA release (5.12.0) because of the significant performance improvements I expect.   I'll include this change with that bump. In the mean time, this issue will be open and pinned for any feedback.

**Comment by dbwiddis** [comment]
So, I started doing this today, and realized that when not changed to the `path`, the `name` field is otherwise set to the `volume`.  So it is already easily available to you with `getVolume()` rather than `getName()`.

So I'm now leaning toward leaving this alone.  "Name" shouldn't be relied on to have any particular format, while path and volume have specific meanings in the filesystem.

**Comment by dbwiddis** [comment]
Of note, the Unix variants all just use the last name in the path as the name, e.g., for `/dev/xxx` the name would be `xxx`.  Not sure if this is more or less helpful than the path (`/`) or volume (`/dev/xxx`), but adds on to the point that "name" might not be the best idea to use for matching filesystem paths.

**Comment by banjiaojuhao** [comment]
Agree! That's more accurate.

**Comment by banjiaojuhao** [comment]
Agree! That's more accurate.
