### ISSUE TITLE
Getting NULL/Unknown/Empty values for some data

### ISSUE THREAD

**Issue by DeepsUttekar** [oshi/oshi#2139]
Hello team,

I have integrated Oshi library in my JAVA application. This application is running only on Windows operating system.

I have used following functionality to get hardware information from Windows OS.
```java
SystemInfo systemInfo = new oshi.SystemInfo();
OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();
CentralProcessor centralProcessor = hardwareAbstractionLayer.getProcessor();
ComputerSystem computerSystem = hardwareAbstractionLayer.getComputerSystem();
List<HWDiskStore> stores = hardwareAbstractionLayer.getDiskStores();
String vendor = operatingSystem.getManufacturer();
String processorSerialNumber = computerSystem.getSerialNumber();
String processorIdentifier = centralProcessor.getProcessorIdentifier().getIdentifier();
-------------
private static String getHddSerialNumber(List<HWDiskStore> stores) {
  for (HWDiskStore store : stores) {
	  if (store != null)
		  return store.getSerial();
  }
return null;
}
```
On one of the machine. I used to get proper values for all above parameters. But then all of a sudden I started getting NULL and Unknown values for 
processorSerialNumber: unknown  
HddSerialNumber: null  

Can you please help me to understand why this can happen? 
What can be possible reasons to get null/unknown values?
Steps to recover from this issue?

**Comment by dbwiddis** [comment]
OSHI fetches the system serial number on Windows from `IdentifyingNumber` field in the WMI table [`Win32_ComputerSystemProduct`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystemproduct).

What result do you see from the following command line?
```
wmic path Win32_ComputerSystemProduct get IdentifyingNumber
```
Similarly hard drive serial number comes from the `SerialNumber` field in [`Win32_DiskDrive`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-diskdrive). What does this command line return?
```
wmic path Win32_DiskDrive get Name,SerialNumber
```
I suspect you have [a problem with your WMI setup.](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-troubleshooting)  If either of the above queries returns an error code, it may help you diagnose the problem.

**Comment by DeepsUttekar** [comment]
Hello, Thank you for help. I will check of above wmi commands work on the machine or not.

Meantime I was trying to evaluate WMI Diagnostic tool, but its notw supported since Windows 7. So is there any other alternative to diagnose problems with WMI setup?

Also on few links, I read about error handling or retrieving error reasons for Oshi library's null/unknown values. But I didn't find any documentation to implement and use it. Is ot possible for you to share an example for error handling code

**Comment by dbwiddis** [comment]
OSHI has adopted a position of "graceful failure" rather than exceptions for most of its outputs.  When users have requested, some capability has been added for error handling objects in drivers.  More can be added if the community wants to contribute.

The WMI Query Handler class is an example.   If you don't like the way WMI errors are handled you can override the methods in that class, and then use its `setInstanceClass()` method with your custom subclass.  While not associated with error handling, this capability gives an example of the process in `oshi-demo`.  The [WmiNoComInitQueryHandler](https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/WmiNoComInitQueryHandler.java) subclass overrides the `initCom()` method.  And the `UserComInit` class there shows how it is used in code:
https://github.com/oshi/oshi/blob/9935393e193644319516ce8477c2d062489fd1dc/oshi-demo/src/main/java/oshi/demo/UserComInit.java#L75
