### ISSUE TITLE
Better handling of ARM CPU Names

### ISSUE THREAD

**Issue by NVShawn** [oshi/oshi#2163]
When running oshi's tests on an ARM box, I get nothing for 'cpuName'. Intel processors give something like this: `Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz`

I realize this is because Intel gives the full string of information and that ARM does not, but there is enough information out there to start to fill in the gaps at least. For example, we can get the implementor of the chip using public information like here: https://developer.arm.com/documentation/ddi0595/2021-06/External-Registers/MIDR-EL1--Main-ID-Register . There may be other places or ways to build up this information so there is something better than nothing for ARM cpu names.

**Comment by dbwiddis** [comment]
Hey @NVShawn, thanks for this report.

OSHI does obtain some of that ARM information.  If you look at the source code of the `queryProcessorId()` method in `LinuxCentralProcessor` you'll see some of those.

The "CPU Name" comes from either the "Processor" or "model name" field in `/proc/cpuinfo`:
https://github.com/oshi/oshi/blob/c261bf88088d1b4f621d9fa3eda3685989782b97/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L103-L106

This should parse a line like this into an appropriate name string:
```
cat /proc/cpuinfo 
Processor	: ARMv7 Processor rev 5 (v7l)
```
Additionally, the MIDR info is present:

Implementer is mapped to vendor:
https://github.com/oshi/oshi/blob/c261bf88088d1b4f621d9fa3eda3685989782b97/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L99-L102

Variant and Revision are mapped to stepping:
https://github.com/oshi/oshi/blob/c261bf88088d1b4f621d9fa3eda3685989782b97/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L119-L128

PartNum is mapped to Model:
https://github.com/oshi/oshi/blob/c261bf88088d1b4f621d9fa3eda3685989782b97/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L129-L132

And there is an attempt to create a MIDR which is reported in the ProcessorID field:
https://github.com/oshi/oshi/blob/c261bf88088d1b4f621d9fa3eda3685989782b97/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L493-L511

I realize that the documentation may not be as clear on this, with a hand-wavy "non-Intel equivalent" statement, because I don't have ARM hardware to develop and test on.  If you'd like to submit a PR to update how OSHI parses this info, or suggest improvements in the documentation, I'd be happy to update those.

**Comment by NVShawn** [comment]
Makes sense. I'll see what I can do to implement some of this in code to make it read better.

**Comment by dbwiddis** [comment]
Excellent. Since the "CPU Name" field is blank, can you post your `/proc/cpuinfo` output and point to a line which should include this information (assuming there is none which says "Processor")?

**Comment by NVShawn** [comment]
```
processor       : 0
BogoMIPS        : 243.75
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
```

This is for a Gravaton2 CPU. Pulling the implementer and part, it shows up as an `ARM Neoverse-N1` which is easier to read but not accurate. `dmidecode -t 4` you can get `AWS Graviton2` if you guess the right field to check, but that only works as root.

**Comment by dbwiddis** [comment]
> This is for a Gravaton2 CPU. Pulling the implementer and part, it shows up as an `ARM Neoverse-N1` which is easier to read but not accurate. `dmidecode -t 4` you can get `AWS Graviton2` if you guess the right field to check, but that only works as root.

Yeah, I was peeking into Linux source code trying to find a consistent field and see the ones you've listed.

You could do similar to how we do ComputerSystem/Baseboard processing and check `hwinfo --cpu` (installed by default and non-root, I think) or `lshw` outputs.

**Comment by NVShawn** [comment]
`hwinfo --cpu` is not installed by default on the box I was using, and gives about what `/proc/cpuinfo` gives. `lshw -C cpu` gives good info, but only when run as root.

**Comment by NVShawn** [comment]
Looks like `lshw` is using DMI information, which is only available via root.

**Comment by dbwiddis** [comment]
Out of desperation, is `dmesg` helpful at all? 😀

**Comment by dbwiddis** [comment]
Hey @NVShawn just checking in. Were you ever able to find any more information on your system without root privs?  Anything I can change on OSHI's side here?

**Comment by NVShawn** [comment]
Nothing concrete yet. To be fair, this has fallen to the wayside at the moment and I likely won't get a chance to look into it for a few weeks.

**Comment by dbwiddis** [comment]
`/proc/device-tree/model` looks helpful.
