### ISSUE TITLE
OSHI process list is empty -  OSHI output (processes): {}

### ISSUE THREAD

**Issue by atyuhapal** [oshi/oshi#2274]
Hi Team
This is for Windows 2016 environment
tested version -  OSHIv6.1.6 OSHIv6.2.2

In our code we print below info when debug log is enabled

**SNIPPET**

 if (log.isDebugEnabled()) {
            log.debug("OSHI output (processes): " + rawData.getProcesses());
            log.debug("OSHI output (perfProcesses): " + rawData.getPerfProcesses());
            String cacheStr = oshiOsProcessCache.size() > 0 ? oshiOsProcessCache.asMap().keySet().toString() : "empty";
            log.debug("OSHI OSProcess cache: " + cacheStr);
        }

**Below is always empty in our log**

OSHI output (processes): {}
OSHI output (perfProcesses): {}

Tried to run the below query  as OSHI used below WMI query to fetch the process related data.

** Query output** 

Get-CimInstance : Invalid class
At line:1 char:1
+ Get-CimInstance -Query "Select * FROM Win32_PerfRawData_PerfProc_Proc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : MetadataError: (:) [Get-CimInstance], CimException
+ FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

Any help on this is highly appreciated.

Kind Regards,
Atyuha

**Comment by dbwiddis** [comment]
This looks like a similar report as #2273 and the same comments apply.

OSHI gets its process information from the Windows Performance Counters. The system is not providing access to the performance counters.  

What you are seeing in OSHI is just a symptom; the underlying problem is with your performance counter and/or WMI setup. This requires debugging at the Windows level, and I really have no expertise there.  Searching the 0x80041010 error code reveals several possible causes and potential solutions.

**Comment by dbwiddis** [comment]
Hey @atyuhapal have you had any success debugging this?
