### ISSUE TITLE
Add support for TcpStats.getConnectionsCloseWait()

### ISSUE THREAD

**Issue by hamadaCA** [oshi/oshi#2296]
TcpStats lacks support for connections in CLOSE_WAIT state

**Comment by hamadaCA** [comment]
TcpStats does not expose api to to get connections that are in CLOSE_WAIT.


        /**
         * Connections Established is the number of TCP connections for which the current state is either ESTABLISHED or
         * CLOSE-WAIT
         *
         * @return the connectionsEstablished
         */
        public long getConnectionsEstablished() {
            return connectionsEstablished;
        }

**Comment by dbwiddis** [comment]
OK, I see the documentation mismatch and perhaps that should be fixed. 

But you should still be able to query a list of connections with `getConnections()` and filter it yourself.

**Comment by hamadaCA** [comment]
Thanks, that would work if TcpState was not package protected, so it is not accessible to the app.
 Additionally, and IMHO, I think adding a method is most optimal for a state snapshot.

**Comment by dbwiddis** [comment]
> Thanks, that would work if TcpState was not package protected, so it is not accessible to the app. 

It's on an interface so it's public by default.  Unless I'm missing something?

> Additionally, and IMHO, I think adding a method is most optimal for a state snapshot.

The best snapshot grabs all the information at once from the whole system so that it's consistent.  That is what the `getConnections()` call does (querying `netstat -n`).  The `connectionsEstablished()` and other calls on `TcpStats` are protocol-dependent netstat calls, so reasonably close to at the same time (and connections aren't going to switch protocols) and consistent.

Digging into the implementations it looks like we just don't have the data on Windows where we fetch using `GetTcpStatisticsEx` and GetUdpStatisticsEx` which return `MIB_TCPSTATS` or `MIB_UDPSTATS`, respectively.  Those don't differentiate close-wait (and are probably the source of the javadoc disclaimer).  We could always just make that "includes close-wait" a Windows caveat and expose the values for the unix-based OS's.

I'd welcome a PR if you'd like to add this.

**Comment by hamadaCA** [comment]
> It's on an interface so it's public by default. Unless I'm missing something?
My bad, IDE misled!
For the short term I will rely on getConnections(). as for a PR, I will try to get to it in mid term, I may lean on you when it comes to windows related changes.
