### ISSUE TITLE
osProcess class for fetching process data in batches

### ISSUE THREAD

**Issue by darshanh** [oshi/oshi#2350]
like "osProcess.getCommandLine() " does oshi support request in batch? if there is a way can you please help on the same .Currently we are fetching the process related data individually , the requirement is to send the request or fetch the data in batch

**Comment by dbwiddis** [comment]
> like "osProcess.getCommandLine() " does oshi support request in batch? 

Option 1: See the docs: https://github.com/oshi/oshi/blob/master/src/site/markdown/Performance.md#windows-process-command-lines

If you set `GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_COMMANDLINE_BATCH, true)` at startup or in a config file, then OSHI will fetch command lines in batch behind the scenes, and each `getCommandLine()` will pull from the cache.

Option 2: Use the source, Luke:

```java
// If using batch mode fetch from WMI Cache
if (USE_BATCH_COMMANDLINE) {
    return Win32ProcessCached.getInstance().getCommandLine(getProcessID(), getStartTime());
}
```

**Comment by darshanh** [comment]
Both the option 1 and 2  does the same? Because we are already using GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_COMMANDLINE_BATCH, true) in our code , we are setting it in the constructor . But still we are seeing the performance issues. Please suggest what else we can do to tune the same

**Comment by dbwiddis** [comment]
> Both the option 1 and 2 does the same? 

Yes, option 1 sets the conditional that is in the code branch in option 2.  It's the actual cached/batch request.

> Because we are already using GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_COMMANDLINE_BATCH, true) in our code , we are setting it in the constructor . 

Assuming you're setting it before accessing any OSHI classes that should work.

> But still we are seeing the performance issues. 

Can you please be more specific? How have you traced these to the command line getters?

> Please suggest what else we can do to tune the same

I would suggest not fetching command lines at all.  You already have the program name.  I suspect nobody ever even looks at 99% of the command lines that get fetched.

**Comment by darshanh** [comment]
I am posting the snippet for your Reference please suggest if any change need to done  :
[Snippet.docx](https://github.com/oshi/oshi/files/11207370/Snippet.docx)
 We are actually using command line information for fetching processes class info  . It is actually required as we do some processing on that data

**Comment by dbwiddis** [comment]
It would have been easier to just copy the code here into markdown than to take a screencap and embed it in a word document. :)

I don't see any reference in that snippet to command lines.  The code looks a lot like #2325, but without the getCommandLine() calls, so the global setting doesn't matter in this case... but maybe you're fetching it outside of what you're showing in that snippet.

I understand you need the command lines for at least some processes.  Note that even with caching, if there are any "new" processes since the previous query it will still fetch the whole process list from WMI to update any.   Is there any way to restrict your command line query by some other feature of the processes for which you need the classes?  Process name?  Parent PID?  Owner?  

Everything other than command lines for processes should be really fast.  Even command lines can be fast if fetching from process memory (which happens for processes owned by the same user, and possibly other non-system processes if you're running as admnistrator).

**Comment by darshanh** [comment]
let me know if we can connect over a call ?

**Comment by dbwiddis** [comment]
> let me know if we can connect over a call ?

I generally try to keep all open-source project related communications in the open.  

I've explained how to get command lines in batch per your earlier question. The source is available (and even linked in this thread) for you to further investigate how it's done.  If there is a more specific question than what's been asked, please ask it.
