### ISSUE TITLE
why have this?

### ISSUE THREAD

**Issue by xiaowine** [oshi/oshi#2402]
I just introduced the library and initialized SystemInfo, and the console outputs
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
Although it does not affect the operation of the program, it is very annoying

**Comment by dbwiddis** [comment]
See #1753

OSHI has the SLF4J API as a dependency.  You are required to supply your own logging implementation as a dependency.
1. If you don't need logging, use the no-op logger as the error message indicates and suggests a link.  Simply add a dependency to `slf4j-nop.jar` and the message will go away.
2. OSHI's test framework uses the simple logger, `slf4j-simple` which is a good option for basic logging.
3. Otherwise, use a logger for log4j, or logback, or reload4j, or java util logging, etc.

**Comment by xiaowine** [comment]
> See #1753 见#1753
> 
> OSHI has the SLF4J API as a dependency. You are required to supply your own logging implementation as a dependency.OSHI将SLF4J API作为依赖项。您需要提供自己的日志记录实现作为依赖项。
> 
> 1. If you don't need logging, use the no-op logger as the error message indicates and suggests a link.  Simply add a dependency to `slf4j-nop.jar` and the message will go away.如果不需要日志记录，请使用无操作记录器，因为错误消息指示并建议链接。只需将依赖项添加到 `slf4j-nop.jar` ，消息就会消失。
> 2. OSHI's test framework uses the simple logger, `slf4j-simple` which is a good option for basic logging.OSHI 的测试框架使用简单的记录器， `slf4j-simple` 是基本日志记录的不错选择。
> 3. Otherwise, use a logger for log4j, or logback, or reload4j, or java util logging, etc.否则，使用记录器进行log4j，或logback，或reload4j，或java util logging等。

Ok, it's been worked out
