### ISSUE TITLE
03000200-0400-0500-0006-000700080009 computerSystem hardwareUUID

### ISSUE THREAD

**Issue by ctadlock** [oshi/oshi#2417]
The UID `03000200-0400-0500-0006-000700080009` is a known default UID for several motherboards. It should be excluded from the logic for `hardware.computerSystem.hardwareUUID` generation. While youre at it also worth excluding `FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF` as we have seen that come up as well.

- https://arstechnica.com/civis/threads/uuid-you-keep-using-that-word-i-do-not-think-it-means-what-you-think-it-means.1491688/
- https://www.reddit.com/r/talesfromtechsupport/comments/6n1y30/with_cheap_manufacturingnothing_is_impossible/

**Comment by dbwiddis** [comment]
Hey @ctadlock, thanks for this report, although I'm not sure its our place as a reporting library to try to censor these out. 

It's entirely possible that someone may want to find such servers in order to "fix" the problem and avoid future software deployment issues, so they would need to be able to find impacted servers with such non-unique ID's.

Certainly these known-bad IDs could be added to a filter in the oshi-demo `ComputerId` class similarly to how lack of serial number is handled (and I suspect there's some overlap there), but I'm leaning against faithfully relaying information from the operating system or hardware to the user and letting them choose to handle it appropriately.

Any other maintainers have thoughts on this?

**Comment by ctadlock** [comment]
> Hey @ctadlock, thanks for this report, although I'm not sure its our place as a reporting library to try to censor these out.
> 
> It's entirely possible that someone may want to find such servers in order to "fix" the problem and avoid future software deployment issues, so they would need to be able to find impacted servers with such non-unique ID's.
> 
> Certainly these known-bad IDs could be added to a filter in the oshi-demo `ComputerId` class similarly to how lack of serial number is handled (and I suspect there's some overlap there), but I'm leaning strongly in favor of faithfully relaying information from the operating system or hardware to the user and letting them choose to handle it appropriately.
> 
> Any other maintainers have thoughts on this?

Good point. We have a whole framework on top of Oshi to deal with what we consider "bad" data. Other apps might have a different definition of "bad".

**Comment by dbwiddis** [comment]
Great. I did update the oshi-demo sample for a Computer ID (which I don't think is a good idea but seems one of the most-asked-for features ¯\\\_(ツ)\_/¯).

On a related note, lots of people still think CPUID is a unique identifier. 😁
