### ISSUE TITLE
Travis CI builds have stopped

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2423]
I noticed today we haven't had any Travis builds for 6 months.   Our only build was on an ARM machine which was free because it was sponsored by someone else; apparently that stopped and we somehow consumed all our free 10K credits.

We have two options:
 - request free credits https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source and repeat every time they run out
 - just delete that job and not deal with Travis CI any more.  We lose on-metal ARM builds (which haven't been working anyway) but there are plenty of free GCC Compile Farm machines we could leverage for those.

I favor the second option. Anyone else have thoughts?

**Comment by hazendaz** [comment]
Drop Travis.  Not OSS friendly anymore.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Daniel Widdis ***@***.***>
Sent: Tuesday, August 1, 2023 12:23:46 PM
To: oshi/oshi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oshi/oshi] Travis CI builds have stopped (Issue #2423)


I noticed today we haven't had any Travis builds for 6 months. Our only build was on an ARM machine which was free because it was sponsored by someone else; apparently that stopped and we somehow consumed all our free 10K credits.

We have two options:

  *   request free credits https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source and repeat every time they run out
  *   just delete that job and not deal with Travis CI any more. We lose on-metal ARM builds (which haven't been working anyway) but there are plenty of free GCC Compile Farm machines we could leverage for those.

I favor the second option. Anyone else have thoughts?
