### ISSUE TITLE
The result of OSProcess#getThreadDetails() in WindowsOSProcess implementation is allways empty array.

### ISSUE THREAD

**Issue by tzfun** [oshi/oshi#2432]
Version: 6.4.4

Wrong code location: WindowsOSProcess line 275
![image](https://github.com/oshi/oshi/assets/34815354/33c71b51-bad8-48a3-856d-0153b8b299e1)

Reason: The threds is got by buildThreadMapFromRegistery, and its not null. So there is no need to build from perf counters at this time.

Correct code: 

```java

        // Get data from the registry if possible
        Map<Integer, ThreadPerformanceData.PerfCounterBlock> threads = ThreadPerformanceData
                .buildThreadMapFromRegistry(Collections.singleton(getProcessID()));

        // otherwise performance counters with WMI backup
        if (threads == null) {
            threads = ThreadPerformanceData.buildThreadMapFromPerfCounters(Collections.singleton(this.getProcessID()));
        }

```

**Comment by dbwiddis** [comment]
Nice catch... can you submit a PR to fix it?

**Comment by dbwiddis** [comment]
Also, even if that branch is incorrect, OSHI should still be using the performance counters or WMI backup, so that switched boolean check doesn't explain the empty array.

**Comment by tzfun** [comment]
> Also, even if that branch is incorrect, OSHI should still be using the performance counters or WMI backup, so that switched boolean check doesn't explain the empty array.

Yes, later I also found out that there is no need to check for null

**Comment by dbwiddis** [comment]
The `buildThreadMapFromRegistry()` method can return null in some cases.  So the first check should be for null.  The second would be an empty map but it's not necessary as the empty set iteration would just get there anyway.

So that's an easy fix. But the problem is the current code is always checking the perf counters and they are returning an empty list.  So there's something wrong with that code.
