### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem

### ISSUE THREAD

**Issue by 1ssqq1lxr** [oshi/oshi#2448]
Running in Docker, the built dependency image is openjdk: 8-jre lpine. How can I solve this error using oshi core 6.4.0

**Comment by mprins** [comment]
please try the current release, various fixes regarding this message have been resolved, see https://github.com/oshi/oshi/issues?q=Could+not+initialize+class

please also check the [FAQ](https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md) and report back what you tried and provide more information to diagnose your problem

**Comment by dbwiddis** [comment]
As @mprins indicated, check the FAQ. A common problem in containers is lack of libudev.  Latest version stack trace/error message should direct you to a solution.  

Closing this due to lack of response to initial questions. Feel free to re-open if using updated version and/or checking the FAQ doesn't resolve your issue.
