### ISSUE TITLE
HWDiskStore stats and partitions don't work for CoreStorage (FileVault or Fusion Drives) on Mac OS

### ISSUE THREAD

**Issue by MathiasExner** [oshi/oshi#250]
Using Mac OS (Version 10.11.6), the function oshi.hardware.HWDiskStore#getTimeStamp always returns a value of '0'.

As an alternative if the correct value is indeterminable it would in my opinion be sufficient to use the system time on creating the 'oshi.hardware.HWDiskStore' instance.

**Comment by dbwiddis** [comment]
Odd... I have the same version and it returns `System.currentTimeMillis()` for me, which is the value set in the code.  I don't see how it would have a 0 timestamp unless all the other statistics are also 0 because it failed to find information in the registry.

**Comment by MathiasExner** [comment]
This is the content of the object:

![bildschirmfoto 2016-08-22 um 16 35 14](https://cloud.githubusercontent.com/assets/21168033/17858605/a2071060-6886-11e6-89d2-e82fc5f750b1.png)

I have a MacBook Pro (Retina, 15', Mitte 2015)

**Comment by dbwiddis** [comment]
The timestamp is associated with the reads/writes which also appear to be zero.  It looks like OSHI is not finding the statistics in the registry for that disk.  

Can you give me the output of the 'diskutil' command?

**Comment by MathiasExner** [comment]
Certainly :)

```
athena:Utilities mathias$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            999.7 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           +999.3 GB   disk1
                                 Logical Volume on disk0s2
                                 FA33A826-C98E-425A-BCF1-9A68A926D36E
                                 Unlocked Encrypted
```

```
athena:Utilities mathias$ diskutil info disk0
   Device Identifier:        disk0
   Device Node:              /dev/disk0
   Whole:                    Yes
   Part of Whole:            disk0
   Device / Media Name:      APPLE SSD SM1024G

   Volume Name:              Not applicable (no file system)

   Mounted:                  Not applicable (no file system)

   File System:              None

   Content (IOContent):      GUID_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 PCI
   SMART Status:             Verified

   Total Size:               1.0 TB (1000555581440 Bytes) (exactly 1954210120 512-Byte-Units)
   Volume Free Space:        Not applicable (no file system)
   Device Block Size:        512 Bytes

   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

   Device Location:          Internal
   Removable Media:          No

   Solid State:              Yes
   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported
```

**Comment by dbwiddis** [comment]
What is the difference between Disk1 and Disk0?  They both seem to be mounted at disk0s2.  OSHI is returning the stats/timestamp for that volume under disk0 (assuming partition #2).

**Comment by MathiasExner** [comment]
Ah, good question. This mac only has one physical disk. Maybe this has something to do with macs fusion drive technology?

> Apple's implementation combines a hard disk drive with a NAND flash storage (solid-state drive of 24 GB or more) and presents it as a single Core Storage managed logical volume with the space of both drives combined.

https://en.wikipedia.org/wiki/Fusion_Drive

**Comment by dbwiddis** [comment]
Does OSHI give you the stats on disk0?  Essentially we can get stats for "disk0s2" so the question is where to display them.  Not sure we should double count them. 

I see it also calls disk1 "virtual"...

**Comment by dbwiddis** [comment]
Closing the loop on this... traveling with limited internet connectivity so I'll try to have a more verbose reply here.

OSHI uses `statfs()` to find mounted file systems.  This may or may not be the same list as returnd by either `mount` or `df`.  In either case it looks for /dev/disk* mounts for further parsing.

And that's where it may be running into trouble with your fusion drive.  While the physical drive is disk0, if it's not mounted, it may not show up in oshi, while disk1 does.  But disk1 is mounted on disk0s2 rather than the expected disk1s2.

If the stats are actually available for you under disk0, we need to figure out how we want to represent the virtual drive, or exclude disk1, etc. if it doesn't have the s2 partition.

If you don't have stats for disk0, then we'll have to grok your registry to find them.  The ioreg commandline or, better, the IORegistryExplorer gui, can help locate them (Oshi looks for an IOMedia object matching that bsdname (e.g., disk1), finds its parent in the IOService plane, verifies it's an IOBlockStorageDriver, and then looks for the "Statistics" element in that dictionary.   I have no idea how that sequence will work on your system.

**Comment by dbwiddis** [comment]
@MathiasExner I need a bit more information from you to see if there's anything I can address on this issue.  Does OSHI give you the stats (reads, writes, etc.) for disk0?  Or does it only show you disk1 with no stats?

**Comment by MathiasExner** [comment]
@dbwiddis Sorry, was occupied with other business last week. HardwareAbstractionLayer#getDiskStores does only return disk1 and diskStore#getReadByte and diskStore#getWriteBytes always returns 0.
As I get no instance of HWDiskStore für disk0 I have no stats for it.

**Comment by MathiasExner** [comment]
IORegistryExplorer gives me the following results:

![bildschirmfoto 2016-08-29 um 10 21 26](https://cloud.githubusercontent.com/assets/21168033/18045284/6eb87054-6dd2-11e6-9d09-fdfaec799fa5.png)

So there is only an IOMedia for disk0, but the statistics are there:

![bildschirmfoto 2016-08-29 um 10 22 39](https://cloud.githubusercontent.com/assets/21168033/18045306/88d9ea1c-6dd2-11e6-96b6-0fdfa691e600.png)

**Comment by dbwiddis** [comment]
OK... that's what I was afraid of.

OSHI is failing in the step of matching an IOService search (returning an IOMedia object) for the BSD name (in your case, `disk1`) when it needs to find the one you've highlighted above (which is `disk0`).  Once we crack that nut, the stats (and partitions!) should just work.

The question here is how we can tell OSHI to look in disk0.  Somewhere in the sequence OS X knows that disk 1 is a "Logical Volume on disk0s2" and I need to know how to figure that out programmatically.

Digging into the code... OSHI currently looks for mounted file systems using fsstat (probably the same as the `mount` command) and looks up from there.  

But looking at the `iostat` source code, it instead searches for all IOMedia devices (with media whole = true).  That's probably a better thing for OSHI to do.  We'll at least find your disk0 and its stats/partitions.   The only piece we will be missing is the Mount Point for the partition (Going this direction we'd get the `/dev/disk0s2` but wouldn't know that it's mounted at `/dev/disk1`.)

Can you show me the output of the `mount` and `df` commands on your system?  It could be that I have that information already from the `getfsstat()` call, but make assumptions instead of using it...

**Comment by MathiasExner** [comment]
athena:~ mathias$ mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
localhost:/9-_93vXOh3oB8oeFOs1X_w on /Volumes/MobileBackups (mtmfs, nosuid, read-only, nobrowse)
athena:~ mathias$ df
Filesystem                        512-blocks       Used  Available Capacity  iused     ifree %iused  Mounted on
/dev/disk1                        1951825920  575057552 1376256368    30% 71946192 172032046   29%   /
devfs                                    362        362          0   100%      627         0  100%   /dev
map -hosts                                 0          0          0   100%        0         0  100%   /net
map auto_home                              0          0          0   100%        0         0  100%   /home
localhost:/9-_93vXOh3oB8oeFOs1X_w 1951825920 1951825920          0   100%        0         0  100%   /Volumes/MobileBackups

**Comment by dbwiddis** [comment]
Awesome, thanks.

I've just committed a change to SNAPSHOT that iterates over IOMedia "whole" drives in the registry rather than just getting mount points.  This should give you some of the stats you need.  

I expect it will properly display stats for disk0.  Not sure if it will show your disk1, however, or the linkage of disk1 to disk0s2 as shown in `diskutil list`.

Let me know how it works out and if you have any ideas on where to go next...

**Comment by dbwiddis** [comment]
Making slow progress here.  The Fusion Drive uses Apple's "Core Storage" functionality which is, alas poorly (if at all) documented.   This apparently also is needed for the new FileVault full-disk encryption system (since Lion) where the OS has access to the (encrypted) virtual drive, which is backed (via CoreStorage) by a hardware partition.

There's a `diskutil cs list` and `diskutil cs info <drive>` command line that probably will provide the info we need to parse.  (Yes, that's a request!)

**Comment by MathiasExner** [comment]
Quick feedback from our tool after updating to the recent oshi-snapshot:

![bildschirmfoto 2016-08-30 um 17 41 53](https://cloud.githubusercontent.com/assets/21168033/18096002/100fbe56-6ed9-11e6-99a9-0a97b3ff77d2.png)

disk0 has all statistics, disk1 is still there but has no statistics.

**Comment by MathiasExner** [comment]
Following is the requested output:

```
athena:~ mathias$ diskutil cs list
CoreStorage logical volume groups (1 found)
|
+-- Logical Volume Group 505BAE96-706A-4186-93DC-2AEA33A4325E
    =========================================================
    Name:         Macintosh HD
    Status:       Online
    Size:         999695822848 B (999.7 GB)
    Free Space:   4435968 B (4.4 MB)
    |
    +-< Physical Volume E264BB06-A4E4-4DDD-9D29-8D5DEDB87540
    |   ----------------------------------------------------
    |   Index:    0
    |   Disk:     disk0s2
    |   Status:   Online
    |   Size:     999695822848 B (999.7 GB)
    |
    +-> Logical Volume Family AE155E04-46F0-4013-8E75-12C6AA2EE944
        ----------------------------------------------------------
        Encryption Type:         AES-XTS
        Encryption Status:       Unlocked
        Conversion Status:       Complete
        High Level Queries:      Fully Secure
        |                        Passphrase Required
        |                        Accepts New Users
        |                        Has Visible Users
        |                        Has Volume Key
        |
        +-> Logical Volume FA33A826-C98E-425A-BCF1-9A68A926D36E
            ---------------------------------------------------
            Disk:                  disk1
            Status:                Online
            Size (Total):          999334871040 B (999.3 GB)
            Revertible:            Yes (unlock and decryption required)
            Revert Status:         Reboot required
            LV Name:               Macintosh HD
            Volume Name:           Macintosh HD
            Content Hint:          Apple_HFS
```

```
athena:~ mathias$ diskutil cs info disk0
disk0 is not a CoreStorage disk
```

```
athena:~ mathias$ diskutil cs info disk1
Core Storage Properties:
   Role:                       Logical Volume (LV)
   UUID:                       FA33A826-C98E-425A-BCF1-9A68A926D36E
   Parent LVF UUID:            AE155E04-46F0-4013-8E75-12C6AA2EE944
   Parent LVG UUID:            505BAE96-706A-4186-93DC-2AEA33A4325E
   Device Identifier:          disk1
   LV Status:                  Online
   Conversion State:           Complete
   LV Conversion Progress:     100%
   Content Hint:               Apple_HFS
   LV Name:                    Macintosh HD
   Volume Name:                Macintosh HD
   LV Size:                    999334871040 B
athena:~ mathias$ 
```

```
athena:~ mathias$ diskutil cs info disk0s2
Core Storage Properties:
   Role:                       Physical Volume (PV)
   UUID:                       E264BB06-A4E4-4DDD-9D29-8D5DEDB87540
   Parent LVG UUID:            505BAE96-706A-4186-93DC-2AEA33A4325E
   Device Identifier:          disk0s2
   PV Size:                    999695822848 B
   PV Status:                  Online
```

**Comment by dbwiddis** [comment]
OK!   I think we're closing in on something here.

Note: I'm not sure where you get the "mounted on" field in your display, since that comes from partitions, not disks, but I'll assume you will understand my partition-based solution.

What I plan to do is create a linkage from the partition (in your case, disk0s2) to the Logical Volume.  I'll iterate over `diskutil cs list` connecting the "Disk" underneath the "Physical Volume" header to the "Disk" underneath the "Logical Volume" header.  So in your case, the "mounted on" string for partition disk0s2 would read something like: "Logical Volume disk1".

Let me know if this is an acceptable solution or if you have any better ideas!

**Comment by dbwiddis** [comment]
So.... I had a spare USB drive laying around and encrypted it with FileVault, and now have a test case very similar to yours.  Enough that I'm pretty sure that it's FileVault creating what you're looking at, rather than Fusion Drive.   Although it's the same underlying technology.  The good news is I think I can stop asking you to run commands, and should be able to get a solid test in.

**Comment by dbwiddis** [comment]
Here's the test output for the current SNAPSHOT for my encrypted drive ... should work for you as well!  Note the stats are on the physical disk4, and the partition disk4s1 is one of possibly multiple partitions (in this case the only one) on the logical volume disk2, which has no stats.  But there's enough info there to correlate.

In the case of a fusion drive, both the SSD and HD portions would show up as separate partitions (with their own stats on the hardware) linked to the same logical volume, so the user would have to sum the stats for each individual portion of the drive to get the total logical volume stats.
```
Disks:
 disk2: (model: Flash Disk - S/N: ) size: 685.1 MB, reads: ? (?), writes: ? (?), xfer: ? ms
 |-- disk2: ILOG (ILOG) Maj:Min=1:6, size: 685.1 MB @ /Volumes/ILOG
 disk4: (model: Flash Disk - S/N: ) size: 1.1 GB, reads: 6371 (657.7 MiB), writes: 13413 (1.4 GiB), xfer: 131701136 ms
 |-- disk4s1: ILOG (ILOG) Maj:Min=1:11, size: 1.1 GB @ Logical Volume: disk2
```
