### ISSUE TITLE
Improvement: OSFileStore#getType additionally as enum

### ISSUE THREAD

**Issue by lundefugl** [oshi/oshi#252]
The function `getType` on `OSFileStore` returns a `String`.

I have seen on Windows:
- Fixed drive
- CD-ROM
- Removable drive
- Network drive

I think the `String` will be different on other platforms.
Is it possible to generate additionally a platform independent enum value of the types ?

In my case I will ignore all "Network drive"s and "CD-ROM"s on follow program steps.

**Comment by dbwiddis** [comment]
Windows does use an integer type for File Stores (see the [DriveType element here](https://msdn.microsoft.com/en-us/library/aa394173(v=vs.85).aspx).)  However, I modeled OSHI's FileStore object on the built-in Java [FileStore class](http://docs.oracle.com/javase/7/docs/api/java/nio/file/FileStore.html#type%28%29) which uses a `String` for the type and includes this notation in the javadoc: 

> Returns the type of this file store. The format of the string returned by this method is highly implementation specific. It may indicate, for example, the format used or if the file store is local or remote.

Swing's [FileSystemView.getSystemTypeDescription()](https://docs.oracle.com/javase/7/docs/api/javax/swing/filechooser/FileSystemView.html#getSystemTypeDescription(java.io.File)) method similarly returns a `String` for the drive type (e.g., CD-ROM).

As a cross-platform implementation, I strongly feel that OSHI should follow the JRE's lead here and maintain this field as a String.   I'm open to a convincing argument otherwise, if there is one.

**Comment by dbwiddis** [comment]
OpenJDK extends `FileStore` with `sun.nio.fs.WindowsFileStore`, `sun.nio.fs.LinuxFileStore`, and `sun.nio.fs.UnixFileStore` classes.  The Linux and Unix variants only have the `String` version of the `type()` method.  WindowsFileStore additionally has a method which passes through the integer type that we see in WMI, but doesn't translate that integer to an enum.

**Comment by dbwiddis** [comment]
Digging around even more to other projects out there, the only non-`String` implementations I've found pass through the WMI integer.  So if we were to add this to OSHI I'd only do the Integer from WMI for Windows, and all other OS's would return 0 (Unknown).  I can be convinced to do that by someone else writing the PR that I might accept. :)

**Comment by lundefugl** [comment]
> So if we were to add this to OSHI I'd only do the Integer from WMI for Windows, and all other OS's would return 0 (Unknown). 

That does not help us. We need it for Windows, Linux and Mac.
I think we will write a own map with the different texts for the operating systems.

**Comment by dbwiddis** [comment]
For Linux/Mac (and Unix) it's really mostly guesswork on OSHI's part based on the file path/mount point.  At least the strings used are consistent enough for you to add your own implementation.

You can look at the platform-specific *FileStore classes to see the possible results.
