### ISSUE TITLE
Comapare OSHI to Windows Task Manager

### ISSUE THREAD

**Issue by pstokosa** [oshi/oshi#2572]
Hi Team,

We are currently developing a Windows application that retrieves CPU usage information from OSHI, specifically calculating the difference in ticks for overall CPU usage and using the getProcessCpuLoadBetweenTicks method for individual process CPU usage. While we understand from previous discussions and the FAQ (https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#why-does-oshis-system-and-processor-cpu-usage-differ-from-the-windows-task-manager) that comparing overall CPU usage with Windows Task Manager is incorrect due to different calculation methodologies, there's a specific note regarding process CPU usage (https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#why-does-oshis-process-cpu-usage-differ-from-the-windows-task-manager).

According to the FAQ, to compare OSHI's process CPU usage with Windows Task Manager's display, we should divide OSHI's calculation by the number of logical processors. Our current approach follows this guidance, and we have a couple of questions for clarification:

1. While we understand that comparing overall CPU usage may be misleading, should we compare process CPU usage (after division by the number of logical processors) with Windows Task Manager? Specifically, if we sum the process CPU usages for a class or group of processes (e.g., all Microsoft Edge processes).

2. Could there be a scenario where the sum of CPU process usage does not equal CPU usage minus System Usage? (In our understanding, CPU usage represents the percentage of time when the CPU was not idle, while System usage is calculated as the sum of the percentage calculated from System ticks, IRQ ticks, and SOFTIRQ ticks.)

**Comment by dbwiddis** [comment]
Hey @pstokosa great questions.  It's been a while since I really dug in to that code and compared it to Task Manager, and I no longer have a windows machine to test on.   

In general I can say that the elapsed ticks for a process attempt to faithfully represent (approximately) the number of milliseconds of CPU usage that processor has.  (The actual ticks jump in increments of 1/64 of a second but represented in 100-nanosecond, so the "approximately" means up to a 16.25 ms error.).  How you interpret that as a "percentage" is your choice.

>  should we compare process CPU usage (after division by the number of logical processors) with Windows Task Manager? 

I'm pretty sure I had the gui application in the `oshi-demo` artifact exactly(within roundoff) matching up with my process task manager the last time I tweaked that code, so it might be a good place to look at the calculations. (Looks like number of cpus * the usage-between-ticks calculation as a percent.) See https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java

> Could there be a scenario where the sum of CPU process usage does not equal CPU usage minus System Usage?

Yes, depending on your settings.

First, note that Process usage includes both "kernel" (System) and "user" components, and those should align with the corresponding system components.

Second, Process usage is always based on elapsed time... specifically, if a process was using a CPU at the time the 1/64th of a second checked on it, it increments by 1/64 of a second of usage (for each such processor).   

System usage is based on elapsed time by default, so the sum of the process "user" ticks should (approximately, with roundoff) equal the overall system "user" ticks, and similarly for kernel/system.  (The javadocs specify which of the multiple fields go to which category.)

However, if you switch system usage to use the Task-Manger tracking "Processor Utility" values, then I don't think they'll line up at all.  

Sorry the answer wasn't simple and direct but I hope I've given enough description of what the stats actually represent to clarify what OSHI provides.

**Comment by dbwiddis** [comment]
>  Then I calculate the sum of process usage ... Is it possible to observe a discrepancy between this calculated sum of process CPU usage and the CPU usage obtained from the formula "100 - (idle/total) * 100"? 

I believe they should be very close.  Some possible differences:
 - remember Process 0 is the "Idle" process so be sure to exclude it in your sum.
 - you need the default time-based calculation, not the utility based one
 - I'm not sure whether more than one process will count as using the same CPU in a 1/64s tick.  This should average out well but I'm not sure about the specific values being precisely equal

You can confirm this for yourself by getting the actual raw data at the root of OSHI's calculations, querying the WMI values for the appropriate counters (wmic command line).  Win32_PerfRawData_PerfOS_Processor for systemwide and Win32_PerfRawData_PerfProc_Process for per-process.  The "raw data" in these tables are the actual elapsed ticks (1/64s in units of 100-ns) and you can sum them up and compare to eliminate any math calculation differences.

**Comment by pstokosa** [comment]
I remove Process 0 and use the default time-based calculation. I'm comparing these values (in RawData), but I wanted to have confirmation about OSHI's status on this dependence. 

Thank you so much for your response. I think I got answers to my questions :)
