### ISSUE TITLE
If the app is running in Docker, will the result obtained by Oshi be information about the operating system or the Docker container

### ISSUE THREAD

**Issue by Haste123** [oshi/oshi#2632]
If the app is running in Docker, will the result obtained by Oshi be information about the operating system or the Docker container

**Comment by dbwiddis** [comment]
Usually about the system, or somtimes not available at all, depending on how the container is configured.

OSHI looks for information where it would typically find it on a system, but from within a container these values can sometimes be changed.

There are configuration parameters to read Linux info from alternative proc, sys, or dev directories that some containers enable for a container-level view.

**Comment by adithyachakilam** [comment]
> There are configuration parameters to read Linux info from alternative proc, sys, or dev directories that some containers enable for a container-level view.

@dbwiddis Can you list what those configuration parameters are ? Thanks!

**Comment by dbwiddis** [comment]
> @dbwiddis Can you list what those configuration parameters are ? Thanks!

These were added in 6.6.0 in https://github.com/oshi/oshi/pull/2626 if you want to change the config file:
https://github.com/oshi/oshi/blob/8a745a131e6bf96bbaa87c2b3bb233a0944ab1d1/oshi-core/src/main/resources/oshi.properties#L9-L17

The corresponding constants if you want to add them programmatically (do this before you initialize SystemInfo) with `GlobalConfig.set(<the string constant below>, <the value>);`
https://github.com/oshi/oshi/blob/8a745a131e6bf96bbaa87c2b3bb233a0944ab1d1/oshi-core/src/main/java/oshi/util/GlobalConfig.java#L27-L29

As for alternative paths in containers, I have very little experience in doing that, but [this SO question](https://stackoverflow.com/questions/47072586/docker-access-host-proc) notes that the procfs inside the container has a limited view and they have mapped the host (real) procfs to `/rootfs/proc`.

**Comment by adithyachakilam** [comment]
We just realized that when in a containerized environment, all the /proc syscalls gives info about the host rather than the container itself. Instead we should be looking at cgroup stuff at `sys/fs/*` atleast for cpu, memory and disk. The format of these files is different from the /proc/stat and the just using `oshi.util.proc.path` would not solve the problem. So, the question is would `oshi` be open to exposing this info ? (I could contribute to those efforts.)

**Comment by dbwiddis** [comment]
> would `oshi` be open to exposing this info

Caveat 1: I've always wanted this to be a community decision so I'm tryiing not to answer for `oshi` here.  So I'm mostly answering from what I've heard over the years by others.

Caveat 2: I'm not an expert in containers.  So of all the feature requests, this is one I understand the least, so please take my opinion as mostly uninformed about specifics, but general in terms of OSHI's "philosopy".

I always hate to say "no" (and it's not really my sole decision), especially when someone offers to contribute.  But before throwing up some code in a PR, let's discuss what we should do.

The subject has come up before... there's a good discussion in https://github.com/oshi/oshi/issues/893 about this.  That issue was eventually closed, but it's been 5 years, so it's good to bring it up again.

A quick summary of that issue:
 - fetching the cgroup stats is a one-liner using OSHI's util methods
 - in general we should avoid creating a new API abstraction that's highly specific to one operating system (or in this case, container system), particularly if it's just a wrapper around an existing one-liner.

I think we'd be very open to a new API if there is any sort of cross-platform common terminology/standard/value that we can fetch.   A quick search brought me to https://github.com/opencontainers/runtime-spec/blob/main/spec.md which seems as "common" or "standard" as one can get.  

And it does look like "cgroups" are somewhat part of that standard: https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#example-3

So if we stuck to OCI conventions with the API that'd be enough to convince me it's not just a Docker thing.

So... maybe?  I'd love to see a more detailed proposal (or even a PR) for further discussion.
