### ISSUE TITLE
LinuxProcess should use its own process to calculate Jiffies per second

### ISSUE THREAD

**Issue by plamenko** [oshi/oshi#265]
In order to calculate Jiffies per second, [LinuxProcess.java](https://github.com/oshi/oshi/blob/e51f8e84f20bc4b132aa02601a4760b20bd4a198/oshi-core/src/main/java/oshi/software/os/linux/LinuxProcess.java) in its static initialization lists all the processes, finds the youngest one and divide its Jiffies since boot with its time since boot.

However, listing all the processes and finding the youngest one seems excessive. It seems unlikely that the process that uses OSHI is during its initialization much younger than what would the youngest process at that time be, and therefore OSHI could just use its own process to calculate this.

A concern might be if the hosting JVM started very soon after the boot, and for example a [Nailgun](https://github.com/martylamb/nailgun) server is used to run the programs. However, meeting both of these conditions seems unlikely.

**Comment by dbwiddis** [comment]
Good observation.  I didn't bother to optimize this overly much as it only runs once and seems to run fast enough, but there are some ways to improve it...

That said, limiting the search to a single process (the OSHI process itself) may not be the best approach.  Conceivably if a monitoring GUI (think Windows process manager, etc.) was built using OSHI it might be started as a service at boot, while the process object wouldn't be instantiated until the user specifically requested process monitoring.

It's less important that the process be "young" as that it have sufficient start time since boot to have an accurate calculation.  If we want to limit the number of processes we calculate for, we could probably start with the highest PID, which will be the youngest process until the process numbers wrap around, at which time it's probably "old enough".   Maybe do a combination of "the OSHI process" and the "highest PID process" and pick the older from these two...

**Comment by dbwiddis** [comment]
I'm going to close this as a wontfix.  Since this process only runs once, there's no need to make it more complex than it is, and as I've explained above, using the OSHI process itself isn't relialble.  The "highest PID or OSHI process #" together would probably be the best choice if this were to be run repeatedly and need optimization -- or if it wasn't already coded.  But for now, if it ain't broke, I'm not that interested in fixing it.    Feel free to submit a PR and reference this issue if you feel strongly about this, though!

**Comment by plamenko** [comment]
Sounds good. I opened the issue because someone was looking at the logs our tool (which uses OSHI) creates and was like "wtf is OSHI and why does it scan all of my processes". But I agree this is probably not the most important thing out there to be worked on.

**Comment by dbwiddis** [comment]
Well now that you mention the reason why, I took a quick look at the code and figure I can actually simplify it a little bit.  I'll throw this into 3.3

**Comment by dbwiddis** [comment]
So, I just kept most of the old code.  I sorted the list of pid files in the proc filesystem and picked the highest PID, which should either be the youngest (before rollover) or young enough (after rollover).
