### ISSUE TITLE
Regarding the issue with the "LinuxSensors.THERMAL_ZONE_PATH" constant

### ISSUE THREAD

**Issue by 1056227556** [oshi/oshi#2739]
In oshi.hardware.platform.linux.LinuxSensors, THERMAL_ZONE_PATH is defined as SysPath.THERMAL + THERMAL_ZONE. In the Linux environment, the value of THERMAL_ZONE_PATH is "/sys/class/thermal/thermal_zonethermal_zone". I believe this is incorrect, as "thermal_zone" is duplicated.
![image](https://github.com/user-attachments/assets/ce82cf55-dee2-487d-8a92-53fc7b9eb1fa)

**Comment by mprins** [comment]
yes that seems to be a bug, because:

https://github.com/oshi/oshi/blob/71e883d2be3b8055eb7a9c35f3a17c862fcb9ab7/oshi-core/src/main/java/oshi/util/platform/linux/SysPath.java#L32

and

https://github.com/oshi/oshi/blob/71e883d2be3b8055eb7a9c35f3a17c862fcb9ab7/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java#L40-L41

can you provide a PR with a fix?

**Comment by 1056227556** [comment]
Okay, I have submitted the changes.
[Fix the issue of being unable to obtain the CPU temperature due to the THERMAL value error.](https://github.com/oshi/oshi/pull/2740)

**Comment by dbwiddis** [comment]
Oops!

Thanks for the fix!
