### ISSUE TITLE
Support getting User/Group/Principal data per process

### ISSUE THREAD

**Issue by CodingFabian** [oshi/oshi#275]
In Sigar you can do getProcCredName/getProcCred to get ids and names for the user/group somtimes called principal executing a process.
It would be great to have such an API in Oshi. Ideally which returns this data in a single call.

**Comment by dbwiddis** [comment]
If the information is available in the extended format of the ps -O command, this seems doable.  I think getting userid/username is easy.  Not sure about the group but maybe a *nix expert can chime in here.

PR welcome.

**Comment by dbwiddis** [comment]
I've been looking into this.  I'd definitely like to add user/group information.  It's easily doable on the *nix-based systems:
- FreeBSD, Solaris:  the existing `ps` command line `-O`/`-o` switch has `uid`, `user`, `gid`, and `group` fields. Easy peasy
- Linux: we currently read the `/proc` directory for process information.  We can use `stat()` followed by `getpwuid()` and `getgrgid()` to get ownership of the `/proc/pid` directory for each process.  Or, we can simply parse the `ps` output like the other *nixes.
- OS X: we currently programmatically get the `proc_bsd_info` structure which contains the uid and gid.  We can then use `getpwuid()` and `getgrgid()` as in Linux.  Or, we can simply parse the `ps` output like the other *nixes.

That leaves Windows.  Which doesn't make anything easy.

The existing WMI implementation uses the [Win32_Process](https://msdn.microsoft.com/en-us/library/aa394372(v=vs.85).aspx) class. Unfortunately, this doesn't have user/group/domain info.  There's a `getOwner` method on the class, but this is not accessible via the WMI queries we use.  We would have to get creative parsing a powershell commandline.

The "proper" programmatic way to do it is to [enumerate the process list using PSAPI](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682629(v=vs.85).aspx), then for each process,  use `OpenProcessToken` to get the token, `GetTokenInformation` with the `TokenOwner` flag to get the SID of the owner, then `LookupAccountSid`.  [See here](http://stackoverflow.com/questions/2686096/c-get-username-from-process).  And all that's just for the owner.  I'm not even sure Windows has a `group` equivalent.

**Comment by dbwiddis** [comment]
Actually, it looks doable in windows using WMI.  The current `WMIUtil` class `enumerateProperties()` method produces a `WbemClassObject` (line 488).  We get the properties by invoking `Get()` on that object.  We would simply (HA!) need to update the `WbemServices` class to add [the `ExecMethod` mehod](https://msdn.microsoft.com/en-us/library/aa392103(v=vs.85).aspx), and pass that object (and other information like the `getOwner` method name), and then figure out how to parse the result strings.

Those are a lot of hoops to jump through just to use WMI which is already abstracting the PSAPI approach.   So  if we do this, PSAPI is probably the right approach.

**Comment by dbwiddis** [comment]
So, I tried to do this programmatically using PSAPI, but ran into a few problems.  I was easily able to list processes and get PID and process name, but any other info requires getting a Process handle and that's where things get wonky.

First, all the system processes came back with `null` on the `OpenProcess()` call.  This may be fixable by fiddling with permissions, but even the processes that were not null gave an `Invalid Memory Access` error frequently.  (This even happened trying to list group SIDs using @dblock [code posted here](http://code.dblock.org/2010/03/18/jna-win32-platform-api-implementation.html) -- sometimes worked, sometimes errored.)

I'm going to try the WMI approach and see if it's any less of a headache.

Here's the problematic code in case anyone wants to tell me where I messed up 😄 

```
    public static void main(String[] args) {
        Kernel32 kernel32 = Kernel32.INSTANCE;
        Tlhelp32.PROCESSENTRY32.ByReference processEntry = new Tlhelp32.PROCESSENTRY32.ByReference();

        WinNT.HANDLE snapshot = kernel32.CreateToolhelp32Snapshot(Tlhelp32.TH32CS_SNAPPROCESS, new WinDef.DWORD(0));
        try {
            while (kernel32.Process32Next(snapshot, processEntry)) {
                System.out.print(processEntry.th32ProcessID + "\t" + processEntry.th32ParentProcessID + "\t" + "\t"
                        + Native.toString(processEntry.szExeFile) + "\tUser: ");
                final HANDLE pHandle = kernel32.OpenProcess(WinNT.PROCESS_QUERY_INFORMATION | WinNT.PROCESS_VM_READ,
                        false, processEntry.th32ProcessID.intValue());
                if (pHandle != null) {
                    final HANDLEByReference phToken = new HANDLEByReference();
                    if (Advapi32.INSTANCE.OpenProcessToken(pHandle, WinNT.TOKEN_DUPLICATE | WinNT.TOKEN_QUERY,
                            phToken)) {
                        HANDLE hToken = phToken.getValue();
                        IntByReference tokenInformationLength = new IntByReference();
                        if (Advapi32.INSTANCE.GetTokenInformation(hToken, WinNT.TOKEN_INFORMATION_CLASS.TokenUser, null,
                                0, tokenInformationLength)
                                || Kernel32.INSTANCE.GetLastError() != W32Errors.ERROR_INSUFFICIENT_BUFFER) {
                            throw new RuntimeException(
                                    "Expected GetTokenInformation to fail with ERROR_INSUFFICIENT_BUFFER");
                        }
                        Memory tokenInformationBuffer = new Memory(tokenInformationLength.getValue());
                        WinNT.TOKEN_USER user = new WinNT.TOKEN_USER(tokenInformationBuffer);
                        // This call causes Invalid Memory Access
                        if (!Advapi32.INSTANCE.GetTokenInformation(hToken, WinNT.TOKEN_INFORMATION_CLASS.TokenUser,
                                user, tokenInformationLength.getValue(), tokenInformationLength)) {
                            throw new LastErrorException(Kernel32.INSTANCE.GetLastError());
                        }
                        // display user
                        System.out.println(Advapi32Util.getAccountBySid(user.User.Sid.getSidString()).name);

                    } else {
                        LOG.error("Failed to get process token for process {}: {}", processEntry.th32ProcessID,
                                Kernel32.INSTANCE.GetLastError());
                    }
                } else {
                    System.out.println("unknown");
                }
                kernel32.CloseHandle(pHandle);
            }
        } finally {
            kernel32.CloseHandle(snapshot);
        }
    }
```

**Comment by dbwiddis** [comment]
I've managed to get the WMI part figured out.

First step is to add `ExecMethod()` to the `WbemServices` object:
```
    public HRESULT ExecMethod(BSTR strObjectPath, BSTR strMethodName, NativeLong lFlags, Pointer pCtx,
            Pointer pInParams, PointerByReference ppOutParams, PointerByReference ppCallResult) {
        // ExecMethod is 25th method of vtable for WbemServices in WbemCli.h
        return (HRESULT) _invokeNativeObject(24, new Object[] { getPointer(), strObjectPath, strMethodName, lFlags,
                pCtx, pInParams, ppOutParams, ppCallResult }, HRESULT.class);
    }
```
Then in the WMI query, we ask for `"__PATH"` to get a unique path for the object.  This is passed as the `strObjectPath` in the above query.  Fortunately the `GetOwner()` and `GetOwnerSID()` methods do not require input parameters, which saves a few steps.   Currently (for testing) piggybacking on the `STRING` type I call `GetOwner()` like this:
```
                case STRING:
                    if ("__PATH".equals(property)) {
                        PointerByReference ppOutParams = new PointerByReference();
                        hres = svc.ExecMethod(new BSTR(vtProp.stringValue()), new BSTR("GetOwner"), new NativeLong(0L),
                                null, null, ppOutParams, null);
                        WbemClassObject result = new WbemClassObject(ppOutParams.getValue());
                        hres = result.Get(new BSTR("User"), new NativeLong(0L), vtProp, null, null);
                        System.out.println("User: " + vtProp.getValue() == null ? "Unknown" : vtProp.stringValue());
                        hres = result.Get(new BSTR("Domain"), new NativeLong(0L), vtProp, null, null);
                        System.out.println("Domain: " + vtProp.getValue() == null ? "Unknown" : vtProp.stringValue());
                    } else {
                        values.get(property).add(vtProp.getValue() == null ? "unknown" : vtProp.stringValue());
                    }
                    break;
```

So, I can put that test code into a separate method and add a few more enum types to deal with the specifics of this call.  This takes care of the user (we can return Domain\User) and uid (we can return the user's SID).

Not sure what (if anything) to put for group, however.  Windows process group ownership isn't really defined. There are groups (e.g.., Administrator), but they would simply replace the owner, rather than supplement it like in the *nix process listings.  (And my brief foray into PSAPI showed each process had a laundry list of groups assigned; not sure how to easily pick just one.  And with WMI I don't think it's really possible.   So I'm inclined to simply leave the Group blank, or possibly put the User / User SID into the group field.

**Comment by dbwiddis** [comment]
Implementing this in #317.  I decided to leave the Group stuff blank for Windows -- open to a future PR if someone has a grand idea on what to do.

I'm also wondering about the UID equivalent in Windows.  I made UID/GID strings, rather than ints, entirely to support the [Windows SID format](https://en.wikipedia.org/wiki/Security_Identifier).  However, this may be overly complex when mostly all we care about is the last number (e.g, instead of the String `S-1-5-21-77013034-1197188806-505994536-1000` just use the int 1000).  I doubt anyone will really be using the full SID for anything.

**Comment by dbwiddis** [comment]
#317 is almost done except for the UID/GID/SID/RID component that I'm still waffling on (pun intended for @dblock and @hazendaz).  

The *nix-based systems have integer UID/GID and corresponding names.   Windows has a domain, a name, and a Security ID (SID), the last component of which is the Relative ID (RID), which is unique to a domain (while the SID is globally unique).

The current Windows implementation:
User --> DOMAIN\user
UID --> Complete SID as a string
Group and GroupID are empty.

I'm currently leaning toward the following mapping for Windows:
User --> user (without domain)
User ID --> RID (integer)
Group --> Domain
Group ID --> (not sure yet what to do here) (integer?)

My thoughts here are to separate the domain from the user, although the use of the domain as a "group" isn't exactly right.   The whole "group" ownership of a process is different; there are a list of SIDs (individual and "group" accounts including "Everyone" and "Administrators" etc.) that would in theory populate that field.   Also, I tend to favor providing the user more information and letting them parse it (e.g., giving the whole SID string rather than extracting the integer RID).

I'd appreciate suggestions from the peanut gallery (including @CodingFabian who requested this) on how to split this out (or not) in a cross-platform manner.

**Comment by CodingFabian** [comment]
I am very happy you implemented this. I did not know this would be such a rabbit hole.

regarding the ids, it does not really matter for me, as long as its consistent (so the same group gets the same id)

**Comment by dbwiddis** [comment]
OK, I've finally settled on an answer, in the "give the user more information" department.  I'm leaving the values as Strings and keeping the Domain\User + SID split.  For Groups on Windows, I am using the APIs to actually fetch the list of groups/group SIDs.  However:
 - Getting groups for a user other than the current user requires oshi to be "run as administrator" and even then misses several system processes (the idle process, many services).
 - There is significant and unpredictable latency per-process for this call.  Minimum of about 30-40ms, maximum of about 1000; an average on my test system produced a 140ms average (overall 11-12 second delay to get a process list).  Accordingly I'm only fetching the group/groupID data for the `getProcess(pid)` single-process method call and not for `getProcesses()`.

**Comment by CodingFabian** [comment]
@dbwiddis the other library that shall not be named does not even return that data eager on a list for a single process but has a separate api. Maybe that helps you deciding how to model it :)

**Comment by dbwiddis** [comment]
Separate API is too much work. :)

See #310 where I'm considering totally revamping the model, and passing properties objects around to "update" much like they're currently done in the JSON version.  That will permit fine-tuned control of what gets initialized/updated on each object and address this issue seamlessly.
