### ISSUE TITLE
Support getting arguments on each process

### ISSUE THREAD

**Issue by CodingFabian** [oshi/oshi#276]
Right now OSProcess only contains the process name, it would be great if we could get access to the arguments as well

one note: in Sigar the name of the process is the first argument. This can cause some confusion.
For example this process:

```
root      3209  2.9  1.1 730744 701816 ?       Sl   Nov11 462:12 redis-server 0.0.0.0:6379
```
```
sudo cat /proc/3209/stat
3209 (redis-server) S 3200 3197 3197 0 -1 4219136 391194 0 4 0 1416994 1356344 0 0 20 0 3 0 399633970 748281856 175454 18446744073709551615 4194304 5367076 140726099622416 140726099621984 139860153686547 0 0 16781313 17610 18446744073709551615 0 0 17 1 0 0 1 0 0 7466384 7486001 25894912 140726099623554 140726099623589 140726099623589 140726099623900 0
```
```
sudo cat /proc/3209/cmdline
redis-server 0.0.0.0:6379
```

In sigar the process name would be `redis-server 0.0.0.0:6379`, while its executable would be `redis-server`.
In oshi the name would be `redis-server` and if arguments would be parsed from cmdline but the first one would be skipped, then the arguments would be empty.

the reason here is that popular tools like redis or nginx rewrite the cmdline file to indicate status (like listen ip+port)

So if an arguments API is added it should include the 0index argument which might or might not be identical to what name is.

**Comment by dbwiddis** [comment]
For the *nix ports, we can grab the full command line from the `ps` listing.  For Windows, there's a `CommandLine` field in WMI which contains something similar.  If we implement this,  I'm in favor of just having a "command line" field and leaving the parsing of arguments to the user.

The hitch here is OS X.  The information is not available through the existing `proc_pidinfo`-based code.  It would be available if we parsed the `ps` command like we do other OS's, which may be a reasonable approach.

**Comment by CodingFabian** [comment]
Just a remark: if you look into /proc/pid/cmdline you will see that arguments are \0 separated. when you look in ps its space separated. so from the cmdline file you can actually separate individual arguments that contain spaces. I like the fact that sigar preserves this, but obviously some tools are already confused by that. also depending on the shell you use when you invoke a process it might be hard to get a space into an argument rather than as separator.

**Comment by dbwiddis** [comment]
Parsing command line arguments is complex and, honestly, best left to the process running it.  Since the OSHI users aren't actually going to be processing the arguments, I'm not sure how useful a \0 delimiter is (or if it would cause problems on output).

I did find a way in OS X to get the process arguments using sysctl.  `mib = {CTL_KERN, KERN_ARGMAX,0,0}` retreives the # of bytes to fill; we can allocate a `Memory` object with this value and pass its pointer using `mib = {CTL_KERN,KERN_PROCARGS2,pid,0}`.   See the [C source code here](https://gist.github.com/nonowarn/770696).

Unfortunately, this requires either running oshi as root/sudo, or the oshi executable process being owned by root.  On the flip side, it requires no special permissions to just parse the `ps` listing (the `ps` command is owned by root, and thus passes this check), as is currently done by the FreeBSD and Solaris ports.  So while normally I would favor using a native code programmatic approach, the best approach for macOS is probably just to parse `ps`.

**Comment by dbwiddis** [comment]
Ended up using the sysctl stuff for macOS -- it provides the same access that the other native code does: which I realized only includes that user's processes (unless oshi is run with sudo, or owned by root).   So, writing using `ps` would be necessary to get all processes without these permissions.

I attempted to do this, actually, but macOS `ps` doesn't have a field for threads (the `wq` value isn't useful).  I think I'll just leave it as is.

Using `stat()` on Linux to get the process owner pid/gid proved problematic. Apparently different architectures use different size integers for the fields, and even different orders, making building a JNA equivalent impossible.  So I used the `stat` command line which conveniently lets me grab the uid/gid/user/group info all at once.

Both macOS and Linux return the command lines null-delimited which I think is more useful to end users (since the executable and args may contain spaces). End users can easily replace the nulls with spaces.  Windows uses double-quotes to allow similar spaces-in-args, but I'd rather leave it to the end user to deal with finding matching quotes.  Since the other OS's parse ps, we're stuck with the pre-parsed space (and 80 character limit on Solaris.)
