### ISSUE TITLE
taskkill feature

### ISSUE THREAD

**Issue by banjo123** [oshi/oshi#277]
It would be very nice, to allow to call a taskkill command
maybe on the process object, or kill by PID 
boolean result

**Comment by henryx** [comment]
I'm sorry, but is out of scope of the project

**Comment by dbwiddis** [comment]
Since this has come up elsewhere as a SIGAR compatibility question, I'll point out that it is trivial to do.

If you are on Java 9+, you don't even need OSHI.  Just use the PID to look up a If you are on Java 9+, you can use the pid to look up a `ProcessHandle` and kill it using core java:

```
Optional<ProcessHandle> proc = ProcessHandle.of(pid);
if (proc.isPresent()) {
    proc.destroy();
}
```

For Java 8, it's also easy to use command lines in core Java with `Runtime.getRuntime().exec(command);`.  OSHI has the `ExecutingCommand` class which wraps that `exec()`, so you could do this:

```
if (Platform.isWindows()) {
    ExecutingCommand.runNative("taskkill " + pid);
} else { 
    ExecutingCommand.runNative("kill -15 " + pid); 
}
```
You could inspect the result of the command to see if you were successful.

However, as OSHI is primarily designed to _collect information_, it is out of scope to actually alter the operating system environment like this, so there won't be a `kill()` method added to the `OSProcess` class.
