### ISSUE TITLE
Idle tick values are incorrect, seems like IOWait is not included (as expected by Oshi) on Windows

### ISSUE THREAD

**Issue by akoshpinter** [oshi/oshi#279]
Hello,

We have noticed that idle tick values are decreasing in time when the CPU usage is 100% (stress testing), and that is because IoWait is subtracted from idle value. (i.e. Idle difference is exactly = -iowait difference) My guess is that it is included in system ticks instead...? Applies to versions 2.6.2 and 3.2.

This happens on Windows machine, haven't yet tested it on Linux. Update: It seems to be correct on Linux.

**Comment by dbwiddis** [comment]
Good catch.

IOWait isn't really defined on Windows, so I made the (apparently poor) assumption to just count all IO time as IOWait.   As you've shown, this assumption breaks down when there is less idle time than there is IO.

The question is how to fix it.  I could do the same as the per-processor calculations and simply report zero IOWait.   I could set IOWait to a maximum of the idle time.   Or I could multiply the percentage of idle time by the IO time and assume it's equally distributed.   I think I favor that last interpretation.  

As you've noted, the problem is Windows specific because of this assumption.
