### ISSUE TITLE
3.3 Release TODO

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#280]
Mostly a note to myself on steps I need to take for the 3.3 release.

- Review #262 and implement in remaining OS's and JSON
- Review #264 and implement in remaining OS's and JSON

**Comment by hazendaz** [comment]
@dbwiddis I'm planning on officially bringing this into psi-probe.  Last we chatted about that, I wasn't as pominant of a position with psi probe.  Currently I'm pretty much the main guy on it now.  So I expect to bring this in as sort of a system out experimental to psi probe.  That should get some significant visibility on this as we just passed 100K downloads of psi probe just on github releases alone.  When I release this, psi probe will come to maven central too for the first time.  So I expect from a devops perspective downloads are going to fly fast.  I'm also planning on making psi probe spring boot enabled which should grow this even more.  Since we last talked the only semi-official usage was a development cut I had a team working with.

All that said, what are your expectations for 3.3 to be released?  Also, how hard is the java 8 requirement?  I still support java 7 on psi probe and can work around that but wondering if there is a lot of java 8 code or if this would compile with java 7 if needed.

**Comment by dbwiddis** [comment]
I was planning on a 1/1/17 release. Just need to port the above two changes to all OS's.

**Comment by hazendaz** [comment]
Sounds good!  Thanks.

**Comment by dbwiddis** [comment]
Java 7 is relatively easy to backport if needed.  Threeten.org dependency, map functions (getOrDefault() and friends) and a few lambdas. Open to ideas on how best to maintain a compatible variant.

**Comment by dbwiddis** [comment]
To be more clear on the previous comment:   parsing of WMI datetime data types required the new Java 8 DateTime classes (JSR-310).  Faced with a choice of supporting Java 7 (EOL+1yr) and adding a dependency to the threeten.org port of the time classes, or just supporting Java 8, I chose the latter.      After choosing Java 8, I took advantage of the expanded Map functions (which could easily be rewritten as wrappers in Java 7) and used some lambdas for readability.

If there's a compelling need to go back to 1.7 I can make it happen (with an added dependency).  We're not so far down the 1.8 road that we can't back up.   I'd prefer to stay on 1.8, however.

**Comment by hazendaz** [comment]
Thanks.  It's perfectly fine to stay on java 8.  I'll just add a check and if java 8 is present I'll allow the support.  All my personal and work related usage is 8 anyways.  For the larger community, if they want it they will just need to update to java 8.  I'll just have the page tell them it's available via java 8 only.  No real hard reason to continue supporting old.  I think it's only a matter of months before huge libraries make the large jump (ie junit 5, spring 5, etc).  This was just more out of curiousity of how much java 8 was really in here.  If you are messing around with JSR-310, I can imagine it's easier to just leave things be ;)

**Comment by dbwiddis** [comment]
These PRs have been knocked out.  Now just to do #274 and we're ready to release...

**Comment by dbwiddis** [comment]
Everything's in, tests run fine on all my VM's, and all the CI stuff passes.  SNAPSHOT can be considered a release candidate.  I'll release when the caffeine to alcohol ratio in my body is greater than 1. 😃 

(Or anyone else is welcome to push the release if they are more awake/sober than I am.)

**Comment by hazendaz** [comment]
I've got a few build things I guess I completely forgot about from a while ago.  Basically license plugin is misconfigured following example off website so it doesn't brand everything.  I've got that fixed but it updated a test file and broke the build.  If you can hang tight, I can get that fixed and applied tomorrow before the release goes.  To much to think about right now and I'm trying to call it a night ;)

**Comment by dbwiddis** [comment]
I'm in no hurry.  Do what you need!

**Comment by hazendaz** [comment]
I got it.  PR just raised.  That's all I have.  Something I had started months ago, ran into a test issue with it, then forgot all about it.  I just fixed the issue with the configuration of license plugin to not affect tests and raised the PR.  Also has a trivial fix to site.xml being included in each submodule otherwise local site doesn't properly generate everywhere which made it hard to verify all version updates ;)

**Comment by Nadahar** [comment]
We're stuck with Java 7 for a long time to come yet. Does this mean that anything prior to 3.3 is Java 7? You should probably mention it in the readme, it took some searching to find this.

**Comment by dbwiddis** [comment]
It's mentioned [in the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#what-minimum-java-version-is-required).  I'll look to see if I can put it in the README.

The last Java 7 version was 2.6.  Java 8 is required for any 3.x release.

**Comment by Nadahar** [comment]
@dbwiddis Ok, thank you. I think it's premature though, the last time I checked there were still Linux distros out there were Java 8 isn't yet available, and Oracle has decided (with good help from Microsoft I suspect) to withdraw their Windows XP support for Java 8 (it was supported in the beginning). [Windows XP is still the 3. most used OS today](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0), much larger than any Linux distro or OS X.

**Comment by dbwiddis** [comment]
Can you open a new issue to discuss reverting the project to Java 7 so we can better track it?

**Comment by Nadahar** [comment]
@dbwiddis I didn't really mean to discuss it - I just wanted to "give you my 2 cents". It seems that 2.6.1 can provide us with the very basic memory and CPU information I'm after.

**Comment by dbwiddis** [comment]
You had some very good reasons to restore support and if I'm going to do it I wanted an issue to reference!
