### ISSUE TITLE
Extend OSProcess (AbstractProcess.java) class is not easy

### ISSUE THREAD

**Issue by michaeldesigaud** [oshi/oshi#295]
I need to return an OSProcess instance through my api with custom properties.  
But it is not easy to extend any OSProcess implementation since the AbstractProcess.java does not allow to access setters (implemented only in WindowsProcess.java for example).

Is there a way to do this ?

**Comment by dbwiddis** [comment]
You would have to write your own constructor which called the old constructor, with its huge laundry list of arguments.  Which is taking problematic code and making it worse instead of fixing it. :)

We should probably rewrite OSProcess to use setters.  You're welcome to try to tackle that.  I may work on it over the next few weeks otherwise.
