### ISSUE TITLE
Processor Serial Number should return the CPU's SN, not the BIOS' SN

### ISSUE THREAD

**Issue by YoshiEnVerde** [oshi/oshi#296]
While the current impementation of **_getSystemSerialNumber_** from the **CentralProcessor** interface is solid on every O.S., I find myself disconcerted on how the values returned are not the values I expected when I first called the method.

From following the logical path _System > Hardware > Processor > Serial Number_, I'm expecting to recieve the **_Processor's SN_**.
Instead, I get the **_BIOS' SN_**.

This gets worse when I read the source code, and I find that this value is kept in memory as "**cpuSerialNumber**".
Even worse, the processor's SN doesn't ever even come close to the implementation of these methods.

Then, when I think something lie "OK, so _System Serial Number_ will target the **BIOS**, but at least I have a _Processor Identifier_, that might have the **Processor's ID**", and knowing that for all purposes the Processor's ID **_is_** its SN, I call that method, and I get a string made by grabbing a few other values and concatenating them; a string closer to the Processor's Name that to the ID.

As an example, running a simple java app to test these values, I get:
> Processor Vendor: GenuineIntel
> Processor x64: true
> Processor Family: 6
> Processor Model: 69
> Processor Stepping: 1
> 
> Processor ID: Intel64 Family 6 Model 69 Stepping 1
> Processor Name: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
> Processor SSN: G7N0GP000709308

Meanwhile, running **dmidecode**, I get the following:
> Processor ID: 51 06 04 00 FF FB EB BF
> Processor Version: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
> Processor Signature: Type 0, Family 6, Model 69, Stepping 1
> System Serial Number: G7N0GP000709308

Those are values from an Ubuntu Linux distro.
Same thing, from a Win7 VM (and using **wmic** instead of **dmidecode**, of course):
OSHI:
> Processor Vendor: GenuineIntel
> Processor x64: false
> Processor Family: 6
> Processor Model: 30
> Processor Stepping: 5
> 
> Processor ID: x86 Family 6 Model 30 Stepping 5
> Processor Name: Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz
> Processor SSN: VMware-56 4d da b8 62 63 33 16-67 b0 20 ae 74 33 36 95

WMIC:
> Processor ID: 0FABFBFF000106E5
> Processor Name:  Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz
> Processor Caption: x64 Family 6 Model 30 Stepping 5
> System Serial Number: VMware-56 4d da b8 62 63 33 16-67 b0 20 ae 74 33 36 95

Just to clarify, I believe CentralProcessor.getIdentifier() should be returning the Processor's ID, not it's Signature/Caption/Description, which should be returned by some method like CentralProcessor.getDescription() or such.
Either that, or we should have another method to get the ID itsef

**Comment by dbwiddis** [comment]
See #69 for background on why it originated the way it did. 

Since we recently added a more fine grained split of processor, board, and BIOS in #263, it makes sense to revisit this implementation and coordinate the two approaches in a consistent manner.

**Comment by YoshiEnVerde** [comment]
Ah, that's a good point there.

Thanks for the fast response.

I'll check thoroughly on the newest model as soon as I have the time, and see if I can contribute in there.
Just as a small heads up, I've managed to pitch the use of OSHI inside one of my company's solutions written in Java. 
As part of the pitch, I presented the idea of having at least a couple of our guys contribute to OSHI on a semi-permanent basis. This includes implementing a port to IBM's AIX.
That means I'll probably be lurking around here for quite a while.

**Comment by dbwiddis** [comment]
That's great news to hear the project will be of good use.  Let me know if you want someone on your team to join our contributor list to be able to merge PRs, etc.   It would feel silly having professional software engineers have to go through me as a gatekeeper. ;)

I wanted to do an AIX port at the same time I added the FreeBSD and Solaris ports, but had no ability to access a VM for testing. That would be an awesome addition.

Previous reply was written on my phone.  The Issues may be less informational than the code, but the bottom line is that we've split out processor, motherboard, and BIOS into separate lookups, trying to stick to factors that were mostly cross-platform.  I think there's some overlap with the way we grab the processor serial number, and it seems feasible to just have the `ComputerSystem` class do all the gathering of the information, and just make the `Processor` class's methods reference the other class when appropriate.

I don't have any grand solution in mind for this but it sounds like you may, so I'm happy to take suggestions.

**Comment by dbwiddis** [comment]
So, I spent a few minutes poking around at this issue and some of the information.

I do not believe there should be any change to `CentralProcessor.getIdentifier()`.  The information it returns is intended to be similar to (or the actual result of) [the `CPUID` opcode](https://en.wikipedia.org/wiki/CPUID), specifically:
  - EAX=0: Vendor ID (e.g., GenuineIntel)
  - EAX=1: Stepping, Model, Family, Processor Type

Even [Intel's documentation defines the Family+Model combination as "Processor Identification"](https://software.intel.com/en-us/articles/intel-architecture-and-processor-identification-with-cpuid-model-and-family-numbers).  And the Windows registry (`HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor`) has an `Identifier` entry (in my case, `x86 Family 6 Model 42 Stepping 7`) which is what OSHI uses on Windows to populate that field.

And, finally, the `ProcessorID` field that you highlight is exactly this information, in byte code.  The [`Win32_Processor` class documentation](https://msdn.microsoft.com/en-us/library/aa394373.aspx) has this to say about `ProcessorID`:

> Processor information that describes the processor features. For an x86 class CPU, the field format depends on the processor support of the CPUID instruction. If the instruction is supported, the property contains 2 (two) DWORD formatted values. The first is an offset of 08h-0Bh, which is the EAX value that a CPUID instruction returns with input EAX set to 1.

So the first 16 bytes of the `ProcessorID` encode the Stepping, Model, Family, and Processor type.  Exactly the same information OSHI displays.  (The second 16 bytes encode the feature flags, which OSHI doesn't currently display.)

I'm open to adding a `getProcessorID()` method to return the 32 byte `CPUID` result. It may be of use to people who wish to parse it and, as you've shown, it's easily obtained from `dmidecode` output.

Which brings us back to what should be given for the Processor Serial number.   We've chosen the `System Serial Number` from `dmidecode` which, as you note, comes from the BIOS (on Windows) and "Platform Serial Number" on OS X.     I think the best solution here is to move the existing `getSerialNumber()` method from the `CentralProcessor` object to the `ComputerSystem` object, deprecating the Processor version and otherwise leaving them unchanged.  This will fulfill the original intent of the method (provide a somewhat unique system/platform/processor serial) requested in #69, but better classify the method onto the `ComputerSystem` object (which did not exist when it was originally added) .

**Comment by dbwiddis** [comment]
The plot thickens. The `ComputerSystem` class already has a `getSerialNumber()` method and the implementations are redundant.  So it seems all we really need to do is deprecate the `CentralProcessor` version.

We can still add `getProcessorID()`, though...
