### ISSUE TITLE
NetworkIF getBytesRecv() returns negative value

### ISSUE THREAD

**Issue by svilenvul** [oshi/oshi#333]
First I have noticed that the Systeminfo binding for openHAB is returning a negative number and I thought that there might be something wrong in the binding.

But later I tried to build oshi using Maven on my machine and the NetworkTest has failed.

>testNetworkInterfaces(oshi.hardware.NetworksTest)  Time elapsed: 0.407 sec  <<< FAILURE!
java.lang.AssertionError
        at oshi.hardware.NetworksTest.testNetworkInterfaces(NetworksTest.java:53)

The 53-rd row is actually 
> assertTrue(net.getBytesRecv() >= 0);

I am running it on Windows and the this seems to be my Local Area Connection (the IP is the same)

**Comment by dbwiddis** [comment]
What version of Windows?  32 bit or 64 bit?

What should the value be?  Try:
- `netstat -e`
- `wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get Name,BytesReceivedPersec`
- Control Panel > Networks > Local Area Connection > Properties (bytes Received)

Off the top of my head, I'm guessing you may have exceeded the max long value.  Windows returns an "unsigned long" that Java doesn't have, but the bits would be correct (and FormatUtil.toUnsignedString(longValue)) would present it properly.  If that's the case, reboot! 😈

**Comment by svilenvul** [comment]
> Off the top of my head, I'm guessing you may have exceeded the max long value...

Yes, you are right :).

**Comment by dbwiddis** [comment]
That's a lot of data!  

But don't close this issue yet.  Looking into this I see some improvements.  In the 32-bit version the same issue could exist (much earlier) and I have the ability to promote those and preserve the sign, so there's at least some other fix.

For the unsigned longs, though, should we cap the value at a max (e.g., `Long.MAX_VALUE`) and ignore negatives?  That would prevent us from measuring differences/bandwidth, though.  I could just strip off the sign bit (`value | 7fffffffffffffffL`) which would make it wrap to zero when it went over...

**Comment by dbwiddis** [comment]
Windows is the only OS in OSHI that we have to handle the 32-bit widening for.  For 64-bit values:
- Windows and macOS produce unsigned longs that can lead to negative values unless we mask the sign bit.
- Linux, Solaris, and FreeBSD parse a string which could be an unsigned long, and would parse to 0 if too large.

I think masking the sign bit and rolling over at 2^63-1 is the best option.  I can put the sign-masking in the `NetworkIF` setters, and create a new `ParseUnsignedLongOrDefault()` to handle unsigned longs using BigInteger.

**Comment by detyo** [comment]
Hi,
  I was using OSHI 3.4.4 on Windows 7 64bit and getting wrong values for network interface speeds. I debugged the code and noticed the widening conversion (unsigned int -> long) which seemed to be causing this. After some investigation, I finally figured that the network speed issue was already reported as #431 and fixed. So the whole problem was that WindowsNetworks was wrongly identifying the Windows version as lower than 6 and doing the widening conversion. After I switched to latest 3.5 snapshot, this got resolved, but I still wonder whether this widening is proper:

`netIF.setSpeed(ifRow.dwSpeed & 0xfffffffL);`

Should not this mask be of eight 'f' digits instead of seven?

Regards,
   Detelin

**Comment by dbwiddis** [comment]
Well, a mask of 8 `f` digits wouldn't mask anything on a double word.  But maybe it should be `0x7fffffffL` to preserve / cap the 32-bit DWORD at max positive value.  Or since our value is a `long` should we parse all 32 bits to a 64 bit value to preserve the information?

**Comment by dbwiddis** [comment]
or maybe 8 `f`s does the widening properly and it's a simple `f` typo?  Who knows these things? :)

**Comment by detyo** [comment]
I'm not quite familiar with JNA and the dword handling, but what I assumed, that the values in `MIB_IFROW` structure are considered unsigned integers by JNA and if the value is too large, it will be set to 2^32-1. However, if this is then cast to long, Java would perform [widening conversion](https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.2) and will sign-extend the value - since the MSB is set in the original int value, it will set the rest of the bits in the long value to 1. If OSHI just reads that, it will be a negative value, so I thought this masking aims to get the original int bits, masking any of the more significant ones which might be set. I did a little experiment and it seems to prove this:

`Integer maxUnsignedInt = Integer.parseUnsignedInt("4294967295");

System.out.println("Max unsigned int as int bit string: \n" + 
        String.format("%32s", Integer.toBinaryString(maxUnsignedInt)).replace(' ', '0'));

Long maxUnsignedIntAsLong = maxUnsignedInt.longValue();
System.out.println("Max unsigned int as long bit string: \n" + 
        String.format("%64s", Long.toBinaryString(maxUnsignedIntAsLong)).replace(' ', '0'));

//mask the upper bits
Long correctValue = maxUnsignedIntAsLong & 0xffffffffL;
System.out.println("Correct long value (after masking): " + correctValue);`

Based on that, I thought that the mask should be 8 `f` digits long, instead of 7.

**Comment by dbwiddis** [comment]
Yep, you're right.   Anyone able to submit a PR?  Can either fix this here or add a new method to `ParseUtil` to do `unsignedIntToLong()`.

**Comment by detyo** [comment]
Ok, let me try that.
