### ISSUE TITLE
Why package private?

### ISSUE THREAD

**Issue by Nadahar** [oshi/oshi#339]
Sorry about the fuzzy issue name, but I didn't really know what to call it. I'm working on some code where I try to access some native OS X methods via JNA. As they are part of ```IOKit``` they use some of the types you have defined in ```CoreFoundation```. Instead of reinventing the wheel, I wanted to use these - but when I tried I discovered that they are package private. 

This means that I'll have to maintain a "copy" of ```CoreFoundation``` where I can access these classes, and that's something I'd like to avoid. Is there a good reason to keep these package private, or is it simply because you never considered that they could be useful for other classes?

Here is [an example](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/jna/platform/mac/CoreFoundation.java#L67).

**Comment by YoshiEnVerde** [comment]
The javadoc of the `CoreFoundation` class itself explains this issue: `CoreFoundation` is a non-API class. This means it's  there for implementation reasons only, should never be accessed directly by the user, and its existence will not be guaranteed between releases.

As such, any helper class that it contains could never be used for anything but internal package related issues

**Comment by Nadahar** [comment]
@YoshiEnVerde I understand that, but from the same text I concluded that it won't disappear but simply be moved to ```JNA```. If or when that happens, it's easy to update the references and continue to use the class from there. I'm aware that I'll probably have to do that at some point in the future, but I still think it makes more sense to use this as it is now rather than to maintain a copy.

**Comment by dbwiddis** [comment]
The simple answer of "why" is that I never really intended for anyone else to access the class and never really thought about package access.  Since the class is intended for internal use it doesn't really matter.

That said, I'm not opposed to changing the access to public and if you'd like to put together a PR I'd approve it.   However, I think the better long term answer if you find these classes useful outside of internal OSHI implementations, is for you to (also) submit a PR to the JNA project itself.

**Comment by YoshiEnVerde** [comment]
What I don't find agreeable about this proposal is that you aren't actually removing the cost of maintaining your own copy of these classes, you're shifting them to this codebase.

That said, since I'm not a main colaborator on here right now, specially when talking about Mac OS; and since  @dbwiddis (who **will** be responsible for these) is not opposed to the changes, I can only make this post to mak my position known

**Comment by Nadahar** [comment]
@dbwiddis I'm on really unfamiliar territory here (with native access, mapping etc.), but if I succeed I think the best thing to do would probably be to make a PR here at Oshi. What I'm trying to do is access methods not implemented in your ```IOKit```, which could probably simply be added to it.

**Comment by Nadahar** [comment]
@YoshiEnVerde I'm not sure I follow you here, as I understand it this code will exist either here or in JNA. I simply want to avoid having multiple versions of the same. I don't expect Oshi to keep this around if it's accepted into JNA.

**Comment by YoshiEnVerde** [comment]
@Nadahar Here's the thing... As far as I can see, it's a bit murkyu, you can only be trying one of three things:

1. You want to use parts of OSHI code in your own implementation of something.
In this case, then maintaining your own copy of the code IS the correct answer. The same way you'd have to do it if you wanted to only use one fifth of the Apache MINA code to build your own SSH server, while discarding the resting 4/5ths.
Just because whatever OSHI does to interact with JNA is the same thing you need doesn't mean it's valid to ask OSHI to modify their code for a use case that's simply not part of its remit.

2. You want to implement more functionalities into OSHI.
In this case, then you shouldn't need any modifications to the accesibility of these classes. Instead, you should be adding classes with the new functionalities into the OSHI code

**Comment by Nadahar** [comment]
@YoshiEnVerde You're seeing this from a very different perspective than I am. I haven't really thought that much about what is "right or wrong" here, I was simply wondering if there was some specific reason why these classes were made package private or if it simply was more or less a "coincidence".

This isn't "normal code", it's simply mapping of some OS X native types to Java. As such, I'm sure the maintenance cost is minimal, as this isn't likely to change. We already have both JNA and Oshi as dependencies. It's not that I wanted to save myself the job of copying the code, I've already done that in the branch where I try to get this working.

My thought when asking were simply to avoid code duplication, and especially duplicating someone else's code. It's absolutely no problem for me to live with a duplicate, that's why I wanted to know if there were a specific reason they were made package private or not.

**Comment by Nadahar** [comment]
In any case I got my answer, I'll see what I can get working and consider how to handle it from there.
