### ISSUE TITLE
Is OpenHardwareMonitor's dependency removed?

### ISSUE THREAD

**Issue by yososs** [oshi/oshi#342]
This project
Although it is introduced as 

> It does not require the installation of any additional native libraries

there is code dependent on the OpenHardwareMonitor application in WindowsSensors.java. Is this dependency removed in the future?

**Comment by dbwiddis** [comment]
The key word here is "require".  OSHI runs just fine without OpenHardwareMonitor installed.

WindowsSensors depends on WMI, the Windows Management Interface, the only officially provided API for sensor information provided by Microsoft.   The simple fact is that if WMI doesn't have the values, they simply aren't available without installing additional software.

Different versions of Windows publish to different locations in WMI, so I check them all.  Just because I check the Windows 8+ location that's not available on Windows 7 doesn't mean OSHI is dependent on Windows 8+.

OpenHardwareMonitor, when running, publishes its information to WMI.  Since it's a lightweight, free program, I have chosen to add the WMI location that OHM publishes to, to the list of other locations that OSHI checks.  If it's there, great.  If it's not, the program happily returns no information.

Removing this check wouldn't make OSHI perform any better, and would remove an option available to users.

**Comment by dbwiddis** [comment]
The alternative to checking one more WMI location, would be trying to replicate the hundreds of lines of code in OHM or similar products, issuing CPU opcodes and parsing the results differently depending on what BIOS is present... and maintaining that code up to date!    I certainly don't have the time to do that (or the hardware to test it on).  If anyone else is willing to put forth that effort, I'd be happy... but I doubt anyone will when the alternative is so painless.

**Comment by dbwiddis** [comment]
I'm not sure I understand the question.  Are you asking if I plan to write code to directly interface with OHM?  Then the answer is "no".

The only published Microsoft API for obtaining Temperature, Fan Speed, and Voltage is through WMI (with various classes).  Unfortunately, this API requires motherboard manufacturers to publish to WMI, and few (or none?) do.

Since the OHM program is free, cross-platform, and easy to set up to run in the background, and most importantly *publishes the data it collects to WMI*, I have added a search of the WMI coordinates that OHM publishes to, as one more way of trying to collect this information.  If there are any other sensor monitoring programs that also publish to WMI, I'll be happy to add them as well.

**Comment by yososs** [comment]
I understood the policy on Windows.

**Comment by dbwiddis** [comment]
I plan on closing this issue as it doesn't appear to raise any additional problems that I can solve.  To summarize:
* there are no plans to require any additional software for OSHI to run.  Without optional/added software, OSHI will always return sensible defaults/null/zero values.
* There are many places where OSHI checks for certain (free) software that is easily installed, to enable additional capabilities, and I don't plan to remove those.  These are documented as much as possible.
