### ISSUE TITLE
OpenHAB2+FreeNAS UNINITIALIZED - HANDLER_INITIALIZING_ERROR

### ISSUE THREAD

**Issue by janb14** [oshi/oshi#382]
I was redirected from the OpenHAB forum after reporting the issue there.
Im running OpenJDK1.8 on FreeNAS 9.10 and tried to use the Systeminfo Binding in OpenHAB, but it couldnt initialize correctly throwing the following error:
`Native library (com/sun/jna/freebsd-x86-64/libjnidispatch.so) not found in resource path (/mnt/openhab2/runtime/lib/boot/org.apache.karaf.diagnostic.boot-4.0.8.jar:/mnt/openhab2/runtime/lib/boot/org.apache.karaf.jaas.boot-4.0.8.jar:/mnt/openhab2/runtime/lib/boot/org.apache.karaf.main-4.0.8.jar:/mnt/openhab2/runtime/lib/boot/org.osgi.core-6.0.0.jar`
What does that mean? Can i do something about it ?

**Comment by dbwiddis** [comment]
I hate to redirect you again, but this isn't specifically an OSHI issue so much as an issue loading the JNI library necessary for OSHI's JNA dependency, so if I can't help here, asking on the JNA user mailing list is probably your next step.  However, I do have an idea:

It looks like a JNA issue regarding locating the JNI library in your FreeBSD installation.  The solution is probably finding the actual location of that library, and adding it to your Java class path (or creating a redirect from the path shown in the error).

**Comment by YoshiEnVerde** [comment]
You beat me to the answer @dbwiddis 

Basically, you're missing a binary file from your JNA build, or configuration (**_com/sun/jna/freebsd-x86-64/libjnidispatch.so_**)

Check inside your JNA JarFile (it will be called jna.jar, or jna_X.X.X.jar) if the file is missing. That's the most probable reason for this error.
If so, you'll need to build your own copy of JNA, or raise the issue in the JNA GitHub so that they can give you a correctly built version of the library

**Comment by dbwiddis** [comment]
> raise the issue in the JNA GitHub

JNA prefers you ask first on [the JNA Mailing List](https://groups.google.com/forum/#!forum/jna-users) to confirm whether there's a bug, prior to raising an issue.

**Comment by YoshiEnVerde** [comment]
Just so you can, more or less, understand what's going on (and thus have less problems with mantaining your own code):

- You call on OpenHAB to get some data.

- OpenHAB calls on OSHI to gather the data to give to you.

- OSHI uses JNA to get the raw data directly from the OS, then parses the results into structured object trees.

- JNA uses binary code (written in C, and compiled natively) to call on the OS' public APIs for the needed data.

- Of course, JNA needs the binary for your concrete OS in order to do this. That's what you're missing.

**Comment by janb14** [comment]
Now im redirecting you guys back to the openHAB forum where someone already noticed missing files from version 4.2.2 on. So it seems to be a bad compiled jna jar as the native interface jars for FreeBSD are missing.
https://community.openhab.org/t/systeminfo/31296/9

**Comment by dbwiddis** [comment]
JNA 4.5.0 may have fixed this.  Can you test?

**Comment by dbwiddis** [comment]
(OSHI snapshot has been updated with dependency to JNA 4.5.0)

**Comment by dbwiddis** [comment]
This should be fixed with OSHI 3.4.4 and update to JNA 4.5.0.
