### ISSUE TITLE
how to get process I/O per second

### ISSUE THREAD

**Issue by martinko2009** [oshi/oshi#385]
I want to know how to get process I/O per second.
I wrote some codes below, but I am not sure these are correct.If the codes are wrong, could you please tell me the correct one, thank you.
these are codes I wrote:
```
int pid = 3066;
OSProcess process = null;
SystemInfo si = new SystemInfo();
OperatingSystem os = si.getOperatingSystem();
process = os.getProcess(pid);
long readBytes1 = process.getBytesRead();
long writeBytes1 = process.getBytesWritten();
Thread.sleep(1000);
long readBytes2 = process.getBytesRead();
long writeBytes2 = process.getBytesWritten();
long processReadBytesPerSecond = readBytes2 - readBytes1;
long processWriteBytesPerSecond = writeBytes2 - writeBytes1;
```

**Comment by dbwiddis** [comment]
Your code is almost correct.

OSHI's process data is static information.  So in your code above your `readBytes2` and `writeBytes2` would be the same values and you'd get zero I/O.  Currently you'd need to re-read the process information (`os.getProcess(pid)`) to update it.  In a future version there may be an `update()` method.

One other suggestion; rather than relying on `sleep(1000)` (plus the other code overhead) taking exactly 1 second you may want to use a timestamp from the process, such as `getUpTime()` to get the actual elapsed milliseconds to use as a denominator.

**Comment by martinko2009** [comment]
Thank you for your help.I will take your suggestion.

**Comment by martinko2009** [comment]
I revised some codes like below, are those codes correctly.
```
int pid = 3066;
OSProcess process = null;
SystemInfo si = new SystemInfo();
OperatingSystem os = si.getOperatingSystem();
process = os.getProcess(pid);
long uptime1 = process.getUpTime();
long readBytes1 = process.getBytesRead();
long writeBytes1 = process.getBytesWritten();
Thread.sleep(1000);
process = os.getProcess(pid);
long uptime2 = process.getUpTime();
long readBytes2 = process.getBytesRead();
long writeBytes2 = process.getBytesWritten();
long processReadBytesPerSecond = (readBytes2 - readBytes1)*1000/(uptime2-uptime1);
long processWriteBytesPerSecond = (writeBytes2 - writeBytes1)*1000/(uptime2-uptime1);
```

**Comment by dbwiddis** [comment]
This looks correct to me!

**Comment by martinko2009** [comment]
Thank you.
