### ISSUE TITLE
memory leak when calling operatingSystem.getProcesses() 

### ISSUE THREAD

**Issue by krdenesh** [oshi/oshi#390]
I am calling operatingSystem.getProcesses() in my service and i see the memory usage increasing rapidly. Has anyone else seen this behavior?

Thanks

**Comment by Kaldolol** [comment]
I've experienced that as well, although I wouldn't call it a _leak_.
I'm far from being an expert on the matter but to my understanding, each call of **operatingSystem.getProcesses()** will instantiate classes and store process information in those classes, taking up memory on the system. 
Since you're running a Java process without any specific options, the Garbage collector won't be called since there's still plenty of memory available for the new processes, and you end up seeing your program taking 1 or 2 gb, even though most objects aren't referenced anymore.

Running your application with the _-Xmx_ option will prevent this behavior. I'm using _-Xmx128m_ to retrieve 20 to 30 processes and it works perfectly.

**Comment by dbwiddis** [comment]
Do you dispose of your OSProcess classes when you are done with them?

**Comment by krdenesh** [comment]
Thanks for the suggestion @Kaldolol reducing the heap size helped. 
@dbwiddis How do you suggest i dispose the OSProcess class other than explicitly performing GC

**Comment by dbwiddis** [comment]
It was more making sure you release all references to them... which if you've done, you're already there....
