### ISSUE TITLE
Windows System UUID

### ISSUE THREAD

**Issue by Lyhaku** [oshi/oshi#429]
I was expecting that the function String getSerialNumber() from the ComputerSystem  object would return the hardware UUID in a windows machine like It does in Linux systems. Instead the default operation when calling the getSerialNumber() in a windows system is reading the BIOS serial number (String serialNumber = WmiUtil.selectStringFrom(null, "Win32_BIOS", "SerialNumber", "where PrimaryBIOS=true");). This way you get two different format serial numbers instead that a common one.
I think It should, at least, try to read the real UUID of the system, the one read by calling the command: "wmic csproduct get uuid". 
It is done like this:
String serialNumber = WmiUtil.selectStringFrom(null, "Win32_ComputerSystemProduct", "UUID", null);

Am i wrong?
Should it be the default choice?

Thank you

**Comment by YoshiEnVerde** [comment]
Better read #296. That was my first issue here.
There's a nice long explanation on why this happens the way it does now.

That said, your issue is a valid one (not a duplicate of my old issue, which was resolved back then).
So, to answer that in simple terms:
The Linux implementation doesn't get the UUID. At least, not if everything goes well.

If you read the code for the LinuxComputerSystem class, you'll find that it first tries to get the SN from **product_serial**, and only gets the one from **board_serial** if that fails (it then goes to try _dmidecode_ and _lshal_ if it still gets nothing).

This is a case where naming conventions are not followed between systems.
What Linux calls **_System UUID_** (which is the first fallback value here, the one in **board_serial**) corresponds to what Windows calls the **_Computer System UUID_** (which is your suggestion for the query).
However, the initial value is what Linux calls the **_System Serial Number_**, which should correspond to what Windows calls the **_BIOS Serial Number_**.

If you check both implementations side to side (WindowsComputerSystem and LinuxComputerSystem), you'll see both follow the same logic:
1. Check if we can recover the primary value (BIOS SN)
2. If not, check if we can recover the secondary value (System UUID)
3. If not, go into panic and try the less available methods (sudo locked commands, deprecated commands, etc)

**Comment by dbwiddis** [comment]
I made a best-effort attempt to be cross-platform and consistent. I may have failed.  I welcome a PR to sort things out and/or provide additional cross-platform values.

**Comment by Lyhaku** [comment]
@YoshiEnVerde you are right... I checked again and I was misdirected by the fact that in my test linux machine the BIOS serial number was the exact same format as the UUID.. Thank you for fast reply! You can close the issue
