### ISSUE TITLE
Support for Disk S.M.A.R.T. attributes 

### ISSUE THREAD

**Issue by szquadri** [oshi/oshi#437]
Thank you for the wonderful project oshi. I am trying to use it for monitoring hardware nodes.

I couldn't find any support for S.M.A.R.T. attributes for disks. I think this is important hardware info that oshi should support.

Any plans supporting SMART?

**Comment by dbwiddis** [comment]
"Plans"?  Nope, but you're welcome to try to add it. :)

I think I briefly looked into it (there's a SMART code available from WMI's Win32_BIOS class but it didn't work in my test VM) but decided against it because it's such a rare use case, there are far superior monitoring tools on the market, packages are needed for any useful information on Linux, and a few other reasons.

That said, if you can add the feature I'll be happy to merge it to the project.

**Comment by dbwiddis** [comment]
Spent a few hours digging into possibilities here.   At best, we can return the usual "OK" from the OS.   Any more detailed and useful information just isn't available out of the box.

Just about every useful tool out there eventually leads back to [`smartctl`](https://www.smartmontools.org/browser/trunk/smartmontools/smartctl.8.in) and utilities to help [parse its output](https://github.com/akramhussein/visco/blob/master/src/contrib/failmon/src/java/org/apache/hadoop/contrib/failmon/SMARTParser.java).

Given that if someone truly cares about monitoring their disk they'll set up better software for the purpose, I think this is something that just won't make it into OSHI, so I'll close this request.
