### ISSUE TITLE
Wrong Windows display information

### ISSUE THREAD

**Issue by UnAfraid** [oshi/oshi#450]
Hello!

I've notice while running SystemInfoTest that display information is kinda wrong:

Active Pixels `3840x1920` my screen resolution is 1920x1080
Also it says `Analog`, but none of them is Analog, first of the monitors is attached with HDMI the second one with DisplayPort
~Those dimensions `53 x 30 cm (20,9 x 11,8 in)` are wrong also~

I am running Microsoft Windows 10 build 14393 Enterprise LTSB

```
Checking Displays...
Displays:
 Display 0:
  Manuf. ID=ACB, Product ID=216, Analog, Serial=110ￓ0E, ManufDate=4/2011, EDID v1.3
  53 x 30 cm (20,9 x 11,8 in)
  Preferred Timing: Clock 148MHz, Active Pixels 3840x1920 
  Range Limits: Field Rate 56-76 Hz vertical, 31-83 Hz horizontal, Max clock: 170 MHz
  Monitor Name: S242HL
  Serial Number: LR90D0048570
 Display 1:
  Manuf. ID=DEL, Product ID=a097, Analog, Serial=3MWS, ManufDate=12/2014, EDID v1.4
  48 x 27 cm (18,9 x 10,6 in)
  Preferred Timing: Clock 148MHz, Active Pixels 3840x1920 
  Serial Number: 29C294BO3MWS
  Monitor Name: DELL P2214H
  Range Limits: Field Rate 56-76 Hz vertical, 30-83 Hz horizontal, Max clock: 170 MHz
````

**Comment by dbwiddis** [comment]
OSHI merely retrieves the EDID from the video adapter; the rest of the information is parsed from that.  It's possible for hardware/software to spoof the EDID and that may be the case here.

**Comment by UnAfraid** [comment]
How can we verify that?

**Comment by UnAfraid** [comment]
I've just downloaded some EDID Monitor viewer and it prints correct information https://i.imgur.com/pt6AqAA.png

**Comment by dbwiddis** [comment]
Does OSHI retrieve the correct EDID and parse the values wrong in its util?

**Comment by YoshiEnVerde** [comment]
Just to point out: The screen sizes are not incorrect.
Both the EDID Monitor screenshots and the OSHI log show that the Dell monitor is 48x27 cm, and the Acer monitor is 53x30cm.

The monitor size in inches in OSHI is the direct conversion on cm>in, while the one in the EDID Monitor is the screen size (which is, basically, the length of the screen's diagonal).
Using the data from OSHI, you can easily get to the screen sizes (Apply Pythagoras: H^2 + W^2 = D^2).

On the other two issues (Analog/Digital and Resolutions), I'm willing to believe that might be a bug in our code

**Comment by UnAfraid** [comment]
Screen size is correct, my mistake i accidentally measured the wrong monitor looking at dell but measured the acer lul, i know how the screen size works inches and so.
But still Analog/Digital and resolutions is wrong

**Comment by YoshiEnVerde** [comment]
After checking the code:

- The Analog/Digital issue is a bug on our code. 
**oshi.util.EdidUtil.java@150:** `return 1 == edid[20] >> 7;`
The shift should be used with the **unsigned right shift** operator (>>>) instead.
When bit 7 is set (meaning Digital display), the current code is returning 0xFF instead of 0x01.

- The Analog/Digital issue is a bug on our code. 
**oshi.util.EdidUtil.java@214:** `int hActive = (desc[2] & 0xff) + (desc[4] & 0xf0) << 4;`
**oshi.util.EdidUtil.java@215:** `int vActive = (desc[5] & 0xff) + (desc[7] & 0xf0) << 4;`
Here, we're parsing the resolutions wrong.
The calculation is adding up the 4 mbits of desc[4] and desc[7] as the 4mbits of the corresponding resolution, when it should be adding the 4 lbits of the byte as the 4 mbits of the resolution.
This is compounded by the fact the binary shift operators are (mathematically) resolved **after** additions, so the shift is being applied to the whole value, not just the second byte.

Replace those by:
```
int hActive = (hRes[1] & 0xff) + ((hRes[0] & 0x0f) << 8);
int vActive = (vRes[1] & 0xff) + ((vRes[0] & 0x0f) << 8);
```

If somebody else would be able to PR these changes, it would be much appreciated.
I won't have the time before the weekend

**Comment by UnAfraid** [comment]
I'll submit the PR

**Comment by UnAfraid** [comment]
I've made the changes you purposed but results are still not correct:
```
 Display 0:
  Manuf. ID=ACB, Product ID=216, Analog, Serial=110ￓ0E, ManufDate=4/2011, EDID v1.3
  53 x 30 cm (20,9 x 11,8 in)
  Preferred Timing: Clock 148MHz, Active Pixels 570x570 
  Range Limits: Field Rate 56-76 Hz vertical, 31-83 Hz horizontal, Max clock: 170 MHz
  Monitor Name: S242HL
  Serial Number: LR90D0048570
 Display 1:
  Manuf. ID=DEL, Product ID=a097, Analog, Serial=3MWS, ManufDate=12/2014, EDID v1.4
  48 x 27 cm (18,9 x 10,6 in)
  Preferred Timing: Clock 148MHz, Active Pixels 570x570 
  Serial Number: 29C294BO3MWS
  Monitor Name: DELL P2214H
  Range Limits: Field Rate 56-76 Hz vertical, 30-83 Hz horizontal, Max clock: 170 MHz
```

**Comment by YoshiEnVerde** [comment]
I've checked the changes locally, and they should be working.

Moreover, there is no possible way they should ever return 570x570 as resolution.
Please check that you used the right code for the latest test

**Comment by UnAfraid** [comment]
I've fixed that, in the pull request its working fine now, thanks

**Comment by dbwiddis** [comment]
Thanks everyone for handling this! Good catch and fix.  One day I'll understand it :)
