### ISSUE TITLE
OS level open file handles

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#461]
Would be helpful to have a system wide metric for the number of open file handles

**Comment by dbwiddis** [comment]
I've thought about this and figured it could be done by the end user after retrieving all the process handles... but if you want to write that utility method (I guess it's faster on the *nixes) be my guest!

**Comment by dbwiddis** [comment]
Looked into doing this and saw it was already done in [FileSystem.getOpenFileDescriptors()](http://oshi.github.io/oshi/apidocs/oshi/software/os/FileSystem.html#getOpenFileDescriptors--) -- except that it's not implemented for Windows, because the closest we can get are Handles (which include not only files, but thousands of other memory pointers).  I don't see why we can't return the total number of Handles (which would match the sum of the `Process` handles) instead of 0... at least let the user ignore it if it's useless... so I'll make that change here.
