### ISSUE TITLE
UpdateDiskStats matches improperly on non-unique serial number

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#510]
Hi,

I build from current GitHub with "mvn package" on 64 Bit Linux. I get this (reproducibly):

```
testDisks(oshi.hardware.DisksTest)  Time elapsed: 0.071 sec  <<< FAILURE!
java.lang.AssertionError
	at oshi.hardware.DisksTest.testDisks(DisksTest.java:85)
```

What's that about? Can I build without the tests?

Many greetings

**Comment by dbwiddis** [comment]
the failing test is that disk reads are not increasing.  This is probably related to #501.

I assume there are switches to maven allowing build ignoring test failures, that you can use while we figure out this problem

**Comment by dbwiddis** [comment]
Can you manually check your disk read operations statistic (OSHI gets it from udev... I think the devstat command gives same values) and see why they aren't increasing (or at a minimum staying the same)?

**Comment by dbwiddis** [comment]
Thanks for the detailed log.   The problem is that OSHI's `updateDiskStats()` method attempts to match on the serial number of the drive, and in your case two of the drives share an identical "Unknown" serial.

I don't see any reason on Linux why we aren't matching on the name, though... and we should rethink serial number matching on all OS's.  @cjbrowne do you have any thoughts?

**Comment by dbwiddis** [comment]
Also, score 1 for unit tests in catching this. :)

**Comment by cjbrowne** [comment]
What is "name" on Windows? I picked serial number under the (now proven false) assumption it had stronger guarantees of uniqueness than the name field would have.

I can take a closer look tonight and see if I can come up with a better solution.

Worst comes to the worst we could combine e.g name and serial for "extra" uniqueness on platforms that don't give us guarantees on unique names for disks.

**Comment by stefan-reich** [comment]
+1 for combining name and serial

**Comment by dbwiddis** [comment]
"Name" on windows is a space-delimited string of the index and the drive letter.  For example, on my system, my primary drive's name is "0 C:".   I've been working on a plan to rewrite the windows version outside of WMI, btw, using PdhEnumObjectItems to iterate the instances ("0 C:", "1 D:", etc.) and then just matching up the index number.   I haven't done any testing to see if the indices reorder themselves if a disk is removed, though.

**Comment by cjbrowne** [comment]
Should be unique enough on its own then.

What should happen if you unplug a hotswap drive and replace it with a different drive? If we just use the name it will appear to be the same drive, if we append the serial number then the two would be treated as two different drives.

Either behaviour seems like it could be expected to me, so I'm not sure which is preferable.

**Comment by dbwiddis** [comment]
The current serial number implementation won't help, though. You'll just look up from the old serial # what the drive instance is and be in exactly the same boat.    Given that I'd like to switch to the PDH implementation, let's try to match on the instance name/number, which I think you already have ("Index").  I can then fetch the instances and use PDH Counters to query the value (essentially doing the same thing [WMI does](https://msdn.microsoft.com/en-us/library/aa394308(v=vs.85).aspx) without the COM overhead).

I think we can ignore hotswapping, or leave that to the user to detect with sanity checks.  Possibly update the javadoc to note this limitation.

**Comment by cjbrowne** [comment]
Ok, sounds good to me.

**Comment by dbwiddis** [comment]
Actually I misspoke.  The "Name" field on the disk stats query is as I said, but the "Name" stored elsewhere and in the HWDiskStore instance is different.  On windows the name is: `\\.\PHYSICALDRIVE0`.  The "PHYSICALDRIVE" portion is always constant, just substitute 0 for the drive index.

So for Windows the strategy should be:
- call updateDiskStats with the HWDiskStore
- parse the name to recover the last digit(s).  While a regexp might be "proper" I actually think you can just lop off the first 16 characters of the string.
- get a list of all physical drives (temporary: WMI query on "Name" from [this class](https://msdn.microsoft.com/en-us/library/aa394308(v=vs.85).aspx)), later will convert to PDH instance list.)
- match the instance that starts with the index recovered 2 steps higher
- retrieve the data.

**Comment by dbwiddis** [comment]
I think I have good line of sight to do Windows... if you (@cjbrowne) can do the Linux fix.

**Comment by dbwiddis** [comment]
I've done the Windows portion in #514, along with switching to the (faster) PDH counters.  Turns out that we (I) already used the Disk Index when creating the Partition class, so as long as the disk exists, the first partition should uniquely identify the index with it's `major` attribute.  If it doesn't have a partition, I think the name can be parsed, but if it doesn't have a partition we probably don't care about reads and writes to it. :) 

I also updated the javadoc to represent the disk swap exception.  So all that's left is the linux change from serial number to some other more unique id.

**Comment by dbwiddis** [comment]
I'll see @stefan-reich's "+1 for combining name and serial" and raise to a "+2 combine All The Things".

HWDiskStore has a `hashCode()` implementation using name, model, serial, size, and the partition array; the partitions also have `hashCode()` on their non-changing values.  So I simply switched the map key from the serial number to the `hashCode()`.

....

Except that's failing unit tests on Travis because update is returning false.  Maybe it's TOO specific...

**Comment by dbwiddis** [comment]
Ah, it appears the initial map is populated while the partition array is null.  So I'll have to slightly scale back the hashCode calculation to exclude the partitions.

**Comment by sohailravian** [comment]
@dbwiddis Dear I am trying to find hard disk free space available. I got the total space like below
HWDiskStore[] disks = systemInfo.getHardware().getDiskStores();
for (HWDiskStore disk : disks) {
				disk.getSize()  // It return total size of disk
			}

Please help me find out the free space on this disk. :(

**Comment by stefan-reich** [comment]
@sohailravian Wouldn't File.listRoots() serve you better here?

**Comment by dbwiddis** [comment]
You want to use Filesystem.getFileStores() and for each OSFilestore get the total and usable space.

**Comment by dbwiddis** [comment]
From a hardware perspective there is no such thing as free space.  Just a disk (or Flash memory) filled with a bunch of 1s and 0s that might mean something to different operating systems.   Free space is a software thing based on partitions mapped to logical drives (FileStores).  You can link the DiskStore to its partitions, which map to mount points that match the file stores.

**Comment by sohailravian** [comment]
@stefan-reich  yes i already did that. Thank you. @dbwiddis yes i am doing same as you mentioned
