### ISSUE TITLE
Uptime is not being updated for cached processes on Windows

### ISSUE THREAD

**Issue by gulzarsingh12** [oshi/oshi#579]
I was trying to use the example on Oshi ReadMe (Process information including CPU and memory per process is available). which is printing per processes information like %cpu, %mem etc. but i notice that %cpu is always increasing upto 100%. Once reached 100%, it is not coming down. Just want to know that what is this %cpu means? I have attached the logs and code snippet i am using. I am monitoring multiple java processes in some parent agent process which periodically checks this per process stats like %cpu, %mem etc. If i do some cpu intensive work on on my java processes than it is going upto 100% and then never coming back. This is %cpu is nothing but (100d * kernel time + user time) / uptime  aa per your business logic.

attached log and code snippet:
[logs-analsis-issue.txt](https://github.com/oshi/oshi/files/2261743/logs-analsis-issue.txt)

Please help me to understand the behaviour or confirm if this is bug?

**Comment by dbwiddis** [comment]
Happy to try to help here, but need a bit more info.  What is your operating system (so I know which implementation to debug)?  Any chance you can display a sequence of the raw tick values for kernel, user, and uptime so we can see which one's increasing (or not increasing, if that's the issue).

Note that in a multiprocessor system with a multithreaded process it is possible for a process to exceed 100%.  OSHI caps that number at 100, but it's entirely possible you're on a quad-core system and the "true" value is bouncing around 150% or so (out of a max of 400%).

Also note that the calculation you quoted is the cumulative time of the process so it will be slow to react even if your process ends.  To get a snapshot you'd calculate the difference in kernel and user since the previous collection, and divide by the difference in uptime.

**Comment by gulzarsingh12** [comment]
You can see the screenshots below for more info.
![image](https://user-images.githubusercontent.com/6365923/43726401-a79dccac-99d1-11e8-979e-290c83029374.png)

![image](https://user-images.githubusercontent.com/6365923/43726455-c5e073ae-99d1-11e8-8587-de1264151149.png)

I have printed the additional logs given below as you said:
[logs-analsis-issue2.txt](https://github.com/oshi/oshi/files/2263186/logs-analsis-issue2.txt)


I can try your suggestion to save these values and get difference to find the actual cpu load.

**Also i have one more question**
How to close all the PD queries and performance counter at the shutdown of process. Can you point to some code which i can add as shutdown hook

**Comment by dbwiddis** [comment]
Thanks for the logs.  Uptime is not increasing. This is obviously a bug.  I'll look into it!

The performance counter handles are maintained in a map in the `PerfDataUtil` class.  You can just remove the counters from the map to close them.  That class has its own shutdown hook set up in the constructor, that closes all remaining counters.

Note that there's a single counter for all the processes; the one counter fetches the multiple process instances, so you don't need to individually shut down on a per-process level.

**Comment by dbwiddis** [comment]
OK, found the bug.  In `WindowsOperatingSystem` line 515 there's a block of code that evaluates whether the process it pulled from the cache is a new process or not.  It compares the calculated start time to the stored start time (with 200 ms of wiggle room; it's usually just a few ms).  If it's the same, it assumes the process is the same one.  This logic is working just fine...

But what's not working is that `proc.setUpTime()` is inside that loop and thus isn't being set for a cached process.   That setUpTime() call (line 518) needs to be moved outside of the conditional, updating in all cases. 

Care to submit a PR to fix it? :)
