### ISSUE TITLE
Querying Remote machine via WMI

### ISSUE THREAD

**Issue by suraj1291993** [oshi/oshi#582]
Hai,
Is it possible to query a remote machine using WmiUtil (provided credentials).
Thanks.

**Comment by dbwiddis** [comment]
The WmiUtil was written primarily as a tool for OSHI to use internally rather than a general WMI tool.  

The connection to the other computer is done in the [`IwbemLocator::ConnectServer`](https://docs.microsoft.com/en-us/windows/desktop/api/wbemcli/nf-wbemcli-iwbemlocator-connectserver) method which has been mapped to JNA.  You can specify the other server simply by appending the server address to the namespace (e.g., instead of `root\cimv2` you would use `\otherserver\root\cimv2`).  However, OSHI's call to `ConnectServer` (presently on `WmiUtil.java` line 582) simply nulls the user and password fields.  You'd have to replace that particular call with one which passes credentials.

Note that I've done a significant rewrite of the `WmiUtil` code that you can see[ on my fork on the `wmi` branch](https://github.com/dbwiddis/oshi/commit/51b6a876173e1746e09399e5e32f89430c278797).  This will eventually make its way into OSHI; I'm holding off because I have submitted essentially that same code to the JNA project (the `WbemcliUtil` class) and am waiting on code review/feedback/changes there which I'll echo here.  This doesn't change the need to replace the `null` user credentials noted above, but the new classes have public methods that are more easily overridden by an extended class.  So if you want to leverage OSHI code you might want to wait a week or two for that change, which will make your job a lot easier.

**Comment by suraj1291993** [comment]
I will try your suggestion.
Meanwhile, I am waiting for your changed in oshi.

**Comment by dbwiddis** [comment]
See #585 which updates the OSHI util classes.  The `WbemcliUtil` class handles most of the interface that you need.   To connect to a remote server:
- create your own class which extends WbemcliUtil
- add a method similar to `connectServer()` which passes not only the namespace (which will include the remote server name) but also your user credentials. Note there are multiple ways of passing credentials, so use whichever one you prefer.
- Inside this method you write, pass the additional arguments to `loc.ConnectServer`.
- Override the `queryWMI()` method in your extended class, changing the internal steps to call your new custom `connectServer()` method.

The new code is on master and in the current SNAPSHOT.  I'll probably push a release within the week.

**Comment by suraj1291993** [comment]
Hai,
I tried what you suggested. But I couldn't make it work. I know I am making a silly mistake somewhere, but couldn't narrow it down.
The code I wrote is [here](https://pastebin.com/ZSuiSciV)
I am getting this error when executing.

![image](https://user-images.githubusercontent.com/6951284/44268911-9246d880-a250-11e8-931d-1082e8d8f69f.png)

When I searched around for that error code, they are saying user docent have proper access.
But when I execute any command using WMIC or powershell, I am getting the result. (I hope I can assume there is no problem access)

Thanks

**Comment by dbwiddis** [comment]
I believe the command also needs your domain name.  From [the docs](https://docs.microsoft.com/en-us/windows/desktop/api/wbemcli/nf-wbemcli-iwbemlocator-connectserver),  

> You can use the user principal name (UPN) format, which is Username@DomainName to specify the strUser.

Or you can leaven the user name **without** the domain and specify it in the `strAuthority` field (but don't put it both places).

**Comment by dbwiddis** [comment]
I'd also suggest you [read through the steps here](https://docs.microsoft.com/en-us/windows/desktop/wmisdk/connecting-to-wmi-on-a-remote-computer).   OSHI has implemented much of the C code you see, but it looks like there are some other steps regarding configuring DCOM and firewalls.

**Comment by suraj1291993** [comment]
I looked at that c++ example sometime back. But faced some problems when porting it into java using jna. I will again look into it everything you suggested.
