### ISSUE TITLE
Target JRE for OSHI 4.x

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#618]
Reasons we should move to Java 8:
- Java 8 has been available for over 4 years now and will have long term support. It's worth investing time to leverage its better features.
- Java 7 has been EOL for over 3 years now.  Commercial support will end in July 2019. Usage share dropped from 60% in 2015 to 30% in 2017 and is probably about 15% or lower now.  
- Travis CI no longer supports testing on Oracle Java 7 (linux) and all mac tests are on Java 8.
- Java 11 will be out by the time we would change.  Each new version brings a new testing requirement to catch things like deprecated/removed code and a requirement to work around it. Testing on 8 and 11 only should suffice.
- Java 8 features that would benefit OSHI:
  - Improved HashMap efficiency, good for OSHI's caching.  
  - Lots more Map API goodness.  We already have a `MapUtil` class coded to work around Java 7's map shortcomings.
  - Default methods in interfaces, good to avoid breaking backwards compatibility when adding new features
  - `Optional` class which may be a good candidate for dealing with failed data lookups (the Sensor class comes to mind).
  - String joining. We have a `StringUtil` class to work around this.
  - Streams. Er, ok, no.  But some of the improved collection API methods will make code cleaner.
  - A sane, thread-safe set of Time classes for parsing time strings.

Reasons we should stay on Java 7:
- Someone will comment below that they are using OSHI and still stuck on Java 7.
- Learning to code things the old fashioned way is a fun challenge we'd lose.
- Temptation to overuse Streams.

Other alternatives:
- Maintain `oshi-core` with Java 7 compatibility and basic features (fetching values), and layer improved functionality (selective updating, caching, serialization) with Java 8.

**Comment by cilki** [comment]
I made #619 regarding Java 9 modules before I saw this post. I fully agree with increasing to Java 8 at least. If we want to take advantage of modules, then we'll have to go up one more, which I would also agree with.

**Comment by YoshiEnVerde** [comment]
The break between current Java (9+) and **old** Java (8-) is substantial, and will require a big refactoring effort, if we don't want to produce a half-baked solution.

That said, moving up to Java 8 would be a really good step. Even with the current code, just changing the required version to 8 will be enough.

We have to remember that, user base aside, Java 8 EOL is less than 4 months away for commercial users (With complete EOL by the end of next year).
Yes, we can expect Java 8 to stay with us for a long time, since extended (paid) support is projected to end halfway through next _decade_, but we should be moving *at least* to Java 8.

In fact, once we move past Java 8, we'll have to move straight to Java 11 or 14 (depending on the year we end up releasing that version of OSHI).

One important thing, and this links to #619 too, is that once we're ready to move past Java 8, we can leverage [JEP238 (Multi-Release JAR File)](http://openjdk.java.net/jeps/238) to have a solution still available to those user that still haven't made the jump.
Of course this would be dependent on the acknowledgement that we'd remove that some day.
I'll talk more about this one in the other issue.

**Comment by dbwiddis** [comment]
![image](https://user-images.githubusercontent.com/9291703/46712722-3886dd00-cc07-11e8-9b39-cfa5fd778cd1.png)

**Comment by dbwiddis** [comment]
Further tracking in #658
