### ISSUE TITLE
CPU Temperature always giving 0.0 on Manjaro

### ISSUE THREAD

**Issue by BilalAM** [oshi/oshi#649]
AS the title says , I am using Manjaro and the cpu temperature from `sensor.getCpuTemperature()` is always returning 0.0.
Debugging it shows that this line in` LinuxSensors` : 
`long millidegrees = FileUtil.getLongFromFile(String.format("%s1_input", hwmon));`
is returning 0.0.
Then it tries to get info from this snippet : 
```
 for (int i = 2; i <= 6; i++) {
            millidegrees = FileUtil.getLongFromFile(String.format("%s%d_input", hwmon, i));
            if (millidegrees > 0) {
                sum += millidegrees;
                count++;
            }
}
```
This also fails , 
Then it goes to this : 
` millidegrees = FileUtil.getLongFromFile(String.format("%s", hwmon));`
And also it is giving 0.0.
The main reason is that the temp1_input file it attempts to read is of unknown type and cannot be read (on manjaro only I guess?)

**Alternate Proposed Solution**
After searching the net , I found this possible solution that the cpu temperature is residing inside this file : 
`/sys/class/thermal/thermal_zone0/temp.`
I have edited` LinuxSensors` to also go through this file and check for temperature and it is working now.
https://github.com/BilalAM/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
(Line numbers 105-108 and 147-154)

**Comment by dbwiddis** [comment]
Don't we already read that source as-of #354?  See lines 64-75.  If that's not working, there's a bug.

Can you be more clear on what "can not be read (on manjaro)" means?  Should we be looking for a return value from a file rather than just checking the file's existence?

**Comment by BilalAM** [comment]
Yes you are right it tries to read from this file `/sys/class/hwmon/hwmon2/temp/temp1_input` , this file is present but the weird part is that it is actually throwing `an invalid argument exception` when it reads the file. I tried to access it via cmd with `cat temp1_input `and it is also giving me an invalid argument error. The file is present but it is not being read in any way.
Below is a screenshot of that file in file explorer , notice the 'unknown type'. 
![screenshot_2018-10-10_20-55-10](https://user-images.githubusercontent.com/10103992/46749418-18225580-cccf-11e8-87ed-b1b6b74bba89.png)

**Comment by dbwiddis** [comment]
Unknown type is probably just because it doesn't have an extension.

OSHI checks for the existence of the `hwmon` path file before falling back to the other path that you cited; perhaps we should actually try to read the file and get sensible output as part of that check.   Also I wonder if we should reverse the order of the checks.   

Let me know your thoughts and, as you're in the best position to test a fix, would be happy to see a PR.

**Comment by dbwiddis** [comment]
The `invalid argument` appears to be because no driver is set up to provide read access to that pseudo-file.  In other words, simply seeing the file in the list in the directory is not sufficient to test whether it provides read access to the temperature sensor.   So the `accept()` method of that first check needs to be modified to actually attempt to read the file and get nonzero output.

Or just switch the order of the two file checks as the second path seems more common...

**Comment by BilalAM** [comment]
Umm I maybe wrong on this but on **line 140** you are attempting to read from thermal_zone files like this : 
```
// If temp2..temp6_input doesn't exist, try thermal_zone0
 millidegrees = FileUtil.getLongFromFile(String.format("%s", hwmon));
```
The hwmon variable is` "/sys/class/hwmon/hwmon2/temp"` and this file does not exist anywhere in hwmon* folders , I also checked this on Linux Mint. The temp file that is supposed to be read exists in the `thermal_zone*` folders in the **thermal directory** . Maybe it was supposed to direct to these folders instead of hwmon ? 
Again I maybe wrong on this but this is my observation (and most probably) causing this issue.

**Comment by dbwiddis** [comment]
I see that code on line 130 and it should work as the backup (although it should be simplified, it's silly to `String.format()` only a String.)

But looking at the code, here's what's supposed to happen:
1. On initialization, the `sensorsMap` is populated with the path to the files (one each) for temperature, fan, and voltage (lines 53-63).  
2. The first attempt for temperature is in the `/sys/class/hwmon/hwmon0` (or `hwmon1`, `hwmon2`, etc.) path looking for a file ending with `_input` (specifically `temp_input`). If successful, this path is stored in the map at the `TEMP` key.  Any higher digit paths will overwrite the lower digit ones since I don't think there's any break in that loop.  In your case this would store `/sys/class/hwmon/hwmon2/temp` as the value for the `TEMP` key, because `/sys/class/hwmon/hwmon2/temp1_input` existed.
3. If step 2 is unsuccessful for temperature (line 67), it looks for files in the `/sys/class/thermal/thermal_zone0` (or `thermalzone1`, etc.) path, this time just looking for the `temp` file (lines 68-74).   We know this should work in your case; however, the value stored in step 2 prevents this from happening (the `TEMP` key exists so we exit the conditional at line 67).  So we never store this backup path.
4. In lines 110-126, the code tries to read `/sys/class/hwmon/hwmon2/temp1_input` and if that fails, average whichever of `temp2_input` thru `temp6_input`.  This is where the code is failing, because while the pseudo-file "exists", it is unreadable.
5. If we get to line 130, the above is unsuccessful and we assume the `TEMP` key in the map returns a value from the step 3 fallback, which would be `/sys/class/thermal/thermal_zone0/temp`.  But since step 3 never got executed, this path doesn't work.

Ultimately the root cause of the bug is that we are only checking for existence of the `hwmon` file rather than testing that it produces readable output.

I believe one solution is in the `getSensorFilesFromPath()` override of the `accept()` method, to check that not only does `f` start with `sensorPrefix` and end with `_input` but additionally read a nonzero value from the file.  That would restore the intended logic of the current code.

However, using a single map key here seems sloppy and doesn't give us a good way to easily switch the order the two paths are checked.  We should consider using some more robust method than checking if a key exists to decide which of the 3 different temperature checking methods should be used.  It seems reasonable to check the `thermal_zone0` path first.  Or in any case, not always re-try paths that we know have failed before.

**Comment by dbwiddis** [comment]
FYI, [here is the documentation for the hwmon paths](https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface) and why it looks the way it does.

**Comment by BilalAM** [comment]
> I believe one solution is in the getSensorFilesFromPath() override of the accept() method, to check that not only does f start with sensorPrefix and end with _input but additionally read a nonzero value from the file. That would restore the intended logic of the current code.

Inside the LinuxSensor constructor , the accept logic can be modified to also read an integer value like you have mentioned (But is this robust ? )
```
 // Find any *_input files in that path
                @Override
                public boolean accept(File f) {
                    return f.getName().startsWith(sensorPrefix) && f.getName().endsWith("_input")
                            && FileUtil.getIntFromFile(f.getName()) > 0;
                }
```
P.s It works fine now after this.

**Comment by dbwiddis** [comment]
As far as robustness... not sure!   I think the above probably should work... I'd do one more thing and put a conditional on whether `hwmon.contains()` part of the second path in the `getTemperature()` section so we don't always try to read the failed path.

Can you make a PR?

**Comment by BilalAM** [comment]
> Can you make a PR

Sure I will

> and put a conditional on whether hwmon.contains() part of the second path in the getTemperature() section so we don't always try to read the failed path.

Can you explain it a bit more ?

**Comment by BilalAM** [comment]
the modified `accept()` method is already 'filtering' the files out based on the prefixes and reading values from inside the file

**Comment by dbwiddis** [comment]
I'd like to not execute lines 110-126 if we already know we're using the backup path.  There's no reason to look for "*1_temp" files that we know we're not using.   So wrap a conditional around those lines testing whether the `hwmon` String contains `HWMON` (in which case do the first calculation) or `THERMAL_ZONE` (in which case skip to line 131).  

Also while you're at it, replace `String.format("%s", hwmon)` with just `hwmon`.  :)

**Comment by BilalAM** [comment]
Roger that.
Give me time till tomorrow , I will also make the pr for freebsd sound cards , it's ready and just need some polishing.
