### ISSUE TITLE
Unit test failure on master

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#667]
````
[INFO] Running oshi.json.software.os.OperatingSystemTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.112 s <<< FAILURE! - in oshi.json.software.os.OperatingSystemTest
[ERROR] testGetChildProcesses(oshi.json.software.os.OperatingSystemTest)  Time elapsed: 0.956 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
        at oshi.json.software.os.OperatingSystemTest.testGetChildProcesses(OperatingSystemTest.java:177)

````

on windows 10x64, running as a regular user. Could this be a permissions thing?

**Comment by dbwiddis** [comment]
This could be an order of process/junior test thing.  I think the most recent commit attempts to fix this.  Not sure I put it on snapshot yet tho.

**Comment by spyhunter99** [comment]
i'm building from source

**Comment by dbwiddis** [comment]
Not from the latest source you're not. [Line 177 is now a comment.](https://github.com/oshi/oshi/blob/master/oshi-json/src/test/java/oshi/json/software/os/OperatingSystemTest.java#L177) :)

OperatingSystemTest counted the number of child processes one way and then attempted to count them again another way (which was ultimately the same way but at a different time.)  This worked 99.9% of the time but due to a race condition (child process ending) would sometimes fail.  I noticed recently the 1-child test was failing much more often, likely do to some way that threads are managed in testing.

[This commit](https://github.com/oshi/oshi/commit/2a46bcde85dc038885efc53a4c58ed335303bf7a) attempts to give an even better chance of passing (between the 1 and two different 2+ tests, only one has to pass), so if you pull the latest source or grab from SNAPSHOT it shouldn't fail.

**Comment by dbwiddis** [comment]
By your comment on another issue can I assume this is working for you now?
