### ISSUE TITLE
OSProcess.getStartTime() jumping funnily

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#676]
Hi, I'm seeing slight changes in getStartTime() of an OSProcess over time, e.g. 1541364765715 vs 1541364765732. Some funky calculation behind that causing this jitter?

I tried to find out whether a process with the same PID is actually the same process by matching on the start time. That doesn't work like this then...

Not a bad issue, but I need some way to find out if process with PID x is still the same one as the last process with that PID.

**Comment by dbwiddis** [comment]
Yes there is a funky calculation.  Which OS?  Off the top of my head I think you can call it equal if within 200 ms...

**Comment by stefan-reich** [comment]
I saw this on both Linux and Windows.

Now I'm matching on this which should be fine for almost all cases:

`p.getProcessID() + "|" + p.getName() + "|" + p.getPath();`

In fact, I'm only using this for calculating per-process CPU usage, so any errors in this logic will iron themselves out after the next calculation anyway.

Thanks :)

**Comment by stefan-reich** [comment]
BTW I have a very nice process list now: ![Screenshot](http://ai1.space/1004590/raw/1101419)

[Source](http://tinybrain.de/1019486)

**Comment by dbwiddis** [comment]
Nice Process List!  But how do you know the same process name/path didn't shut down and start up again with the same PID?  (Other than statistics as that has to be exceedingly rare!)

The problem we have with start time is that most OS's don't have it (but it's great, as you've described, for trying to correlate the same process).  We have to calculate it from the up time.  And that requires knowing what time it is now.  Of course, a few milliseconds can elapse since grabbing when "now" is and pulling the start time, and that's what you're seeing.

On Linux, there is no caching so the value is re-calculated every cycle.  The `/proc/pid/stat` pseudo-file we parse does include a field for start time (in jiffies, not milliseconds, which requires a Boot time, which can be up to 5 ms off based on rounding in the initial calculation) and it might be preferable to actually use that value (assuming our HZ calculation is good).  Or we can cache the values and not change start time if it hasn't changed significantly.   I'm going to reopen this Issue while evaluating whether caching or using the stored field is preferable to what we do now.

On Windows, we do cache start times and consider it a new process if the start time varies by more than 200ms, but any smaller difference should keep the same (cached) start time.  This is the behavior I might consider implementing on Linux.  Are you sure you saw small start time variations in Windows? Or did you see slightly larger than 200ms so I should expand that 200ms buffer?

One other thing you can consider in your "same process" matching. You can store the last time you grabbed the list, and any start times that are after that would represent a new process.  (Or store your up time between polls of the process and consider up time below that value, a more accurate calculation, to be a new process.)

**Comment by dbwiddis** [comment]
Note to self or anyone else who wants to take a crack at this: A comprehensive fix for this should include consistent behavior (e.g., caching with 200ms difference or similar) across all OS's, and #590 should be completed at the same time.
