### ISSUE TITLE
CentralProcessor.getSystemUpTIme is no longer accurate.

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#684]
running off of 3.10-snapshot on windows 12 server x64.  It some cases, i was seeing it report something like 15 minutes uptime, however the system had been running for several hours. Where does oshi get system boot time/uptime from? It is effected by changes to the system clock by chance?

windows 10 can also report strange values for this, but they correlate to what task manager shows and all the other mechanisms available via command line. it probably only resets itself after a hard shutdown or something, the "normal" shutdown/power off is some kind of hibernation mechanism design to speed up boot time.

**Comment by dbwiddis** [comment]
OSHI gets uptime from the [GetTickCount64](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-gettickcount64) function.  OSHI does do a version check for Major version >=6 (WinNT) to use this method rather than the 32-bit [GetTickCount](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-gettickcount).

In theory this should match the sum of the Idle, Kernel, User, and IRQ times of `getSystemCpuLoadTicks()`.

We could look at using a PerfMon counter (`\System\System UpTime`) or manually reading the same counter key from the registry, but I don't think that would give us any different value than the built-in function.

Not sure how to further troubleshoot this, unless Win12 Server has a different time function we can use.

**Comment by dbwiddis** [comment]
Have you looked into this any more to compare the results of the various methods/counters?

**Comment by spyhunter99** [comment]
no unfortunately time got away from me on this one. Close if you want to. Soonest i can look at it is monday

**Comment by spyhunter99** [comment]
looks like it was my fault. Uptime is time in seconds, no milliseconds and I was calculating a system boot timestamp in ms.
