### ISSUE TITLE
fresh build failure on master, testPowerSource

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#706]
java.lang.AssertionError
        at oshi.hardware.PowerSourceTest.testPowerSource(PowerSourceTest.java:39)

**Comment by dbwiddis** [comment]
Looks like the failing test is `assertTrue(ps.getRemainingCapacity() >= 0 && ps.getRemainingCapacity() <= 1);`.   Can you print out the power source stats so we know which one? (And which OS you're using it on.)

**Comment by spyhunter99** [comment]
java.lang.AssertionError: returned value out of bounds 1.361545538178473
        at oshi.hardware.PowerSourceTest.testPowerSource(PowerSourceTest.java:39)

windows 10 x64 enterprise

**Comment by dbwiddis** [comment]
Looks like Windows is returning a remaining capacity greater than its max capacity.  

OSHI gets this info from [CallNtPowerInformation](https://docs.microsoft.com/en-us/windows/desktop/api/powerbase/nf-powerbase-callntpowerinformation) using the SystemBatteryState (5) information level which populates a `SYSTEM_BATTERY_STATE` structure.  Apparently it's possible to have a higher remaining capacity than max capacity, so that portion of the test should be removed.

**Comment by spyhunter99** [comment]
must be a "feature"

**Comment by dbwiddis** [comment]
Well the obvious solution is to discharge your battery some before building OSHI.  :grin:   There are other sources of Windows power information like using [DeviceIoControl](https://docs.microsoft.com/en-us/windows/desktop/api/ioapiset/nf-ioapiset-deviceiocontrol) with the [IOCTL_BATTERY_QUERY_INFORMATION](https://docs.microsoft.com/en-us/windows/desktop/power/ioctl-battery-query-information) to produce a [BATTERY_INFORMATION](https://docs.microsoft.com/en-us/windows/desktop/power/battery-information-str) structure, but I would guess they would probably give the same result.  So ultimately we just need to reduce the test.
