### ISSUE TITLE
WmiUtil#setWmiTimeout call on a non-windows system throws an exception

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#711]
Not sure how much of a valid issue this is, but in my application, I use oshi on a few different operating systems, namely Windows and CentOS. On Windows, I have to set the WMI timeout to something less than infinity as sometimes, wmi queries will fail to return. This particularlly happens when the system is under high load and is rather unfortunate. 

Anyhow, so my class looks something like this.
    
    static {
        WmiUtil.setWmiTimeout(5000);
    }

On a whim, I retested my code on CentOS and found that this throws up with some kind of native error message. I don't recall the specifics but it was either a unsatisfied link error or something similar. To work around the issue, I can wrap it in a try/catch or to check the OS first before calling the WmiUtil method. I think it's the static initializer of WmiUtil throwing, not the `setTimeout` method. 

I'm not sure if this is something that should be fixed within oshi, but I just wanted to document the issue in case anyone else runs into it and perhaps suggest some javadoc on the WmiUtil class as a warning

**Comment by dbwiddis** [comment]
Given that the `WmiUtil` class lives inside a package specifying Windows, I do think it's reasonable to leave it to the user to only call this on the correct OS.  Rather than catching an exception I'd suggest you use `SystemInfo.getCurrentPlatformEnum()` to test the OS first.  

We have other code that's only imported on one OS, such as `getHz()` on Linux.  Not sure documenting each one as OS-specific is needed, though, given the package names.  But it makes sense to document it somewhere.
