### ISSUE TITLE
Dependabot added

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#744]
@dblock @dbwiddis Heads up!  I've added 'oshi' to dependabot.  This will replace how we generally raise commits / pull requests for dependency updates.  I've been testing this on another project (psi probe) and it's worked out really well.  It will create a single commit per version it believes needs updated.  That will be a branch that I believe is setup to auto delete once merged.  The tool does have more access writes than we would normally give out but no more than a typical contributor.  If for some reason it behaves incorrectly and violates what we consider its approved usage (ie creating a branch, raising a pull request, nothing more), then we can easily disable it.

**Comment by dbwiddis** [comment]
I just saw all the PRs come through!   Cool.  Is it configurable?  There are a few dependencies we are intentionally behind on:
- javax.json 1.1.4 requires Java 8, and we're still supporting Java 7.  And when we do bump to 8 we'll probably be killing that dependency (but enabling users to easily create json from POJO via Jackson if they desire).
- wagon-git 2.0.4 is buggy since forever and 2.0.3 works.

I have been running maven's version check plugin every so often (particularly before a release) and it seems a bit less spammy to update all dependencies at ones instead of than a bunch of commits (mostly for build tools vs. actual dependencies).

**Comment by dbwiddis** [comment]
Cool, closing the PR for a version I don't want auto-configures it to not notify again, and tells you commands to type to suppress further minor and major versions.   The slight annoyance of keeping build tools updated in real-time is balanced by the benefits of actually writing down in an PR why we're staying on older versions.

**Comment by dbwiddis** [comment]
So does Dependabot have a badge for the readme?  I'm missing my "VersionEye" badge that told me all my dependencies were up to date. 😄

**Comment by dbwiddis** [comment]
Badges are in the works! https://github.com/dependabot/feedback/issues/6

**Comment by hazendaz** [comment]
Nice!  I'm missing that as well.

**Comment by hazendaz** [comment]
What is impressing me even more is that in some cases the versions-maven-plugin has clearly failed to tell me there are new versions.  I had noticed that from time to time but in a super pom I have laying around I thought I had cleared all really old items.  It just found one such item.

**Comment by dbwiddis** [comment]
It looks like it runs daily with 5 per day and no more than 10 total... but we can configure that. :)
