### ISSUE TITLE
GUI based oshi

### ISSUE THREAD

**Issue by BilalAM** [oshi/oshi#807]
Any chance for a gui using oshi like other tools out there ? 
Considering the amount of info oshi can get , i think it would be a nice little addition . Just my two cents though.

**Comment by dbwiddis** [comment]
The chance of a GUI is directly proportional to the motivation of other people to develop one.  :)  

Personally I'd love to see something similar to the Windows Task Manager or equivalent on other OS's, but have no plans to write one myself.

**Comment by cilki** [comment]
I'm pretty good with JavaFX, but I'm not sure how much time I would have to work on such a project currently. Here are two questions:

- What framework would be most appropriate? (JavaFX, Swing, Electron, etc...)
- Should it be an official member of the OSHI organization or a standalone project?

 I'm definitely interested though, since my primary usage of OSHI is very similar.

**Comment by BilalAM** [comment]
I was thinking and planning about doing this on JavaFX for the last couple of days , if thats the case then i'll start working on it over the weekend and will let you guys know if the results are positive.

@cilki JavaFX would be best i guess (i used it for my final year research project and it really is a huge improvement over swing..my opinion though..).
As for the decision of it being an official member of OSHI or standalone , thats @dbwiddis decision obviously ;)

**Comment by cilki** [comment]
@BilalAM I can get a JavaFX + Gradle skeleton project up easily. I would just need to know where to put it and what to call it.

**Comment by dbwiddis** [comment]
I'll defer to @cilki on JavaFX choice, although I think a web-based GUI enabled by Graphite would also be cool.

More than happy to have an official oshi project in the group outside of `-core`, similar to the current `oshi-demo` artifact.  Perhaps `oshi-javafx`?  Lesson learned from `oshi-json`, though, needs to better integrate or auto-generate a lot of the "what info is available" stuff.   Let me know if you want me to create you a new artifact.

**Comment by cilki** [comment]
The usage where Graphite seems to really shine is if you wanted to see metrics from many machines (over time) in one place. There's no reason this couldn't be done, but a simple desktop application acting as a frontend for OSHI's data would be much easier for the user in the use-case I'm imagining:

- Users need a "temporary" view of one system
- Users don't want to setup the additional infrastructure that Graphite requires (just want to download and run the application quickly)

I think a simple JavaFX application would be much easier to implement and would suit more people. 
`oshi-javafx` is a good name for the artifact and we can always add a more user-friendly name later if someone comes up with something good.

**Comment by dbwiddis** [comment]
I'd suggest starting with oshi-javafx right here, then. You don't need a separate project set up, and you can immediately commit.  This has the advantage of staying in sync with the main project (identical release versions).

Alternately we can set up a new github project under the `oshi` org (like the `oshi5` site) where the project can develop on its own pace and with its own releases.

Which do you think is better?

**Comment by cilki** [comment]
I like the idea of keeping the versions identical, but this project is strictly a consumer of OSHI so it really belongs in its own repository. Separating them also has the benefit that the commit histories won't be intertwined forever. Also it gives us the option to easily abandon the project just in case it doesn't turn out.

I put together a working project base with Gradle, but I can convert it to Maven if that's what you need for release (or consistency) purposes. (Although I would want you to appreciate that the entire build file is only 35 lines first).

**Comment by dbwiddis** [comment]
I'll set you up a new repo.  Use whatever build you want as long as the README documents how to do it!

**Comment by dbwiddis** [comment]
But I need a name. :)

**Comment by cilki** [comment]
I think `oshi/oshi.javafx` is a fine working name until someone thinks of something better. Github repos can be renamed easily.

**Comment by dbwiddis** [comment]
Have fun.  https://github.com/oshi/oshi.javafx

**Comment by BilalAM** [comment]
Is it possible if it would be for maven ?

**Comment by cilki** [comment]
@BilalAM I prefer Gradle for new projects because the build files are **much** simpler and it downloads itself automatically. Just do `./gradlew run` from the repository's root directory to build and launch the application. That already works on every platform with just 30 lines in the `build.gradle`.

I don't have any experience writing `pom.xml`s, so if the majority of contributors still want Maven, someone else will have to come up with one.

What are the reasons to stay with Maven?

**Comment by dbwiddis** [comment]
The maven wrapper has the same `./mvnw <command>` option that you describe.   And a basic pom.xml isn't very challenging at all.  Here's [OSHI's original pom, only 32 lines of the mandatory stuff](https://github.com/oshi/oshi/blob/8d16d602e59a21a31f65e8b3ce069f0ef923e771/pom.xml). Then some plugins added... The "build files much simpler" is primarily a programming language style syntax vs. XML.  

Don't have a strong opinion on a new project, though... I will say that having worked extensively on a project at a previous employer with a maven build cycle that I knew and could run from my IDE... when the code guy switched to Gradle because he liked it better, it never worked for me.   My IDE didn't integrate well with it and I had to resort to his command line instructions, which always gave me errors and he said "oh, you have to do this too" all the time.   Of course, I'm an old curmudgeon set in my ways.

But hey, new project?  Set it up how you like. Just thoroughly document what people need to do to build/run.  If I can run it, great. If not, I'll file issue after issue until you fix it ;)

**Comment by cilki** [comment]
@dbwiddis Good points. We'll do a trial run and see how it goes.

**Comment by spyhunter99** [comment]
Fair warning, opinions ahead. 

More than a decade worth of plugin development and easy deployment anywhere. Pom's are simple and there's tons of examples. Debugging gradle scripts is miserable and is basically worse than ant. Everything is easier with maven, except for android. someone ported the gradlew wrapper for maven too. i think it's called mvnw. Gradle, imo, is closer to ant. Yes you can build a java project (or whatever) with it, but is it the best solution? 

my experience with gradle has been terrible. i've written thousands of lines of gradle scripts to replicate what maven does out of the box. Gradle, at least in the past, was way slower that maven on a clean install vs clean build. It's better now from what i understand

finally the owner of gradle has had some interesting blog posts. mostly stating that, yeah we know this is broken but we'll get to it when we get to it. 

i'd rather not write code, to write code.  spending time debugging the build system is a waste of my time frankly. The only ide really has any decent support for gradle is intellij. More pay products. Gradle is commercial too. I get emails all the time from them offering training and commercial support. You shouldn't need training or commercial support for a build system.

Maven on the other hand, eclipse, netbeans, etc are all free and open source. There's no agenda to push a certain bit of tech or build system or requirement for buying something for commercial use

Finally, publishing to https://oss.sonatype.org/ is still painful with gradle. Keep in mind the requirements, 

- the artifact itself
- javadoc jars
- source jars
- pom files that are populated with their minimums, name, description, website, url, scm location, authors, and probably a few others.
- digital signatures on everything
- digital hashes on everything

try doing all that with gradle and you'll have a long build script.

to mitigate this, everyone now publishes to jcenter, which is also a for profit company (nothing wrong with this). They place a few limitations on you and then you have to pay past that. At one point, you had to upload your private gpg key to them in order to handle the signing. No thank you.

**Comment by cilki** [comment]
@spyhunter99 Next you'll be telling me you don't want to write code that writes code to write your code ;)

I meant my question to be more specific to this project (which build system will be best for this project in the short term and long term?). Publishing to an artifact repository isn't even related to this project because no one wants to download their applications from Maven Central. That's what Github releases are for. (Let me know if there actually is a reason to do this).

Respectfully, I don't find any of your points convincing. There's nothing very complicated/unconventional going on in this build, so the question really is which tool is easier to setup and maintain. I have much more experience with Gradle, so it took me less than 15 minutes to fully set this project up (only thing that's missing is the Github release plugin). In my experience with the recent versions of Gradle, IDE support is on-par, it's quite fast, and the declarative DSL is easy to use.

The one issue I have with using Gradle is that it obviously breaks consistency with the rest of OSHI. I value consistency quite a bit, and since I'm new here and in no position to assert decisions, I won't be disappointed to convert the build to Maven. Although it sounds like you could write that pom more efficiently than me.

**Comment by dbwiddis** [comment]
I think these last two posts have pretty much outlined the choice.

OSHI is primarily a library meant to be included in other programs.   That makes the Central Repository a natural home for it, and Maven a natural choice for publishing there.  The envisioned GUI is an app meant to be directly downloaded, not included as a GUI.  That means it can be published anywhere.

I don't think this is an irreversible choice, and I favor whichever build system gets the code written and out there in the community the fastest.  I don't think it's a huge hurdle switching between systems.

If this is eventually included as a module/artifact of OSHI, the parenting nature of the pom makes it a natural choice to use maven.  [This is the pom](https://github.com/oshi/oshi/blob/master/oshi-demo/pom.xml) for the `oshi-demo` artifact that includes `oshi-core` as a dependency.  Pretty simple.  It'll get built along with the main project.  If there's a reason to create a separate build script, I'm ok with that too...

**Comment by dbwiddis** [comment]
Hey @cilki how's the GUI coming?  I am nearing the point where I might consider playing with building one, but don't want to waste effort if you have a skeleton built somewhere that I can put some meat on the bones....

**Comment by hazendaz** [comment]
Latest psi probe release has link on that page now.  It's just a data dump right now.  You can get the latest psi probe war from the git repo to check it out.  Its jsp though :(

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Correct on points.  Psi probe isnt likely what you'd want.  It might leverage oshi UI though...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BilalAM** [comment]
> Fast-changing variable fields like CPU usage, network bandwidth, interrupts, etc. A line chart with last-second, and periodic moving averages (Metrics, anyone?) would work well here.

I remember when I was creating my final year project , i had to basically show cpu utilization % of 'routers' that my project was based on . I was searching the internet far and wide and stumbled across oshi . I used oshi to get the percent utilization of my CPU and displayed it on a line chart using JavaFX . 
My interest in this project started from that day lol . 
Your comment reminded me of that @dbwiddis :) .

Here is the screenshot of it 
![Screenshot from 2018-05-10 00-52-12](https://user-images.githubusercontent.com/10103992/63883542-d802b900-c9ed-11e9-8b60-ea6014992ee5.png)

**Comment by dbwiddis** [comment]
Perfecct example of a fast-changing number that should be a line chart, and a slow-changing memory consuption that's better in a pie chart or equivalent! :)

**Comment by BilalAM** [comment]
@dbwiddis i was "trying" to create a monitoring type chart . Notice the word "trying" :)

**Comment by dbwiddis** [comment]
So, since I'm quarantined I have nothing else to do.  I decided to try to learn Swing today.  Here's the result of a couple hours of playing around...

![image](https://user-images.githubusercontent.com/9291703/76722358-79d6c280-6700-11ea-80a3-fdb69181f3b8.png)

![image](https://user-images.githubusercontent.com/9291703/76722376-94a93700-6700-11ea-8f12-52b96076d777.png)

**Comment by dbwiddis** [comment]
![image](https://user-images.githubusercontent.com/9291703/76724746-46e4fc80-6709-11ea-9ecd-0b810733ce5a.png)

**Comment by dblock** [comment]
Nice! Maybe you want to learn [Electron](https://www.electronjs.org/) and [build a mac app](https://github.com/cuba-labs/java-electron-tutorial)? :)

**Comment by spyhunter99** [comment]
just checked it out, looks pretty good!
although i'd suggest dividing process level cpu data by the quantity of cpu cores. mine reads something like 600% idle

**Comment by dbwiddis** [comment]
Yep, but I'm [trying to replicate top](https://unix.stackexchange.com/questions/145247/understanding-cpu-while-running-top-command), and if you've got a multithreaded process (or Idle) it is indeed possible to exceed 100% CPU.  The "SystemTime" of the idle process exceeds the up time!

Of course Windows Task Manager does the division by logical cores. :)

The GUI is meant as a demo/blueprint that others can tweak if they like.

**Comment by dbwiddis** [comment]
I just tweaked my current update #1147 to do the logical processor division on Windows (to match task manager) and also not bother to display pid 0 (Idle) on Windows, either. :)

**Comment by dbwiddis** [comment]
Changed the above to defaults and added some radio buttons to change the calculation (and sort field) on-the-fly. :)
