### ISSUE TITLE
ExecutingCommand#runNative does not work for Windows commands without executable

### ISSUE THREAD

**Issue by BilalAM** [oshi/oshi#812]
I tested ExecutingCommand.java on windows but it was not showing any results , snooping around the code I found out that it needs to have **cmd.exe /c** appended before the actual command.

**Comment by dbwiddis** [comment]
Good observation but I'm not sure we should change this (although updating the JavaDoc would be helpful).  

We try to avoid command lines whenever possible and manage do do so in Windows in all but one case.  Our Util functions are not officially part of the API and are not meant to handle all cases.  In particular, the string version that you submitted the change on doesn't handle "arguments with spaces" which requires the String-array based version.  So to properly fix it we should fix the array version.  But then if the user has already specified it we should not add it, or we end up doing "cmd.exe /c cmd.exe /c command"...

The `cmd.exe /c` prefix is not needed for command lines associated with a program that exists on the PATH.   OSHI's only use of this method is for `route` which executes `route.exe` without a problem.   It is needed for built-in windows commands like `echo` that don't run a program, but this can be addressed in code when calling these functions, as we do in `ExecutingCommandTest()`:
```
String ECHO = SystemInfo.getCurrentPlatformEnum().equals(PlatformEnum.WINDOWS)
            ? "cmd.exe /C echo Test" : "echo Test";
```

Ultimately, `ExecutingCommand.runNative()` is simply a convenience front-end method to `Runtime.getRuntime().exec()` that captures the output in a list, and I think I'd prefer to keep it that way rather than try to deal with adding `cmd` for the very few Windows commands that need it.

That said, the JavaDoc should certainly note this requirement for "Windows commands not associated with an executable program."

**Comment by BilalAM** [comment]
> ...Our Util functions are not officially part of the API and are not meant to handle all cases...

Oh if thats the case then you are right about the rest if it is used internally in the API and not to be used by the general user . I thought that the utils classes are also to be used by the general user but you cleared it up nicely :) 
I might as well delete the PR though.
Also if this is the case then mention it in the javadocs for it so that unsuspecting users can see it

**Comment by dbwiddis** [comment]
Updated javadoc in [this commit](https://github.com/oshi/oshi/commit/3ee51ad5e60351d4067c0e25ce03a59293fc9c9b).
