### ISSUE TITLE
Updating from 3.12.1 to 3.13.2 how to set Wmi timeouts?

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#885]
In v3.12.1, setting the Wmi query timeout was

    WmiUtil.setWmiTimeout(500); //in ms

In v3.13.2, this was designed into a singleton pattern, sort of. It's not clear to me how on how to use it and looking at the code, it's not a standard singleton interface.
My initial thought was this

````
WmiQueryHandler. instance = WmiQueryHandler.createInstance();
instance.setWmiTime(500);
WmiQueryHandler.setInstanceClass(instance);
````

However this will not compile. The method is expecting a class, not an instance. So I have to subclass WmiQueryHandler just to set the timeout? If that's the case, it's pointless to have a `setWmiTimeout` method as there's no way to access a WmiQueryHandler instance outside of the `createInstance` method. After searching the code base, it always calls createInstance. 

So the only option here is to subclass `WmiQueryHandler` correct? If that's the case, I'd suggest making at least the `wmiTimeout` field protected instead of private, then just remove the setTimeout method.

**Comment by dbwiddis** [comment]
I'm a bit confused here.  `wmiTimeout` is a standard attribute with a `public` getter and setter
```
    public void setWmiTimeout(int wmiTimeout) {
        this.wmiTimeout = wmiTimeout;
    }
```
So this should work on an instance.

**Comment by spyhunter99** [comment]
But there is no longer a getInstance method. It's not a singleton class. A singleton is implies that there is exactly one instance of the class. There's only a setInstance(class) or createInstance. The instance is never cached within the WmiQueryHandler.

Take `WindowsComputerSystem` for example, there is no way to get a reference to the WmiQueryHandler. So from my code, there's no way to call setWmiTimeout.

**Comment by dbwiddis** [comment]
This compiles for me?
```
        WmiQueryHandler wmiQueryHandler = WmiQueryHandler.createInstance();
        wmiQueryHandler.setWmiTimeout(500);
```

**Comment by dbwiddis** [comment]
Oh, wait... I get the issue.  While the OSHI code, and anyone writing custom code using the WMI util classes can access the handler and set the timeout, there's no way for someone just using OSHI to set a global value of the timeout that persists across instances (since they all disappear after use).

A few thoughts:
 - Create a config class with WMI Timeout and other key parameters in it and always read this in by default
 - Subclass the WmiQuery handler and override the `getWmiTimeout()` method to return a constant of your choosing; then `setInstanceClass()` to your subclass

**Comment by dbwiddis** [comment]
So define a new class and do this:
```
public class WmiQueryHandlerWithTimeout extends WmiQueryHandler {

    @Override
    public int getWmiTimeout() {
        return 500;
    }
}
```
Then when initializing your code:
```
WmiQueryHandler.createInstance().setInstanceClass(new WmiQueryHandlerWithTimeout());
```
Then all future `createInstance()` calls will generate an instance of the subclass, with the override.

**Comment by spyhunter99** [comment]
I ended up subclassing and it appears to be working. setTimeout is still pointless as is. Maybe mark it as deprecated or something

**Comment by dbwiddis** [comment]
It's not pointless -- it's a designed-in feature of a util class, permitting the writer of a query to set a different timeout for each query.  One might want a timeout only on one particular type of query, for example.  

You do have a point that there should be a better way of setting a global timeout than subclassing, which is why I mentioned a global config (probably a good idea for many reasons) or the ability to set a default (for all new instances) that can be overridden.  (The subclass method would overwrite any other customizations, so it's a temporary workaround until we get this designed right.)

**Comment by dbwiddis** [comment]
See discussion on #888 which I hope will fix this... would like your input there.

**Comment by dbwiddis** [comment]
After toying with the idea of a global config, I'm back to thinking that changing the setting on the `WmiQueryHandler` itself is the best option, and your original suggestion to make the `wmiTimeout` method `protected` rather than private.  It will still require subclassing, but will allow your subclass to easily set that timeout on instantiation.

I still want to keep the ability to set/override the timeout on a per-query basis, even if it's currently unused in OSHI.

Do you want to submit that PR?  Can also do it on the 3.13.X branch (I should have done it before releasing a few days ago...)

**Comment by dbwiddis** [comment]
Actually... we don't need the `protected` since we have the setter.  Can we just do this?
```
public class WmiQueryHandlerWithTimeout extends WmiQueryHandler {
    public WmiQueryHandlerWithTimeout() {
        setWmiTimeout(500);
    }
}
```
Followed by:
```
WmiQueryHandler.setInstanceClass(WmiQueryHandlerWithTimeout.class);
```
This will always re-set the timeout when a new handler is instantiated.

**Comment by cilki** [comment]
We're trying to avoid subclassing just to set the timeout with #888 right? If so, `WmiQueryHandler` needs to have a reference to a `SystemInfo` or `Properties` so it can find the timeout value. And that's impossible since it's a singleton :worried:

**Comment by spyhunter99** [comment]
it's not really a singleton, it's a factory class. A singleton would be 1 instance of the WmiQueryHandler per JVM (ish).

**Comment by dbwiddis** [comment]
I'm leaning against the global config from a code design since it's really only going to be used by a single class, and requires making the `Properties` object globally accessible to be useful, which introduces thread safety issues if static, or passing it around as an argument when creating the objects in the tree under `SystemInfo`.

But I'm also leaning towards it because it does have a global (at least on Windows) impact on all WMI queries across multiple classes. Arguably it's each of these classes that *could* set the timeout themselves if they had access to the config.

The current class *is* trying to follow the factory pattern, and customizing the object produced by the factory (subclassing) is allegedly the correct way to handle this.  You want to introduce a static variable somewhere (either properties or on the handler class) that potentially introduces thread safety issues.  

Ultimately I don't know the best way to handle it.   I know the current design allows it with a trivial subclass object/factory template that's already intended to allow more logging customization and other "default" WMI behavior, and I'm not sure why that's so much worse than adding a static variable to tweak the default.

**Comment by spyhunter99** [comment]
ehh leave it as is. it's usable.

**Comment by dbwiddis** [comment]
That's my near term solution in any case.  I do think we'll eventually have a global config but we don't need to create one just for this.

**Comment by dbwiddis** [comment]
Closing this as there is a mechanism (subclassing per [this comment](https://github.com/oshi/oshi/issues/885#issuecomment-500081768)) for doing this on-the-fly, and I'll include a global default (read-only startup-only) in a global config tracked in #888.
