### ISSUE TITLE
Dependency resolution on gradle gives wrong JNA version

### ISSUE THREAD

**Issue by srowatt** [oshi/oshi#892]
When trying to obtain the processor id on a mac running JDK 11.0.3 using the following code
```
final SystemInfo systemInfo = new SystemInfo();
final String id = systemInfo.getHardware().getProcessor().getProcessorID();
```
I got the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/SystemB$Timeval
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:59)
	......
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.mac.SystemB$Timeval
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
```
I included Oshi in my project using gradle i.e.
```
compile("com.github.oshi:oshi-dist:3.13.3") 
```
and that transitively imports the JNA 4.5.2 libs i.e.
```
compile("net.java.dev.jna:jna:4.5.2")
compile("net.java.dev.jna:jna-platform:4.5.2")
```
To get it to work I had to override the JNA libs to use 5.3.1 using the following build.gradle 
```
compile("com.github.oshi:oshi-dist:3.13.3") {
        exclude group: "net.java.dev", module: "jna"
        exclude group: "net.java.dev", module: "jna-platform"
}
compile("net.java.dev.jna:jna:5.3.1")
compile("net.java.dev.jna:jna-platform:5.3.1")
```
This looks like a potential bug and should Oshi be using JNA 5.x libs instead of 4.x libs?

**Comment by dbwiddis** [comment]
I'm not that familiar with gradle.  [OSHI publishes its dependencies via POM](https://search.maven.org/artifact/com.github.oshi/oshi-core/3.13.3/jar), and it properly points to JNA 5.3.1.  I checked the [download zip at oshi-dist](https://search.maven.org/artifact/com.github.oshi/oshi-dist/3.13.3/pom), and it also includes the JNA 5.3.1 jars.

I'm curious why you are compiling `oshi-dist` rather than `oshi-core`.  The `dist` is primarily just a mechanism to have downloadable zip or tar files, but for dependency resolution you should use `oshi-core`.

Looking at the docs for [Gradle dependency resolution](https://docs.gradle.org/current/userguide/introduction_dependency_management.html#sec:dependency_resolution), I note it is similar to Maven in preferring projects earlier in the order:
> Modules from earlier repositories are preferred over modules in later repositories.

It is likely that you have some other dependency in your project that depends on 4.X, and it is loaded before OSHI.  You might try including OSHI closer to the top of your build.  Or, as you've pointed out, you can explicitly define the JNA version. 
```
	<properties>
		<jna.version>5.3.1</jna.version>
		<main.basedir>${project.parent.basedir}</main.basedir>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>${jna.version}</version>
		</dependency>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna-platform</artifactId>
			<version>${jna.version}</version>
		</dependency>
	</dependencies>
```

**Comment by dbwiddis** [comment]
Hey @srowatt, were you able to resolve this?

To recap:
 - OSHI properly imports 5.3.1
 - You're likely getting 4.x from another dependency.
 - You depend on `oshi-dist` which puts the jna dependencies down 2 levels.  If gradle does the same "do all first level dependencies first, then second level, etc." that contributes to a lower priority.  You should:
   - Use `oshi-core` as the dependency, unless you need JSON; then use `oshi-json` instead
   - Put OSHI higher up in the list

Closing this since I've triple-checked OSHI's setup. Feel free to re-open if you think there's something we should change.

**Comment by ABoat365** [comment]
Maybe use "spring boot", see "spring-boot-dependencies-2.1.3.RELEASE.pom" line 107.
