### ISSUE TITLE
DetectVM - Wrong comparison of result

### ISSUE THREAD

**Issue by jgueth** [oshi/oshi#908]
In the class **DetectVM** (package _oshi.demo_), the method _findOuiByMacAddressIfPossible_ returns an empty string if no entry was found in the _vmMacAddressOUI_ map. However, the result is checked to null (not empty String), which means that the method always ends after the MAC address check.

**Comment by dbwiddis** [comment]
Not only the MAC check, but the first MAC check.  Looks like the error was introduced in #872.  Can you submit a PR to fix, or should I toss it out to first-timers?

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [DetectVM.java](https://github.com/oshi/oshi/blob/fa069ec975c6c06014b895c390ffb111bbf74c9b/oshi-demo/src/main/java/oshi/demo/DetectVM.java#L87) class.  At line 87, the code only checks for a non null string. This is a bug, because the code should also check for an empty string.
- [ ] Alter the code to additionally check for an empty String.
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by shannondavid** [comment]
Hi @dbwiddis. I haven't contributed to open source before and would like to give it a go. Do you mind if I contribute?

**Comment by yzhang2907** [comment]
It has been done, this is my first time contributing to OS besides adding my name in the first-contribution github tutorial. It is PR #909. Thank you!

**Comment by dbwiddis** [comment]
Hi, sorry @shannondavid  it looks like @yzhang2907 beat you to the punch here!  I can suggest a slightly more challenging issue for you to work on if you'd still like to help!

**Comment by shannondavid** [comment]
@dbwiddis I'd love to!

**Comment by dbwiddis** [comment]
@shannondavid check out #877.  [This comment covers the basics](https://github.com/oshi/oshi/issues/877#issuecomment-498683461) of what to do, scroll down to the end for the better Windows solution using event log.

**Comment by dbwiddis** [comment]
Fixed in #909

**Comment by shannondavid** [comment]
got it! checking out #877 now
