### ISSUE TITLE
Javadoc @author tag is unnecessary and possibly harmful

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#927]
We should [stop using the `@author` tag](https://www.databasesandlife.com/dont-use-the-author-javadoc-tag/).  It's [not included as part of the generated javadoc](https://www.vojtechruzicka.com/stop-using-javadoc-author-tag/), and we haven't bothered updating it when making large changes to the code so in [most cases it's inaccurate](https://implementsblog.com/2018/02/16/dont-use-the-author-javadoc-tag/).  Should we ever wish to relicense under [Apache, it's required to remove them](https://blog.mkowalski.net/2016/12/29/still-using-author-please-dont/).

Git history tracks all our contributions.

No need to mass edit files to remove the tag if that's the only change, but if you're making other changes to a file, kill the `@author` tag while you're at it.  Leaving this issue open as a reminder until the number of edits is small enough for a final cleanup.

**Comment by cilki** [comment]
What are your thoughts on the `@since` tag?

**Comment by dbwiddis** [comment]
It's not harmful, but I don't think it's really needed either.

**Comment by spyhunter99** [comment]
mm i dont think the author tag is enforced. it's everywhere in asf repos

**Comment by dbwiddis** [comment]
Well, enforced or not, we don't need it and the multiple linked articles above explain why :)

**Comment by hazendaz** [comment]
Just my 2 cents.

I agree, use of 'at author' is bad for quite a number of reasons.  Many open source projects have been removing it.  There is a point where you need to blame the code for an issue not the original author(s).  Plus git provies blame of the commit directly which still is nicer that calling a person out on something they did at some point in time.  "Blame the code not the author".  We have long stopped using it at my day job for that very reason.  And I insist on repos I work on to not see it come in.

'at since' is ok but that only matters on a very public api and and needs to be consistently used otherwise it's a bit useless.  The history still can indicate when something came in and if users are using the latest which we hope they are, then it's use deminishes.  One prime example of it being noise in my opinion is a recent additionl to 'spotbugs-maven-plugin'.  The submitter used what would be thought to be next version release but I had to change the version number for a patch revision and as such I had to additionally change that commited code.  Further, prior new code was not using 'at since' at all.  So that non consistency gives some very real false impressions.

**Comment by dbwiddis** [comment]
So I discovered `mvn javadoc:fix` and played with it.  The bad news is that it added @author tags everywhere!  The good news is it was easy to search and kill them all, only missing two of them because of the line following them (multiple authors in one, and a `since` in the other).   Fixing those and closing this issue.
