### ISSUE TITLE
oshi-core 4.0.0-b1 is not resolving the correct jna version through maven central

### ISSUE THREAD

**Issue by ramjega** [oshi/oshi#936]
I used oshi-core 4.0.0-b1 from maven central. I got some No such method error and class not found exceptions when running SystemInfoTest in ubuntu 16.04.  After I added the jna version 5.4.0 as dependency , it is working fine

**Comment by dbwiddis** [comment]
Hi, @ramjega and thanks for this report.  The issue you experienced is because of how Maven deals with transitive dependencies.   It first resolves all the first level dependencies in the order you specify in your POM, and then gets all the dependencies of those, and then the dependencies of those dependencies, etc.    This creates a problem if you have a top-level dependency declared in your POM which uses an older version of JNA.

This problem is usually resolved by making oshi the first (or one of the first) dependency in your POM, and if that doesn't work, explicitly declaring the JNA version, as you have done, will nearly always resolve it.

I'm going to close this since you've reported that it's working. Please let me know if there's anything you think we can do on the project side.
